### ISSUE TITLE
extends of tsconfig.json doesn't work when it reference to other package

### ISSUE THREAD

**Issue by kidylee** [TypeStrong/ts-node#2090] opened 2023-11-23 06:36 UTC
### Search Terms

`ts-node` `ts-config.json` `extends`

### Expected Behavior

The issue is from `extends` keyword of `tsconfig.json` file, if it reference to a file based location is file, but if it is reference to a pacakge will occur extendee file not found error.

```
{
    "extends": "@tsconfig/node-lts/tsconfig.json"
}
```

In the meanwhile, `tsc` and `jest.config.js` doesn't have this issue.

### Actual Behavior
```
╰─ pnpm test-ts                                                                                                                                                         ─╯

> ts-config-extends@1.0.0 test-ts /Users/anli/Developer/pp/ts-config-extends
> jest --config jest.config.ts --passWithNoTests

Error: Jest: Failed to parse the TypeScript config file /Users/anli/Developer/pp/ts-config-extends/jest.config.ts
  TSError: ⨯ Unable to compile TypeScript:
error TS6053: File '@tsconfig/node-lts/tsconfig.json' not found.
    at readConfigFileAndSetRootDir (/Users/anli/Developer/pp/ts-config-extends/node_modules/.pnpm/jest-config@29.7.0_@types+node@20.9.4_ts-node@10.9.1/node_modules/jest-config/build/readConfigFileAndSetRootDir.js:116:13)
    at async readInitialOptions (/Users/anli/Developer/pp/ts-config-extends/node_modules/.pnpm/jest-config@29.7.0_@types+node@20.9.4_ts-node@10.9.1/node_modules/jest-config/build/index.js:392:15)
    at async readConfig (/Users/anli/Developer/pp/ts-config-extends/node_modules/.pnpm/jest-config@29.7.0_@types+node@20.9.4_ts-node@10.9.1/node_modules/jest-config/build/index.js:147:48)
    at async readConfigs (/Users/anli/Developer/pp/ts-config-extends/node_modules/.pnpm/jest-config@29.7.0_@types+node@20.9.4_ts-node@10.9.1/node_modules/jest-config/build/index.js:424:26)
    at async runCLI (/Users/anli/Developer/pp/ts-config-extends/node_modules/.pnpm/@jest+core@29.7.0_ts-node@10.9.1/node_modules/@jest/core/build/cli/index.js:151:59)
    at async Object.run (/Users/anli/Developer/pp/ts-config-extends/node_modules/.pnpm/jest-cli@29.7.0_@types+node@20.9.4_ts-node@10.9.1/node_modules/jest-cli/build/run.js:130:37)
```

### Steps to reproduce the problem
```
pnpm i
pnpm test-js
pnpm test-ts
```

### Minimal reproduction

https://github.com/kidylee/ts-config-issue-mre

### Specifications

ts-node v10.9.1
node v19.7.0
compiler v5.3.2
```

**Comment by gtjamesa** [comment] 2023-11-23 09:42
Looks to be an issue with TS 5.3

- https://github.com/TypeStrong/ts-node/issues/2076
- https://github.com/microsoft/TypeScript/issues/56492

**Comment by edosrecki** [comment] 2023-11-24 13:27
Hi @kidylee, I believe it is safe to close this issue as a duplicate of #2076.

**Closed** 2023-12-08 11:08 UTC
