### ISSUE TITLE
Cache compilation

### ISSUE THREAD

**Issue by Timmmm** [TypeStrong/ts-node#920] opened 2019-11-29 09:58 UTC
Apparently this used to support caching, but it was removed. Unfortunately caching is pretty much a necessity if you're using this for interactive scripts because compilation is so slow (around 2 seconds for my 100-line script!)

It would be nice to have caching back!

**Comment by blakeembrey** [comment] 2019-11-29 14:12
Duplicate of https://github.com/TypeStrong/ts-node/issues/908 and https://github.com/TypeStrong/ts-node/issues/754. Feel free to test `master` (different compilation mode) or submit a PR.

**Closed by blakeembrey** 2019-11-29 14:12 UTC
