### ISSUE TITLE
Moch+DefinitelyTyped+ESM - module import does not work

### ISSUE THREAD

**Issue by tpluscode** [TypeStrong/ts-node#1772] opened 2022-05-23 14:18 UTC
This is super weird. I have tests in mocha where I import a class from an external package. That package has a `@types` package and it happened that the declarations there were incorrect. Namely, there is only a default export in JS but the types also mention a named export

As long as there is an `export class ...` in the type declarations, the test fail at runtime

### Expected Behavior

A module should import correctly regardless of the contents of `@types` package

### Actual Behavior

Runtime error `ReferenceError: TermSet is not defined`

From the error I understand that the `TermSet` class variable is completely removed from the execution scope.

### Steps to reproduce

1. Clone the gist below
2. yarn test

Now, if you go into `node_modules/@types/rdfjs__term-set/index.d.ts` and correct the declaration, the code will run correctly

```diff
-export class TermSet<T extends Term = Term> {
+declare class TermSet<T extends Term = Term> {
```

### Minimal reproduction

https://gist.github.com/tpluscode/cbcd3f47b45f719475e079dd76801344

### Specifications

* ts-node v10.8.0
* node v14.18.1
* compiler v4.6.3
* tsconfig.json, if you're using one:
```
{
  "compilerOptions": {
    "target": "ES2019",
    "module": "ESNext",
    "moduleResolution": "Node",
    "esModuleInterop": true,
    "declaration": true
  }
}
```

* Operating system and version: macOS 11.6
* If Windows, are you using WSL or WSL2?: no

**Comment by cspotcode** [comment] 2022-05-23 19:36
Weird, looks like a bug with the typescript compiler.  I recommend raising a bug report with them.

If I run `tsc` to compile the TS into JS, I see that the typescipt compiler is emitting the wrong code.  Do you see the same?

**Comment by cspotcode** [comment] 2022-05-23 19:39
Another thing to think about before filing a bug report with them: remember that the compiler intentionally omits type-only imports.  It uses type information to do this.  So this might be a case where bad type information is telling the compiler to omit an import.

See also: https://www.typescriptlang.org/tsconfig#importsNotUsedAsValues
I'm not saying that using the `importsNotUsedAsValues` option will fix this problem, it's just the closest thing I could think of to sharing documentation on this subject.

**Comment by tpluscode** [comment] 2022-05-24 06:23
Yes @cspotcode, this corroborates my observation. The import is removed then default-imported. Setting `"importsNotUsedAsValues": "preserve"` does change the output but it's still wrong

Would you like me to close here then are report in TS instead?

**Comment by tpluscode** [comment] 2022-05-24 06:27
Ah, looks like I found an existing issue: https://github.com/microsoft/TypeScript/issues/47598

**Comment by cspotcode** [comment] 2022-05-24 11:52
Yeah, since we've confirmed this is not a ts-node bug and there is no action to be taken on our end, I'm going to close this.

**Closed** 2022-05-24 11:52 UTC
