### ISSUE TITLE
ERR_UNSUPPORTED_DIR_IMPORT throwing in ESM package

### ISSUE THREAD

**Issue by donmccurdy** [TypeStrong/ts-node#1832] opened 2022-07-11 02:07 UTC
### Search Terms

ava, ESM, ERR_UNSUPPORTED_DIR_IMPORT, typescript, tape

### Expected Behavior

I'm converting TypeScript packages I maintain to be ESM-only. In the process, I'm switching from running tests with tsnode+tape to tsnode+ava. I use microbundle to build the package itself, output to a dist folder, and I have a root `package.json` file that points to that output. Tests in a './test/' directory import from the parent directory like this:

```javascript
import packageToTest from '../'

// ... run tests
```

Previously this worked correctly — VSCode doesn't complain about the import, ts-node resolves the import, and the tests pass. 

### Actual Behavior

After switching to Ava + ESM, VSCode is still fine with the import, but the imports no longer resolve in ts-node and I see the following error:

```
ava test/*.ts | tap-spec
(node:60823) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
      Uncaught exception in test/index.test.ts
      Error: ERR_UNSUPPORTED_DIR_IMPORT /Users/donmccurdy/Documents/Projects/typescript-library-template/ /Users/donmccurdy/Documents/Projects/typescript-library-template/test/index.test.ts
      › finalizeResolution (node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:362:17)
      › moduleResolve (node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:801:10)
      › Object.defaultResolve (node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:912:11)
      › node_modules/ts-node/src/esm.ts:218:35
      › entrypointFallback (node_modules/ts-node/src/esm.ts:168:34)
      › node_modules/ts-node/src/esm.ts:217:14
      › addShortCircuitFlag (node_modules/ts-node/src/esm.ts:409:21)
      › resolve (node_modules/ts-node/src/esm.ts:197:12)
      ✖ test/index.test.ts exited with a non-zero exit code: 1
      ─
      1 uncaught exception


error Command failed with exit code 1.
```

### Steps to reproduce the problem

The `typescript-library-template` package is a template repository, basically the boilerplate used in my other projects. Attached below is the PR attempting to switch the project to tsnode+Ava:

https://github.com/donmccurdy/typescript-library-template/pull/4

I've tried to follow https://typestrong.org/ts-node/docs/recipes/ava/ and https://github.com/avajs/ava/blob/main/docs/recipes/typescript.md#for-packages-with-type-module ... those guides don't quite match but I did try a few variations.

### Minimal reproduction

See link above.

### Specifications

- ts-node: v10.8.2
- node: v18.5.0
- compiler: v4.7.4
- os: macOS

<details>

<summary><b>tsconfig.json</b></summary>

```
{
	"compilerOptions": {
		"moduleResolution": "node",
		"module": "es2020",
		"lib": ["es2020"],
		"target": "es2020",
		"declaration": true,
		"typeRoots": ["node_modules/@types"],
		"strict": true
	}
}
```

</details>

<details>

<summary><b>package.json</b></summary>

```
{
  "name": "my-package",
  "version": "0.0.0",
  "description": "my-package",
  "type": "module",
  "sideEffects": false,
  "source": "./src/index.ts",
  "exports": "./dist/my-package.modern.js",
  "types": "./dist/index.d.ts",
  "repository": "github:donmccurdy/my-package",
  "author": "Don McCurdy <dm@donmccurdy.com>",
  "license": "MIT",
  "scripts": {
    "dist": "microbundle --format modern --define PACKAGE_VERSION=$npm_package_version",
    "watch": "microbundle watch --format modern --define PACKAGE_VERSION=$npm_package_version",
    "watch:debug": "microbundle watch --no-compress --format modern --define PACKAGE_VERSION=$npm_package_version",
    "test": "ava test/*.ts | tap-spec",
    "coverage": "nyc --reporter=lcov --reporter=text ava test/*.ts",
    "coverage:report": "nyc report --reporter=text-lcov > .nyc_output/coverage.lcov",
    "preversion": "yarn dist && yarn test",
    "version": "rimraf dist/* && yarn dist && git add -u",
    "postversion": "git push && git push --tags && npm publish && yarn coverage:report"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "5.30.5",
    "ava": "^4.3.1",
    "eslint": "8.19.0",
    "eslint-config-prettier": "8.5.0",
    "microbundle": "0.15.0",
    "nyc": "15.1.0",
    "prettier": "2.7.1",
    "rimraf": "^3.0.2",
    "tap-spec": "5.0.0",
    "ts-node": "^10.8.2",
    "typescript": "4.7.4"
  },
  "files": [
    "dist/",
    "src/",
    "README.md",
    "LICENSE",
    "package.json"
  ],
  "ava": {
    "extensions": {
      "ts": "module"
    },
    "nodeArguments": [
      "--loader=ts-node/esm"
    ]
  }
}

```

</details>

**Comment by cspotcode** [comment] 2022-07-11 02:58
What we're describing sounds like node's expected ESM behavior.  That is to say, when you convert a project to ESM, importing directories will not work in this way.  Because node supports directory imports for CJS and not for ESM.  This is an intentional, documented change in node's behavior.

**Comment by donmccurdy** [comment] 2022-07-11 03:12
Thanks @cspotcode! Note there's no `index.js` in the imported folder, I'm relying on the `package.json` file to resolve `"exports": "./dist/my-package.modern.js",` ... does Node.js not inspect `package.json` for directory inputs? Reading through the [resolver argorithm](https://nodejs.org/api/esm.html#esm_resolver_algorithm) is not going great. 

None of the usual import paths seem to work, then:

- `../` fails in Node.js with ESM, as described
- `my-package` fails, "Cannot find module 'my-package' or its corresponding type declarations." ... this is the package defined by the local `package.json`.
- `../dist/my-package.modern.js` fails, "error TS7016: Could not find a declaration file for module '../dist/my-package.modern.js'." ... the type definitions exist, but aren't discoverable on this import path.

**Comment by donmccurdy** [comment] 2022-07-11 03:18
Hm, I may have found a workaround but I don't really understand it. I added the following line to `compilerOptions` in tsconfig.json —

```js
"paths": {
  "my-package": ["./"]
},
```

With that, the following import succeeds:

```js
import packageToTest from 'my-package';
```

As far as I can tell I'm still doing a directory import here, but it seems to work this way! 😕

**Comment by cspotcode** [comment] 2022-07-22 18:27
Closing as seems like this is a support request, not a bug report or feature request.  Support requests are best raised on the TypeScript Community Discord: great community over there.

**Closed by cspotcode** 2022-07-22 18:27 UTC

**Comment by matthiasg** [comment] 2023-05-25 07:01
Not sure this should have been closed. When the typescript compiler compiles the source fine, with those settings why does ts-node not ?

**Comment by staff0rd** [comment] 2024-03-14 12:06
I was getting this error until i changed this:
```bash
node --loader ts-node/esm ./src/index.ts
```
to this:

```bash
node --experimental-specifier-resolution=node --loader ts-node/esm ./src/index.ts
```
