### ISSUE TITLE
doesn't work with typescript@next

### ISSUE THREAD

**Issue by arolson101** [TypeStrong/ts-node#18] opened 2015-10-31 05:25 UTC
```
/Users/aolson/Developer/updraft/node_modules/ts-node/dist/ts-node.js:32
    return ts.parseConfigFile(config, ts.sys, fileName);
              ^

TypeError: ts.parseConfigFile is not a function
    at readConfig (/Users/aolson/Developer/updraft/node_modules/ts-node/dist/ts-node.js:32:15)
    at Object.register (/Users/aolson/Developer/updraft/node_modules/ts-node/dist/ts-node.js:41:18)
    at Object.<anonymous> (/Users/aolson/Developer/updraft/Gulpfile.js:55:20)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
```

looks like they [renamed parseConfigFile to parseJsonConfigFileContent](https://github.com/Microsoft/TypeScript/commit/002f0c066b3d6f117bf418ffaf3b51397a0d2efc#diff-057bf8560e435e388ba45f7810c3d08d)

**Comment by blakeembrey** [comment] 2015-10-31 16:08
Duplicate of #15. I will be fixing this over the weekend, just been busy with work and https://github.com/typings/cli.

**Closed by blakeembrey** 2015-10-31 16:08 UTC

**Comment by blakeembrey** [comment] 2015-11-02 17:47
Released with `v0.4.1`

**Comment by tonypee** [comment] 2016-06-15 03:38
It might be good to remove the https://www.npmjs.com/package/typescript-node npm package, as without reading closely it is confusingly holding old code (i just tried to use it and ended up here)

or update both?

**Comment by blakeembrey** [comment] 2016-06-15 03:40
There's a deprecation notice when you install and in the README. It can be deleted though, sure.
