### ISSUE TITLE
ts-node --inspect does not work on 5.0.0

### ISSUE THREAD

**Issue by xueeey** [TypeStrong/ts-node#543] opened 2018-02-28 20:11 UTC
```
$ ts-node --inspect==5858 src/index.ts
Server started at http://localhost:8080
```

Works fine with v4.1.0

**Comment by blakeembrey** [comment] 2018-03-01 04:27
Duplicate of https://github.com/TypeStrong/ts-node/issues/537. Please search before opening another issue, especially since the issue directly before this is the exact same.

**Closed by blakeembrey** 2018-03-01 04:27 UTC

**Comment by gyerts** [comment] 2020-03-24 20:04
ts-node --files ./src/index.ts --inspect

**Comment by benbieler** [comment] 2020-05-07 19:56
you need to use something like this: `**node inspect=9999 -r** ts-node src/index.ts`
