### ISSUE TITLE
Does not work after upgrading to 4.0.0

### ISSUE THREAD

**Issue by lednhatkhanh** [TypeStrong/ts-node#480] opened 2017-12-11 17:08 UTC
`ts-node` just suddenly stop working after upgrading to 4.0.0 (The same with 4.0.1):

nodemon.json
```json
{
	"watch": ["src"],
	"ext": "ts",
	"ignore": ["src/**/*.spec.ts"],
	"exec": "ts-node -P ./tsconfig.json --no-cache ./src/index.ts"
}
```

tsconfig.json
```json
{
	"compilerOptions": {
		"target": "esnext",
		"module": "commonjs",
		"sourceMap": true,
		"lib": ["esnext"],
		"outDir": "build",
		"rootDir": "src",
		"importHelpers": true,
		"noEmitOnError": true,
		"strict": true,
		"noUnusedLocals": true,
		"noUnusedParameters": true,
		"noImplicitReturns": true,
		"noFallthroughCasesInSwitch": true,
		"moduleResolution": "node",
		"experimentalDecorators": true,
		"emitDecoratorMetadata": true
	}
}
```

nodemon: 1.12.5 (dev dependency)
typescirpt: 2.6.2 (dev dependency)
ts-node: 4.0.1 (dev dependency)

Reverted ts-node back to 3.30 solved the problem.

**Comment by fox1t** [comment] 2017-12-12 09:40
Hi, i have the same problem when using ts-node >= 4.x.x. When i save a file, node process isn't killed and both dev port and inspector port remains used. If i downgrade to 3.x.x, it starts working again. I use this npm scripts to start in dev mode:
`"nodemon": "nodemon -e ts -w \"./src\" -x \"npm run debug\"",`
`"debug": "ts-node --inspect ./src/index.ts",`

**Comment by unlight** [comment] 2017-12-12 17:55
Possible duplicate #481

**Comment by blakeembrey** [comment] 2017-12-14 16:23
Can you share the OS or other information so someone can help you debug?

**Comment by fox1t** [comment] 2017-12-14 16:31
macOS: 10.13.2
nodemon: 1.12.5 (dev dependency)
typescirpt: 2.6.2 (dev dependency)
ts-node: 4.0.1 (dev dependency)

I haven't spare time to debug at the moment , otherwise i could do it and post even more info.

**Comment by blakeembrey** [comment] 2017-12-14 17:06
Interesting, thanks. I thought it may have been a duplicate of https://github.com/TypeStrong/ts-node/issues/481, but not if it's on mac. Looks like these issues may be negative side effects of https://github.com/TypeStrong/ts-node/pull/419.

For anyone running into this, can you switch to using `node -r ts-node/register`? This avoids many of the process issues that were occurring and is likely the recommended way to use in the next release.

**Comment by unlight** [comment] 2017-12-14 18:00
node v8.9.0 Win8.1x64 `node -r ts-node/register` works for me.

**Comment by stelcheck** [comment] 2017-12-15 03:06
@blakeembrey just switched on my windows machine and everything seems to work fine when I rebuild from master on the repo. I do run into this issue when installing from NPM however.

**Comment by blakeembrey** [comment] 2017-12-15 03:59
@stelcheck That's really odd, there shouldn't be a difference between what's on master. Can you diff your built files at all? Maybe something in my release pipeline broke, that would be odd.

**Comment by stelcheck** [comment] 2017-12-15 04:01
Never mind, I was able to reproduce the issue locally. 

There seems to be two issues: one related to how early errors are piped through on Windows (maybe mac?), the other I am still investigating. Trying to get a PR in ASAP.

**Comment by k8w** [comment] 2017-12-15 04:10
@blakeembrey Also not work after upgrade 4.0.1

OS: Win10
Node: 8.9.1

**Comment by stelcheck** [comment] 2017-12-15 04:49
The cause of the issue appears to be that `process.stdin/out/err` cannot be inherited by spawned processes on Windows. I couldn't find a solid reference to that issue, but that's the only thing that seems to be different.

That explains both why nothing gets printed out (the error happens in the subprocess, and its stdout/err is not piped to the main process), but also explains the actual crash (stdin is not a TTY, and no file names are being passed, so the code tries to read... nothing)

Since the reason that happens on Windows is because of a fix that was made essentially for *nix system, I'd say the simplest solution would be to not run in detached mode on Windows. I'll make a PR for that right now.

**Comment by stelcheck** [comment] 2017-12-15 04:54
Addendum: I suspect there might be something going on when using `ts-node` as a sub-process as well. (which would explain issues on macOS). I'll reboot on Linux soon and will check that as well.

**Comment by stelcheck** [comment] 2017-12-15 05:09
Just double-checked on Linux:

```shell
echo "process.on('SIGINT', () => console.log('called')); setInterval(() => console.log('sadasd'), 1000)" | node dist/bin.js
```

This seems to work properly. @fox1t is it possible that you also catch 'SIGTERM' in your app? You might also want to look into configuring a specific signal for nodemon https://github.com/remy/nodemon/pull/725 89 (been a while I haven't used it, assuming this is still configurable).

**Comment by stelcheck** [comment] 2017-12-15 05:19
@fox1t Also, I see this issue in nodemon's issue tracker: https://github.com/remy/nodemon/issues/1164 - the reporter is on Windows, but perhaps it is related to your issue as well?

**Comment by stelcheck** [comment] 2017-12-20 08:23
Here is another PR which would also solve the issue by simply removing subprocesses overall: https://github.com/TypeStrong/ts-node/pull/499

**Comment by ricardasjak** [comment] 2017-12-21 17:11
Same problem here after upgrade from 3.3.0 to 4.0.1
Windows 10,
Node 9.2.0

However it works fine on CI (unix) build server.

**Closed** 2017-12-23 02:28 UTC
Labels: bug
