### ISSUE TITLE
Running ts-node through npm with `--project`

### ISSUE THREAD

**Issue by unional** [TypeStrong/ts-node#83] opened 2016-03-21 18:13 UTC
I try to run:
```sh
ts-node --project test test/test.ts
```
it is working fine. But if I run it through `npm` it does not:
```js
// package.json
{
  "scripts" {
    "test": "ts-node --project test test/test.ts"
  }
}
```
```sh
npm test
# TSError: ⨯ Unable to compile TypeScript
# test/test.ts (1,24): Cannot find module 'batch'. (2307)
```

What am I missing?
I'm working on `typed-typings/npm-batch` to see how it works using the tests in source package.

**Comment by blakeembrey** [comment] 2016-03-23 21:42
Looks like you have different versions locally and globally. Since I use the TypeScript compiler to resolve `tsconfig.json` now, it's a duplicate of https://github.com/Microsoft/TypeScript/issues/2965. I need to do a PR once I can to fix this, I've had that issue around for _way too long_.

**Closed by blakeembrey** 2016-03-23 21:42 UTC
