### ISSUE TITLE
Stuck in type checking loop

### ISSUE THREAD

**Issue by OliverJAsh** [TypeStrong/ts-node#400] opened 2017-08-04 08:57 UTC
Hi!

I have a project which compiles OK using `tsc`, but when I use `ts-node` it seems to get stuck in an infinite loop of `fileExists` and `directoryExists` (seen when enabling `TS_NODE_DEBUG`).

If I specify `TS_NODE_FAST`, the script will complete successfully. This seems to suggest the problem is related to the type checking.

Do you have any tips for debugging this? Have you seen this issue before? 

[Here is some of the output](https://gist.github.com/230e6b57534160caa11435fbe243a654). I can't possibly paste it all because it goes on forever. The longest I've left it running is 10 minutes, so I'm assuming it's stuck in a loop—especially considering `tsc` completes in seconds.

I will try to reduce it to the smallest reproduction case, but it won't be easy.

Thanks,
Oliver

**Comment by blakeembrey** [comment] 2017-08-04 20:05
I haven't encountered this before, no. Seems odd, since only TypeScript is in charge of traversing the files. There's a couple of things I can think of to verify that we could could try:

1. Replace `ts.sys.directoryExists` with a custom implementation - here's some code from a previous implementation: https://github.com/TypeStrong/ts-node/commit/3f0d97520ccd7574566e5970cc511937f06599af#diff-f41e9d04a45c83f3b6f6e630f10117feL551
2. Check the cache function (https://github.com/TypeStrong/ts-node/blob/668e9efa245359f29ec62f95087fb4ebc020d95f/src/index.ts#L263-L266) for whether the content is in a loop because of the version increment

**Comment by OliverJAsh** [comment] 2017-08-07 10:41
Thanks @blakeembrey!

I just tried replacing `directoryExists` with a custom implementation and I'm now getting a `Cannot find module` `TSError` for a module in `node_modules`. I'm not sure if this is related.

I also tried removing the version increment (`+ 1`) from `setCache`, just to see if that made any difference, but I'm not seeing any changes.

For context, I am using `ts-node/register` alongside `babel-register`, using the fix provided in https://github.com/babel/babel/pull/5386. I will likely try to use `ts-node` again when we come to remove Babel from the mix (we're incrementally migrating at the moment).

**Comment by blakeembrey** [comment] 2017-08-07 17:22
Do you have a type definition for the module that gets "Cannot find module"? The odd thing is that the TypeScript implementation should be largely the same as the custom one: https://github.com/Microsoft/TypeScript/blob/bb34bce4208c8a7b1e875a27b07e67dea0e7fe7a/src/compiler/sys.ts#L318-L337.

**Comment by OliverJAsh** [comment] 2017-08-07 17:28
I don't have a type definition, but I haven't enabled `noImplicitAny` so that shouldn't matter.

Hmm, very odd.

**Comment by astashov** [comment] 2017-08-31 14:29
I have a similar issue, but it's somewhat intermittent. I use `ts-node` to run `mocha`, via `ts-node/register`. If I run `npm run test` with `TS_NODE_DEBUG`, and if it's not stuck, then I mostly see `module._compile` / `readThrough` for each file, going through like 150-200 files per second and then the actual tests start.

In case when it's stuck, I see `module._compile` / `readThrough` first going fast, but at some point they start to write a lot of repeating `fileExists` / `directoryExists` before each `module._compile` / `readThrough`, speed drops to like 2-3 `readThrough` files per second, and since there're like thousands of files to load, it looks like it's stuck, but it just going through very slow.

I've never seen such issue on TypeScript <= 2.3, it only started to happen with TypeScript 2.4

**Comment by astashov** [comment] 2017-11-14 17:25
This PR solves the issue for me: https://github.com/TypeStrong/ts-node/pull/461

**Comment by trusktr** [comment] 2018-08-05 17:14
I haven't had this problem (and maybe that PR fixed it), but a workaround would be to run `ts-node` without type checking, then just run `tsc` separately with no emit to perform type checking.

**Comment by SDepn** [comment] 2018-12-06 10:59
We are currently encoutering the same issue. It is not stuck in a loop, but the building of the cache in `%TMP%/ts-node...` is taking forever.

 A fully built cache for our project is currently around 75MB. Renaming this folder and restarting ts-node with `TS_NODE_DEBUG=true` displays what @OliverJAsh described. After one hour of compilation I cancelled it and roughly 5MB of Cache have been built. This means it would take over 12 hours for an initial run of our project. Starting the project with transpile-only is working fine.

**Comment by gustavopch** [comment] 2018-12-06 14:43
Same here. When I run `ts-node`, it's taking a minute or so to load. It used to take 5s a few days ago. With `TS_NODE_DEBUG=true`, I can see a lot of fileExists / directoryExists, mainly on directories inside node_modules. Don't know why as my tsconfig.json is excluding node_modules. I'm using 7.0.1.

**Comment by SDepn** [comment] 2019-02-25 13:05
@blakeembrey Any news on this topic? We still have the issue, that running ts-node after some changes to node_modules can take up to an hour with an already existing cache.

**Comment by cspotcode** [comment] 2021-06-14 04:17
Closing because this issue is old and I suspect it has been solved by some combination of improvements to our in-memory caching, to our path normalization, to our `*Host` implementations, or due to general improvements in TypeScript itself.

If anyone has this problem today, please open a new issue *with a reproduction*.  You can link it to this issue if you want.

**Closed by cspotcode** 2021-06-14 04:17 UTC
Labels: bug, research
