### ISSUE TITLE
`ts-node xxx.ts` run in bat file will auto close cmd window

### ISSUE THREAD

**Issue by hpyou** [TypeStrong/ts-node#899] opened 2019-10-30 07:16 UTC

**Comment by blakeembrey** [comment] 2019-10-31 02:30
What's the expected behavior? I don't really know what a bat file is, nor why it should or shouldn't close. If it's just a script, why wouldn't it close? Does `node` have the same behavior?

**Comment by hpyou** [comment] 2019-10-31 11:05
`
echo start cmd ...
ts-node xxx.ts
echo end cmd...
pause
`

when run this bat file,it will auto close by finished to execute `ts-node xxx.ts`, and will not print `end cmd ....`, but if run `node xxx.js`, it will run all cmd, and not close the window

**Comment by blakeembrey** [comment] 2019-11-08 02:54
Do you want to create a reproduction I can test? I don't really use Windows normally so don't know where to start with debugging this.

**Comment by hpyou** [comment] 2019-11-08 03:19
demo.bat
```
echo start cmd ...

ts-node demo.ts

echo end cmd...

pause
```

demo.ts
```
console.log('enter demo.ts')
```

Normally， this command window will not be closed because of the `pause` command in demo.bat, 
but if halfway run `ts-node demo.ts`, it will be closed by  finished to execute the typescript file

**Comment by blakeembrey** [comment] 2019-11-08 07:14
How do I run the file?

**Comment by hpyou** [comment] 2019-11-08 07:40
in windows system you just double click the demo.bat file

**Comment by G-Rath** [comment] 2019-12-09 19:28
@blakeembrey I can confirm this behaviour:

```
C:\Users\G-Rath>tsc demo.ts

C:\Users\G-Rath>nano demo.bat

C:\Users\G-Rath>demo.bat

C:\Users\G-Rath>echo start cmd
start cmd

C:\Users\G-Rath>node ./demo.js
hello world

C:\Users\G-Rath>echo end cmd
end cmd

C:\Users\G-Rath>pause
Press any key to continue . . .
```

vs

```
C:\Users\G-Rath>demo.bat

C:\Users\G-Rath>echo start cmd
start cmd

C:\Users\G-Rath>ts-node ./demo.ts
hello world

C:\Users\G-Rath>
```

That's using latest TS & ts-node.

`ts-node` is doing something differently on Windows vs regular node - no idea what tho 🤷‍♂ 

To run, you can call it via cmd by just doing `demo.bat`.

**Comment by blakeembrey** [comment] 2019-12-10 17:30
@G-Rath Would you be interested in helping contribute a fix? I don't usually have a windows machine around, and also never had to develop on one so it might take me a while to find the issue.

**Comment by blakeembrey** [comment] 2019-12-10 17:31
Also, do you get the same behavior with `node --require ts-node/register`?

**Comment by G-Rath** [comment] 2019-12-17 19:48
@blakeembrey I'll have a look into it, but can't promise anything as I use WSL and don't know enough about the underlying differences in `ts-node` vs `node` (aka: I need to upskill on piping & streams :joy:)

If you have a guess on where the problem could lie, that would be good for a starting point :)

**Comment by blakeembrey** [comment] 2019-12-18 01:45
I'd probably confirm that `node -r ts-node/register` works as you'd expect from `node`, that'll narrow it down to only the `bin` file (so something related to starting the program). From there it's a bit trickier, but there's no actually many lines of code - basically it called `Module.runMain()`.

**Comment by cspotcode** [comment] 2020-01-22 22:26
@hpyou 

This is an issue with your .bat script, due to the way .bat / .cmd scripts interact and the way npm's cmd shims are implemented.  This is not a bug in ts-node.

## The fix

Modify your batch script to use `call` when invoking `ts-node`.

```
echo start cmd ...
call ts-node demo.ts
echo end cmd...
pause
```
 
## The reason

npm emits cmd shim scripts on Windows.  When your `.bat` script calls `ts-node`, it is invoking `ts-node.cmd`.  When `ts-node.cmd` runs `EXIT /b` it terminates the *outer* `.bat` file.  Using `call` behaves the way you want, allowing the inner `.cmd` script to exit and the outer script to resume.

https://ss64.com/nt/exit.html
https://ss64.com/nt/call.html
https://www.npmjs.com/package/cmd-shim

**Comment by cspotcode** [comment] 2020-01-24 16:27
Closing this because it's a bit old and I'm almost positive https://github.com/TypeStrong/ts-node/issues/899#issuecomment-577415320 correctly addresses the problem.  Please don't hesitate to reply if the issue is not resolved, and we can re-open.

**Closed by cspotcode** 2020-01-24 16:27 UTC
Labels: needs more info
