### ISSUE TITLE
syntax error in default parameter

### ISSUE THREAD

**Issue by snowbay** [TypeStrong/ts-node#53] opened 2016-01-17 02:22 UTC
Hi, I cannot use default parameter

```js
// hello.ts
function hello(name = 'World') {
    console.log(`Hello, ${name}`)
}
```
```bash
$ ts-node hello.ts
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.loader (/sandbox/node_modules/ts-node/src/ts-node.ts:225:14)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at Object.<anonymous> (/sandbox/node_modules/ts-node/src/bin/ts-node.ts:121:12)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
```

below code works fine
```js
function hello(name) {
    console.log(`Hello, ${name}`)
}
```

environment
---
+ node: 5.4.0
+ typescript: 1.7.5
+ tsconfig.json
```
{
    "compilerOptions": {
        "target": "es6",
        "noImplicitAny": false,
        "sourceMap": false
    },
    "exclude": [ "node_modules" ]
}
```

thanks.

**Comment by blakeembrey** [comment] 2016-01-17 04:22
This is an issue with node + TypeScript. Node doesn't support all of ES6 currently, so your program is crashing on certain ES6 features. You can use ES5 for now. I'm going to close as a duplicate of https://github.com/TypeStrong/ts-node/issues/43, and check out the conversation at https://github.com/Microsoft/TypeScript/issues/4692.

**Closed by blakeembrey** 2016-01-17 04:22 UTC
