### ISSUE TITLE
v8.6.0 breaks TS_NODE_COMPILER_OPTIONS environment variable

### ISSUE THREAD

**Issue by dstaley** [TypeStrong/ts-node#938] opened 2020-01-10 18:40 UTC
The release of v8.6.0 introduced the ability to configure via tsconfig.json. However, it looks like in the process the ability to use TS_NODE_COMPILER_OPTIONS was either removed or broken, resulting in broken builds for us.

Since v8.6.0 was a minor semver release and did not have a "Breaking Changes" section in the release notes, I did not anticipate any breaking changes in this release. If the change was intentional, I suggest adding a "Breaking Changes" section to the release notes, otherwise a patch release that restores the behavior would be appreciated! In the meantime I've moved to using tsconfig.json, so this would just be for other users who find themselves in the same situation I found myself in.

**Comment by cspotcode** [comment] 2020-01-10 18:52
Do you have a minimal reproducible example of the bug, to help with
diagnosis?

This is not intended to be a breaking change, hence the minor version bump.

Affected users can continue using the previous version of ts-node in the
meantime.

**Comment by dstaley** [comment] 2020-01-10 19:05
Sure thing! [Here you go](https://github.com/dstaley/ts-node-envar).

**Comment by blakeembrey** [comment] 2020-01-10 20:49
Thanks for the report, I think I may have introduced it when refactoring the `tsconfig.json` support. Revising the logic now.

**Comment by cspotcode** [comment] 2020-01-10 21:01
`DEFAULTS.compilerOptions` should store the value parsed from the environment variable.
https://github.com/TypeStrong/ts-node/blob/master/src/index.ts#L242

`readConfig` pulls from `DEFAULTS` when building the merged `compilerOptions` object.
https://github.com/TypeStrong/ts-node/blob/master/src/index.ts#L909-L916

Shouldn't that be correctly incorporating the environment variable?

**Comment by cspotcode** [comment] 2020-01-10 21:08
Oh I think it's because of the ordering of overrides.

I put the 2 indicated values out of order.  ([from here](https://github.com/TypeStrong/ts-node/blob/master/src/index.ts#L909-L916))

```
config.compilerOptions = Object.assign(
    {},
    DEFAULTS.compilerOptions,  // <-- the env var
    config.compilerOptions, // <-- the tsconfig's "compilerOptions"
    config['ts-node']?.compilerOptions,
    options.compilerOptions,
    TS_NODE_COMPILER_OPTIONS
  )
```

**Comment by blakeembrey** [comment] 2020-01-10 21:47
Fixed with https://github.com/TypeStrong/ts-node/commit/db409d75278aaf407fff6385a9bcd2ebd8473e1e and release as V8.6.1 - thanks!

**Closed by blakeembrey** 2020-01-10 21:47 UTC
