### ISSUE TITLE
ts-node tries to compile any imported files

### ISSUE THREAD

**Issue by jasdeep-compro** [TypeStrong/ts-node#545] opened 2018-03-01 11:25 UTC
Hi, while running test with mocha I got an issue.  ts-node tries to compile my 3rd-party  javascript imports which are already compiled. Is there a way to ignore the javascript imports ?

**Comment by blakeembrey** [comment] 2018-03-01 17:26
I need more information to help you. Can you share an example of a 3rd-party JavaScript import which is having trouble?

**Comment by pumano** [comment] 2018-03-13 15:56
I have same problem. I use mocha with ts-node/register and it have problem with es6 imports of another libs.

```
C:\Repository\my-project\node_modules\react-native-vector-icons\MaterialCommunityIcons.js:6
import createIconSet from './lib/create-icon-set';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:576:28)
    at Module._extensions..js (module.js:623:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Repository\myproject\node_modules\ts-node\src\index.ts:392:14)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Repository\myproject\src\ui\LoginForm.tsx:10:1)
    at Module._compile (module.js:612:30)
```

**Comment by Jiahui-Ruan** [comment] 2018-03-13 18:59
I have same problem with @pumano when I want to import es6 module that I written in other folder inside my project.

**Comment by blakeembrey** [comment] 2018-03-14 03:17
@pumano @Jiahui-Ruan That sounds like the opposite problem to OP. I'm closing this now since I haven't had a response and both your reports means it works correctly.

**Closed by blakeembrey** 2018-03-14 03:17 UTC
Labels: needs more info

**Comment by blakeembrey** [comment] 2018-03-14 03:21
@Jiahui-Ruan Please provide more information when you have a problem. There's nothing actionable I can do to help you with your response. What's the folders look like? What's the files look like? Can you make a reproduction?

@pumano You shouldn't be importing ES6 modules from other libs. Can you share how you're ending up with that?

**Comment by pumano** [comment] 2018-03-14 12:53
@blakeembrey I use react-native with typescript. When I try to unit test it via mocha + ts-node/register I got imports in my application with libraries that contain ES6 code with ES6 imports. And it causes error (I was provided stacktrace below). I don't figure out how to solve that problem.

**Comment by jasdeep-compro** [comment] 2018-03-14 12:58
@blakeembrey Sorry I couldn't reply earlier. The problem faced by @pumano is similar to mine. The libraries I'm importing contains ES6 imports.  I'm not sure if I can create a git repo for reproduction.

@pumano It would be really helpful if you can create a reproduction at your end.

**Comment by blakeembrey** [comment] 2018-03-14 17:45
Can either of you tell me what the expected behaviour would look like? I got the impression from the text in OP that you don't want it to compile 3rd party scripts, but now it sounds like you want it to. Are you all using `allowJs`? 

I'm also not familiar with `react-native`, does it import ES6 files somehow? I just can't see in the lib you mentioned any reference to the ES6 files, they're published to NPM as CommonJS with babel (https://github.com/oblador/react-native-vector-icons/blob/37cb9a82be4be7d835b8dea45ca638542877b216/package.json#L5).

**Comment by LKay** [comment] 2018-04-23 03:14
I have similar problem. Some of my dependencies are delivered as javascript ES6 modules only without ES5 version. So I want to transpile them using babel before they get processed by ts-node. I tried to include `@babel/polyfill` and `@babel/register` with proper `ignore` rules whitelisting only these specific modules from `node_modules` but ts-node ignores that and tries to use ES6 version where it shouldn't Is there any working solution to this problem?

**Comment by blakeembrey** [comment] 2018-04-24 02:01
You need to provide more information or a reproduction if you would like help. I’m 90% confident your issue is not with `ts-node` since you mention Babel.
