### ISSUE TITLE
Very slow start (with tsconfig.json)

### ISSUE THREAD

**Issue by whitecolor** [TypeStrong/ts-node#137] opened 2016-06-19 04:22 UTC
I'm just trying TS and node. Use just:
```
// index.js
require('ts-node/register')
```
My server index.js starts about 2 minutes.

If I remove `tsconfig.json` from root (it can be even empty) server starts normally. What can be the reason for such behaviour?

**Comment by blakeembrey** [comment] 2016-06-20 05:14
What version are you using? How big is the project? What additional files are being included?

**Comment by whitecolor** [comment] 2016-06-20 08:09
ts-node the last versions at current moment, typescript 1.8.10 (locally installed in the project)
Windows 10 64x, Node 5.5.0, npm 3.3.12

Protect is not big I would say but many deps. ONE ts file.

Alos I transpile babel using
`require('babel-core/register')` hook

As I've said it seem to work ok without `tsconfig.json`

**Comment by blakeembrey** [comment] 2016-06-20 15:54
The only reason I can imagine this happening (taking a while) is if you have a ton of subdirectories or a symlink to a ton of directories. When loading, it's doing a glob of files if you aren't using `files` in `tsconfig.json`. Can you share your `tsconfig.json` file?

**Comment by whitecolor** [comment] 2016-06-20 16:48
Well it is actually empty.
Yes I have a quite a lot of npm linked modules, I thought `exclude` node_modules should help. But it doesn't.
But it seems its ok with "files"
```
"files": [
  "*.ts"
]
```

**Comment by whitecolor** [comment] 2016-06-20 16:51
Well it is actually empty.
Yes I have a quite a lot of npm linked modules, I thought `exclude` node_modules should help. But it doesn't.
But it seems its ok with "files"
```
"files": [
  "*.ts"
]
```

**Comment by blakeembrey** [comment] 2016-06-20 16:54
@whitecolor That's not how `files` works, it's not a glob. Given that, I was just checking and `ts-node` isn't actually doing any resolving of files (just of `tsconfig.json`). It seems more of the slowness of coming from TypeScript trying to resolve imports then.

**Comment by whitecolor** [comment] 2016-06-20 17:18
Why then adding `"files": ["*.ts"]` helps?

**Comment by blakeembrey** [comment] 2016-06-20 17:22
Because it matches nothing.

**Comment by blakeembrey** [comment] 2016-06-20 17:24
Without it, TypeScript starts resolving the files in the current project for compilation. It's possible we can add another hack to make it so it only resolves the files we want and node is accessing.

**Comment by whitecolor** [comment] 2016-06-20 17:26
Babel-core/register works with no prob, should do something like them.

**Comment by blakeembrey** [comment] 2016-06-20 17:35
Yes, but TypeScript is not Babel.

**Comment by threehams** [comment] 2016-07-09 21:38
I have a project with this issue, but it only occurs with nightly builds of 2.0.0. I'll bisect for a bit to see if I can narrow down the release which causes it.

**Comment by threehams** [comment] 2016-07-10 05:03
Repro steps are completely different than this one - it's Windows-only, affects `ts-node` but not `tsc`, and was introduced with the Typescript 2.0 branch. Go ahead and ignore my report - I need to narrow it down, and it's likely a problem with Typescript itself.

**Comment by blakeembrey** [comment] 2016-07-20 01:36
Closing this as answered, feel free to open a new issue or continue the discussion here. If there's a major, reproducible issue with `tsconfig.json` I'd love to fix it.

**Comment by blakeembrey** [comment] 2016-07-20 01:37
@whitecolor By the way, if all you want is something that works like `babel` and does no type checking, maybe the `--fast` flag is what you're after.

**Closed by blakeembrey** 2016-07-20 01:36 UTC
Labels: question

**Comment by whitecolor** [comment] 2016-12-25 12:21
@blakeembrey Again I'm facing that issue, how is it possible to debug which files are handled by ts-node? Also which `tsconfig.json` it does use. Some debug ability is really needed, but can not find it.

**Comment by blakeembrey** [comment] 2016-12-25 15:04
@whitecolor It just gives the sources to TypeScript. TypeScript would compile on the first file because it's needed to resolve the dependency tree. I did have some debugging ability the last time around, but I don't think I ever committed it. Happy to add a flag back for it in the New Year or accepting PRs.

**Comment by whitecolor** [comment] 2016-12-25 15:47
@blakeembrey 

Nice, It would be great to have some flag that would increase verbosity of the output.

> It just gives the sources to TypeScript. TypeScript would compile on the first file because it's needed to resolve the dependency tree.

Does ts-node reuses results of the compilation between runs to speed up sequential runs? Or how does it work? I saw before that there was some `ts-node` folder witch some source cache, but not seeing it now.

**Comment by blakeembrey** [comment] 2016-12-25 16:31
There's no way to re-use the compilation between different executions. Within the same execution it doesn't need to re-compute everything, but in a new one it will. There is a cache that is used, but once you encounter a file that isn't in the cache TypeScript will need to kick in.

**Comment by Epskampie** [comment] 2018-11-02 11:13
For people find this through google like me, I fixed ts-node starting slow by adding

    "exclude": ["node_modules"]

to my tsconfig.json

**Comment by whitecolor** [comment] 2018-11-18 13:10
> For people find this through google like me, I fixed ts-node starting slow by adding
> 
> ```
> "exclude": ["node_modules"]
> ```
> to my tsconfig.json

Basically one should exclude `"**/node_modules/*"`

**Comment by victorschinaider** [comment] 2019-03-27 13:29
I'm having same problem. But, when i remove `experimentalDecorators": true` property it comes fast!
