### ISSUE TITLE
Can't install v4.0.1 because git dependencies

### ISSUE THREAD

**Issue by dereklin** [TypeStrong/ts-node#482] opened 2017-12-11 22:46 UTC
I am behind a proxy.

Looking at the package.json I see:

```
"@types/v8flags": "types/npm-v8flags#de224ae1cd5fd7dbb4e7158a6cc7a29e5315930d",
"@types/yn": "types/npm-yn#ca75f6c82940fae6a06fb41d2d37a6aa9b4ea8e9",
```

I am getting this error:

```
npm ERR! git clone --template=/u1/cibuild/.npm/_git-remotes/_templates --mirror git@github.com:types/npm-yn.git /u1/cibuild/.npm/_git-remotes/git-github-com-types-npm-yn-git-ca75f6c82940fae6a06fb41d2d37a6aa9b4ea8e9-7f8e5da1: Cloning into bare repository '/u1/cibuild/.npm/_git-remotes/git-github-com-types-npm-yn-git-ca75f6c82940fae6a06fb41d2d37a6aa9b4ea8e9-7f8e5da1'...
```
Is there any plan to use the types from npmjs.org?

**Comment by MaxCCC** [comment] 2017-12-12 06:42
Same issue but different error since 4.0.1 (version 3.3.0 is working)
we are facing proxy issues since we are using 4.0.1 because of 
```
    "@types/v8flags": "types/npm-v8flags#de224ae1cd5fd7dbb4e7158a6cc7a29e5315930d",
    "@types/yn": "types/npm-yn#ca75f6c82940fae6a06fb41d2d37a6aa9b4ea8e9",
```

error:
```
4274 silly fetchPackageMetaData error for @types/v8flags@github:types/npm-v8flags#de224ae1cd5fd7dbb4e7158a6cc7a29e5315930d Error while executing:
4274 silly fetchPackageMetaData /usr/bin/git ls-remote -h -t ssh://git@github.com/types/npm-v8flags.git
4274 silly fetchPackageMetaData
4274 silly fetchPackageMetaData ssh: Could not resolve hostname github.com: nodename nor servname provided, or not known
4274 silly fetchPackageMetaData fatal: Could not read from remote repository.
..

4275 silly fetchPackageMetaData error for @types/yn@github:types/npm-yn#ca75f6c82940fae6a06fb41d2d37a6aa9b4ea8e9 Error while executing:
4275 silly fetchPackageMetaData /usr/bin/git ls-remote -h -t ssh://git@github.com/types/npm-yn.git

```

**Comment by BernhardRode** [comment] 2017-12-12 08:14
Not working behind our coporate proxy, too.

**Comment by schmuli** [comment] 2017-12-13 13:32
Are these types required at runtime? I would assume that moving them into the `devDependencies` would resolve the Proxy issue, without requiring a different source.

**Comment by whitecolor** [comment] 2017-12-14 13:56
Those deps even not needed in prod version https://github.com/TypeStrong/ts-node/issues/475 they just should be moved to `devDependencies`

**Comment by paulkoegel-wessels** [comment] 2017-12-14 14:04
This PR should fix it: https://github.com/TypeStrong/ts-node/pull/484

**Comment by blakeembrey** [comment] 2017-12-14 17:03
Going to close as a duplicate of https://github.com/TypeStrong/ts-node/issues/475 for now.

**Closed by blakeembrey** 2017-12-14 17:03 UTC
