### ISSUE TITLE
ts-node not handling async/await properly with Bluebird

### ISSUE THREAD

**Issue by mcalhoun** [TypeStrong/ts-node#832] opened 2019-05-12 18:37 UTC
ts-node doesn't seem to be handling the resolution of promises correctly when using the Bluebird library globally.

The following code illustrates the issue. The code maked as from the 3rd party library is intended execute a series of promises in order (fooLoader, barLoader, bazLoader) where barLoader should not execute until fooLoader has resolved.

```typescript
const log = (message: string) => {
  // tslint:disable-next-line:no-console
  console.log(`${new Date().toISOString()}    ${message}`);
};

const sleep = (timeToSleepMs: number): Promise<void> => {
  return new Promise<void>(res => setTimeout(res, timeToSleepMs));
};

// this code is taken from a 3rd party library
function runInSequence<T, U>(
  collection: T[],
  callback: (item: T) => Promise<U>
): Promise<U[]> {
  const results: U[] = [];
  return collection
    .reduce((promise, item) => {
      return promise
        .then(() => {
          return callback(item);
        })
        .then(result => {
          results.push(result);
        });
    }, Promise.resolve())
    .then(() => {
      return results;
    });
}

const fooLoader = async () => {
  log("foo loader begin");
  await sleep(1000);
  log("foo loader complete");
};

const barLoader = async () => {
  log("bar loader begin");
  await sleep(2000);
  log("bar loader complete");
};

const bazLoader = async () => {
  log("baz loader begin");
  await sleep(3000);

  log("baz loader complete");
};

const runIt = (message: string) => {
  return (
    runInSequence([fooLoader, barLoader, bazLoader], loader => {
      const loaderResult = loader();
      return loaderResult instanceof Promise ? loaderResult : Promise.resolve();
    })
      .then(() => log(message))
      // tslint:disable-next-line: no-console
      .catch(err => console.error(err))
  );
};

const runWithoutBluebird = () => {
  log("running without Bluebird...");
  return runIt("without bluebird complete");
};

const runWithBluebird = () => {
  log("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
  log("running with Bluebird...");
  const Promise = require("bluebird");
  Promise.config({ longStackTraces: true });
  global.Promise = Promise;

  return runIt("with bluebird complete");
};

runWithoutBluebird()
  .then(() => runWithBluebird())
  // tslint:disable-next-line: no-console
  .catch(err => console.error(err));
```

output:

```
2019-05-10T15:55:25.452Z    running without Bluebird...
2019-05-10T15:55:25.456Z    foo loader begin
2019-05-10T15:55:26.461Z    foo loader complete
2019-05-10T15:55:26.462Z    bar loader begin
2019-05-10T15:55:28.463Z    bar loader complete
2019-05-10T15:55:28.464Z    baz loader begin
2019-05-10T15:55:31.467Z    baz loader complete
2019-05-10T15:55:31.467Z    without bluebird complete
2019-05-10T15:55:31.467Z    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2019-05-10T15:55:31.467Z    running with Bluebird...
2019-05-10T15:55:31.495Z    foo loader begin
2019-05-10T15:55:31.495Z    bar loader begin
2019-05-10T15:55:31.496Z    baz loader begin
2019-05-10T15:55:31.496Z    with bluebird complete
2019-05-10T15:55:32.498Z    foo loader complete
2019-05-10T15:55:33.497Z    bar loader complete
2019-05-10T15:55:34.499Z    baz loader complete
```

Running `tsc` and then running the result in node directly produces the correct ordering.

I also opened the following issue with Bluebird: https://github.com/petkaantonov/bluebird/issues/1595

**Comment by blakeembrey** [comment] 2019-05-12 21:13
@mcalhoun This seems interesting since nothing in this module changes node behavior. Can you provide the `tsconfig.json` and any runtime arguments you're using for your configuration?

**Comment by blakeembrey** [comment] 2019-05-12 21:15
<img width="682" alt="image" src="https://user-images.githubusercontent.com/1088987/57587827-66dfda00-74c0-11e9-8327-f3932d4cd37b.png">

**Comment by blakeembrey** [comment] 2019-05-12 21:16
Type-checking mode:

<img width="752" alt="image" src="https://user-images.githubusercontent.com/1088987/57587845-9393f180-74c0-11e9-9d1f-844c7b330ef1.png">

**Comment by blakeembrey** [comment] 2019-05-12 21:22
I also tried switching to node.js 8, TypeScript 2.9, and other combinations as reported in the Bluebird issue but nothing is reproducible.

**Comment by mcalhoun** [comment] 2019-05-12 22:38
Hi @blakeembrey I just did a few experiments and it seems that `"target": "es2015"` works while `"target": "es2017"` is when the problem starts happening.

**Comment by blakeembrey** [comment] 2019-05-12 23:39
@mcalhoun It doesn't appear to be `ts-node` related then. I just tested with `tsc` and it exhibits the same behavior:

<img width="752" alt="image" src="https://user-images.githubusercontent.com/1088987/57589147-8da80b80-74d4-11e9-9874-5ac165167469.png">

**Comment by blakeembrey** [comment] 2019-05-12 23:41
@mcalhoun The major difference between ES2015 and ES2017 is that async functions are native in ES2017, so they wouldn't be using Bluebird.

**Comment by blakeembrey** [comment] 2019-05-12 23:43
This would, of course, in your example, result in `instanceof Promise` always being false and `Promise.resolve()` being immediately run. Closing as a non-issue.

**Closed by blakeembrey** 2019-05-12 23:43 UTC
Labels: needs more info
