### ISSUE TITLE
TS_NODE_LOG_ERROR doesn't work

### ISSUE THREAD

**Issue by videni** [TypeStrong/ts-node#977] opened 2020-03-09 09:33 UTC
I set TS_NODE_LOG_ERROR  explicitely, but I still got following error, anything I did wrong?

```
{
  "watch": ["src", "public"],
  "exec": "cross-env TS_NODE_PROJECT=tsconfig.server.json TS_NODE_LOG_ERROR=true node -r ts-node/register src/server/index.ts",
  "ext": "js ts tsx"
}


```

```
[ error ] ERROR in /Users/john/www/acme-admin-ui1/src/components/Route/Link.tsx
2:8 'NextLink' is declared but its value is never read.
    1 | import React, { useContext } from 'react';
  > 2 | import NextLink, {
      |        ^
    3 |   LinkProps as NextLinkProps,
    4 | } from 'next/link';
    5 | import OrganizationContext from '../../layouts/OrganizationContext';
```

**Comment by cspotcode** [comment] 2020-07-29 02:46
The following is working for me, so it looks like it's not a bug on our end.

```
$ echo "const a: string = 123; console.log('Code is running');" > foo.ts
$ TS_NODE_LOG_ERROR=true ts-node ./foo.ts
```

Shows the following output, where the error is logged, and then the code runs.
```
TSError: ⨯ Unable to compile TypeScript:
foo.ts:1:7 - error TS2322: Type '123' is not assignable to type 'string'.

1 const a: string = 123; console.log('Code is running');
        ~

Code is running
```

Closing as it looks like everything is working as intended.

**Closed by cspotcode** 2020-07-29 02:46 UTC
Labels: question
