### ISSUE TITLE
Import of module does not work the first time around

### ISSUE THREAD

**Issue by arichiardi** [TypeStrong/ts-node#331] opened 2017-05-13 02:03 UTC
Hello again!

In my quest to using a REPL-centric approach to Typescript, I found another little obstacle: the import of a module does not work the first time. It does the second.

```
> import _ = require("./src/cqrs-event-store")
ReferenceError: exports is not defined
    at [eval].ts:2:23
    at ContextifyScript.Script.runInContext (vm.js:32:29)
    at ContextifyScript.Script.runInNewContext (vm.js:38:15)
    at _eval (/home/arichiardi/git/cqrs-event-store/node_modules/ts-node/src/_bin.ts:265:23)
    at REPLServer.replEval (/home/arichiardi/git/cqrs-event-store/node_modules/ts-node/src/_bin.ts:321:14)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.onLine (repl.js:536:10)
    at emitOne (events.js:96:13)
    at REPLServer.emit (events.js:191:7)
> import CqrsEs = require("./src/cqrs-event-store")
undefined
```

Note that this does not happen with `const`+`require`:

```
> const d = require("./src/cqrs-event-store")
Starting...
Segments: saladMan,order
Explain:undefined
undefined
```

Any hint?

I will try to investigate and check the code as well.

Thanks a lot!

**Comment by blakeembrey** [comment] 2017-05-13 06:13
Duplicate of https://github.com/TypeStrong/ts-node/issues/309.

**Closed by blakeembrey** 2017-05-13 06:13 UTC
