### ISSUE TITLE
Add top level await in repl

### ISSUE THREAD

**Issue by esprehn** [TypeStrong/ts-node#440] opened 2017-10-05 01:49 UTC
The repl doesn't run in an async function which means you can't do ex.

```js
var x = await db.getStuff();
```

and instead have to use `.then()` or wrap your line in an async IIFE which is ugly.

See also:
https://twitter.com/umaar/status/897408737694109697

**Comment by blakeembrey** [comment] 2017-10-05 03:35
Is it supported in the node.js REPL? Duplicate of https://github.com/TypeStrong/ts-node/issues/245. Please search before opening an issue.

**Closed by blakeembrey** 2017-10-05 03:35 UTC

**Comment by blakeembrey** [comment] 2017-10-05 03:38
Feel free to follow up in the linked issue when https://github.com/nodejs/node/issues/13209 gets closed. Ideally we don't have to do anything and it _just works_, but since there's transpiling that might not be true. I just don't want to deviate too much from what node.js supports.
