### ISSUE TITLE
Support passing `--trace-deprecation` flag to node

### ISSUE THREAD

**Issue by niieani** [TypeStrong/ts-node#1291] opened 2021-04-03 06:42 UTC
### Expected Behavior

Adding flag `--trace-deprecation` to ts-node, should work just as it does when running `node` natively.

### Actual Behavior

```

Error: Unknown or unexpected option: --trace-deprecation
    at arg (/home/runner/trace-deprecation-repro/node_modules/arg/index.js:88:19)
    at main (/home/runner/trace-deprecation-repro/node_modules/ts-node/dist/bin.js:15:67)
    at Object.<anonymous> (/home/runner/trace-deprecation-repro/node_modules/ts-node/dist/bin.js:238:5)
```

### Steps to reproduce the problem

Run `ts-node --transpile-only --trace-deprecation ./index.ts`

### Minimal reproduction

https://replit.com/join/bmbohiwr-niieani

Run `yarn test` to see the issue.

### Specifications

ts-node v9.1.1
node v12.22.0
compiler v4.2.3

* Operating system and version: any
* If Windows, are you using WSL or WSL2?: n/a

**Comment by cspotcode** [comment] 2021-04-03 20:29
Duplicate of #1182

**Closed by cspotcode** 2021-04-03 20:29 UTC
