### ISSUE TITLE
Unable to use REPL

### ISSUE THREAD

**Issue by pelotom** [TypeStrong/ts-node#453] opened 2017-10-26 17:05 UTC
TypeScript version: 2.5.3

```
» ts-node
> const x = 3
Thrown: ⨯ Unable to compile TypeScript
[eval].ts: Cannot find name 'exports'. (2304)
[eval].ts (0,11): Cannot find name 'module'. (2304)
```

**Comment by blakeembrey** [comment] 2017-10-26 17:45
Duplicate of https://github.com/TypeStrong/ts-node/issues/437.

**Closed by blakeembrey** 2017-10-26 17:45 UTC

**Comment by pelotom** [comment] 2017-10-26 18:05
Is there any timetable for a new release with this fix?

**Comment by blakeembrey** [comment] 2017-10-27 18:56
When all other major tasks are done, so no. Is it very difficult to install a type definition until then?

**Comment by pelotom** [comment] 2017-10-27 20:13
Nope, I just wasn’t aware of what the fix was.

**Comment by blakeembrey** [comment] 2017-10-27 20:52
No problem, I thought it was in the linked issue but it was in the duplicate of that duplicate. See https://github.com/TypeStrong/ts-node/issues/351#issuecomment-307178924.
