### ISSUE TITLE
Performance issue when using with nodemon on Windows after version 7.0.1

### ISSUE THREAD

**Issue by chengjia0807** [TypeStrong/ts-node#821] opened 2019-04-20 16:22 UTC
Need the help from you guys about my performance issue when running with nodemon on Windows Enviironment.

Here is the script:
node --inspect -r ts-node/register -r tsconfig-paths/register -r dotenv/config ./src/index.ts

7.0.1 is slow but versions after that are unbelievable slow

**Comment by blakeembrey** [comment] 2019-04-20 17:13
Probably a duplicate of https://github.com/TypeStrong/ts-node/issues/754.

**Closed by blakeembrey** 2019-04-20 17:13 UTC
