### ISSUE TITLE
ts-node hangs while scanning node_modules in cluster mode and yarn workspace

### ISSUE THREAD

**Issue by QuentinFarizon** [TypeStrong/ts-node#1369] opened 2021-06-07 06:25 UTC
I am using https://github.com/hunterloftis/throng to setup node clustering and ts-node-transpile-only to run my server.

I am using yarn workspaces, with simplified structure :
Back/
  backend/ (yarn workspace)
    bin/
      www.js
    services/
      (all services files, js and ts)

Here is an excerpt of my bin/www.js :
```
throng({
  worker: startServer,
  count: 1
})

async function startServer (id, disconnect) {
  console.log(`Started worker ${id}`)
  (starting server, ...)
}
```

### Expected Behavior

When using clustering, the process starts a first time in master mode, and a second time as worker (only 1 worker setup here). So I'm expecting the startup time to be twice as long as calling directly startServer, since it basically launches/trasnpiles two times.

### Actual Behavior

The start as "master" mode takes the same time as the direct mode 
The start as "worker" mode is very much longer than expected, up to 10x the time, so the overall start of my server is very very slow (up to several minutes against a few seconds when calling directly startServer)

I have logged the ouptut of `TS_NODE_DEBUG=1 start` :

Without throng/clustering :
```
ts-node 2021-06-07T06:00:21.681Z] module._compile /home/me/Code/MyCompany/myProject/Back/backend/bin/www.js
[ts-node 2021-06-07T06:00:21.855Z] module._compile /home/me/Code/MyCompany/myProject/Back/backend/hapi-server.ts
(... 128 additional lines, all the js/ts files of my project)
[ts-node 2021-06-07T06:00:28.911Z] module._compile /home/me/Code/MyCompany/myProject/Back/backend/services/api-key-service.ts
```
As you can see, no fileExists/directoryExists output, and no node_modules.

With throng/clustering :
```
(same 128 lines of output as above, then -> )
[ts-node 2021-06-07T05:59:33.953Z] module._compile /home/me/Code/MyCompany/myProject/Back/backend/bin/www.js
[ts-node 2021-06-07T05:59:33.988Z] directoryExists /home/me/Code/MyCompany/myProject/Back/backend/bin/node_modules 1
[ts-node 2021-06-07T05:59:33.990Z] directoryExists /home/me/Code/MyCompany/myProject/Back/backend/node_modules 2
[ts-node 2021-06-07T05:59:33.990Z] directoryExists /home/me/Code/MyCompany/myProject/Back/backend/node_modules/dotenv 3
[ts-node 2021-06-07T05:59:33.990Z] fileExists /home/me/Code/MyCompany/myProject/Back/backend/node_modules/dotenv.ts 1
[ts-node 2021-06-07T05:59:33.990Z] fileExists /home/me/Code/MyCompany/myProject/Back/backend/node_modules/dotenv.tsx 2
[ts-node 2021-06-07T05:59:33.991Z] fileExists /home/me/Code/MyCompany/myProject/Back/backend/node_modules/dotenv.d.ts 3
[ts-node 2021-06-07T05:59:33.991Z] directoryExists /home/me/Code/MyCompany/myProject/Back/backend/node_modules/@types 4
[ts-node 2021-06-07T05:59:33.991Z] directoryExists /home/me/Code/MyCompany/myProject/Back/backend/node_modules/@types/dotenv 5
[ts-node 2021-06-07T05:59:33.991Z] fileExists /home/me/Code/MyCompany/myProject/Back/backend/node_modules/@types/dotenv.d.ts 4
[ts-node 2021-06-07T05:59:33.992Z] directoryExists /home/me/Code/MyCompany/myProject/Back/node_modules 6
[ts-node 2021-06-07T05:59:33.992Z] directoryExists /home/me/Code/MyCompany/myProject/Back/node_modules/dotenv 7
[ts-node 2021-06-07T05:59:33.992Z] fileExists /home/me/Code/MyCompany/myProject/Back/node_modules/dotenv.ts 5
[ts-node 2021-06-07T05:59:33.993Z] fileExists /home/me/Code/MyCompany/myProject/Back/node_modules/dotenv.tsx 6
[ts-node 2021-06-07T05:59:33.993Z] fileExists /home/me/Code/MyCompany/myProject/Back/node_modules/dotenv.d.ts 7
[ts-node 2021-06-07T05:59:33.993Z] directoryExists /home/me/Code/MyCompany/myProject/Back/node_modules/@types 8
[ts-node 2021-06-07T05:59:33.994Z] directoryExists /home/me/Code/MyCompany/myProject/node_modules 9
[ts-node 2021-06-07T05:59:33.994Z] directoryExists /home/me/Code/MyCompany/myProject/node_modules/dotenv 10
[ts-node 2021-06-07T05:59:33.994Z] fileExists /home/me/Code/MyCompany/myProject/node_modules/dotenv/package.json 8
[ts-node 2021-06-07T05:59:33.995Z] readFile /home/me/Code/MyCompany/myProject/node_modules/dotenv/package.json 1
[ts-node 2021-06-07T05:59:33.999Z] fileExists /home/me/Code/MyCompany/myProject/node_modules/dotenv.ts 9
[ts-node 2021-06-07T05:59:33.999Z] fileExists /home/me/Code/MyCompany/myProject/node_modules/dotenv.tsx 10
(4000 additional lines)
```
It seems it cannot correctly resolve the path to files in node_modules, and searches them recursively.

### Minimal reproduction

I've attempted a reproduction repo here : https://github.com/TypeStrong/ts-node-repros/pull/11

### Specifications

ts-node v10.0.0
node v12.20.1
compiler v4.3.2
typescript 4.0.5
* tsconfig.json, if you're using one:
```
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "lib": ["es2015"],
    "allowJs": true,
    "outDir": "build",
    "rootDir": "",
    "strict": true,
    "noImplicitAny": true,
    "esModuleInterop": true,
    "resolveJsonModule": true
  },
  "exclude": [
    "node_modules",
    "build"
  ]
}
```

* Operating system and version:
Ubuntu 20.04

**Comment by cspotcode** [comment] 2021-06-07 12:26
Try putting `transpileOnly` in your `tsconfig.json` instead of triggering it via `ts-node-transpile-only`.

https://typestrong.org/ts-node/docs/configuration

**Comment by cspotcode** [comment] 2021-06-14 03:21
I'm closing this under the assumption that this is not a bug and the problem has been solved.  Issues can always be reopened if we can demonstrate that this is a bug in ts-node.

**Closed by cspotcode** 2021-06-14 03:21 UTC
