### ISSUE TITLE
ts-node cannot import pure typescript npm module inside node_modules directory

### ISSUE THREAD

**Issue by zixia** [TypeStrong/ts-node#158] opened 2016-07-26 04:44 UTC
I had wroten a pure typescript npm module(without any .js file), and want to use it in my server project which use ts-node(without any compile work like tsc) to run directly. because my case is a server environment, so startup time is not a problem.

* my npm module is here: https://github.com/zixia/wechaty-io
* my server typescript file is here: [link](https://github.com/zixia/wechaty.io/blob/9b19220fd55ec1976ae2731ffb6e5b59b3f45869/bin/index.ts#L17)

the problem is: ts-node cannot use `import` to load pure typescript inside `node_modules` directory, I had to do a little hack(move it out, use soft link to link it back).

## Which cannot run:
```shell
$ npm install
$ ts-node bin/index.ts

/Users/zixia/git/wechaty.io/node_modules/wechaty-io/index.ts:1
(function (exports, require, module, __filename, __dirname) { export * from './src/io-server'
                                                              ^^^^^^
SyntaxError: Unexpected token export
```

## Which could run

**my hack is: move `wechaty-io` module directory out of node_modules, then use soft link to link it back**

```shell
$ npm install
$ mv node_modules/wechaty-io .
$ ln -s ../wechaty-io node_modules/
$ ts-node bin/index.ts

info io-server Listening on 8080
info io-server init succeed
```

It seems the `import` in ts-node will not work when the pure typescript module is in `node_modules` directory. But, after we changed the physics directory out of `node_modules` directory, `ts-node` will make `import` work properly.

Is there any better solution to do this? Thanks.

**Comment by blakeembrey** [comment] 2016-07-26 10:48
Isn't this a duplicate of https://github.com/TypeStrong/ts-node/issues/155?

**Closed by blakeembrey** 2016-07-26 10:48 UTC

**Comment by glebmachine** [comment] 2017-06-19 14:13
`Isn't this a duplicate of #155? We don't enable TypeScript modules in node_modules, node modules should be JavaScript.`

That's look weird, because we have got a lot libraries which doesn't compiled properly..

Is there any option to replace import folder for ```node_modules```? Or disable ```node_modules``` ignoring?

**Comment by blakeembrey** [comment] 2017-06-21 15:45
@glebmachine Sure. Check the README or the linked issue.
