### ISSUE TITLE
ts-node >= 7.x makes mocha unit tests hanging

### ISSUE THREAD

**Issue by Q-Man** [TypeStrong/ts-node#805] opened 2019-03-29 01:45 UTC
I'm using Mocha Version 6.0.2 in my project with ts-node for writing unit tests in TypeScript.

I'm starting mocha from the command line via:

`mocha --require ts-node/register --ui bdd ./src/**/*.test.ts ./src/**/*.test.tsx`

With ts-node 6.x I don't have any problems, but all ts-node versions after (7.x and 8.x) make mocha hanging without any output.

Is it possible to get a debug output from Mocha or ts-node to see what's going on?

**Comment by hisuwh** [comment] 2019-04-02 09:47
I'm seeing the same thing with alsatian tests with ts-node 8.x but not with 7.0.1

**Comment by jbouhier** [comment] 2019-04-24 00:37
Duplicate of https://github.com/TypeStrong/ts-node/issues/754

**Comment by cspotcode** [comment] 2021-06-14 03:39
Closing because each aspect of this ticket is either solved or the necessary work is tracked by other issues:

- Performance recommendations here: https://typestrong.org/ts-node/docs/performance
- #817, #1245, #1161 track research and work to use incremental builds
- `TS_NODE_DEBUG=true` logs verbose diagnostic information to see what ts-node and the compiler are doing
  - Docs: https://typestrong.org/ts-node/docs/options#diagnostics

**Closed by cspotcode** 2021-06-14 03:39 UTC
