### ISSUE TITLE
-gc flag does not work

### ISSUE THREAD

**Issue by ejoebstl** [TypeStrong/ts-node#1073] opened 2020-07-09 15:57 UTC
### Expected Behavior

`-gc` flag should be accepted by `ts_node`, as discussed [here](https://github.com/TypeStrong/ts-node/issues/418).

### Actual Behavior

Fails to parse param.

```
ts-node -gc script.ts
/usr/local/lib/node_modules/ts-node/node_modules/arg/index.js:92
						throw err;
						^

Error: Unknown or unexpected option: -g
    at arg (/usr/local/lib/node_modules/ts-node/node_modules/arg/index.js:90:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ts-node/dist/bin.js:13:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

### Minimal reproduction

```
touch script.ts
ts-node -gc script.ts
```

### Specifications

```
ts-node v8.3.0
node v10.18.1
compiler v3.9.5
```

Operating system and version: Linux archlinux 5.7.2-arch1-1

**Comment by cspotcode** [comment] 2020-07-09 16:26
This is working as intended.  We no longer attempt to spawn a child node process and pass it node flags.

If you need to pass extra flags to the node process, you can invoke node directly, telling it to load `ts-node/register`.

See also:
https://github.com/TypeStrong/ts-node#programmatic

Closing for now, because I think this adequately explains why it's working as intended.  We can reopen as needed.

**Closed by cspotcode** 2020-07-09 16:26 UTC

**Comment by ejoebstl** [comment] 2020-07-09 16:36
Thank you for the clarification. I was not aware of the changes.
