### ISSUE TITLE
REPL: Ignore Undefined For Commands Returning Nothing

### ISSUE THREAD

**Issue by lordmilko** [TypeStrong/ts-node#460] opened 2017-11-14 10:45 UTC
When ts-node is executing in REPL mode and executes a command that returns nothing (such as `console.log("test")`, in addition to the output "test" it also returns `undefined`. This appears to be the default behavior of the Node.js REPL module, and can be [controlled](https://nodejs.org/api/repl.html#repl_repl_start_options) by specifying `ignoreUndefined: true` in the options passed to [start](https://github.com/TypeStrong/ts-node/blob/3718bf135ac816328790cae3b0319b0352c1fdff/src/_bin.ts#L268).

I believe it would be a good idea for ts-node to support this functionality, either hard coding this behavior (if a command returns nothing it seems clear it returns nothing?) or by defining an option users can configure in ts-node as to whether or not they wish to ignore undefined.

**Comment by blakeembrey** [comment] 2017-11-15 05:38
The REPL works the same as node.js. Is there an option in node.js to do this?

**Comment by lordmilko** [comment] 2017-11-15 05:43
It appears that specifying the `ignoreUndefined: true` to the `start` function in node controls this

```javascript
const repl = start({
  ignoreUndefined: true
})
```
So potentially the code in ts-node's `startRepl` function could be changed to the following

```javascript
function startRepl () {
  const repl = start({
    prompt: '> ',
    input: process.stdin,
    output: process.stdout,
    eval: replEval,
    useGlobal: false,
    ignoreUndefined: true
  })

...
```

**Comment by blakeembrey** [comment] 2017-11-15 05:46
I didn't ask how the API works, I know that. Is there a flag for node.js's REPL to do the same functionality. If not, I won't be adding it here.

**Comment by lordmilko** [comment] 2017-11-15 05:49
I haven't been able to identify any separate flags separate from the arguments passed to the `start` function. As such, beyond ts-node controlling a variable specifying whether `ignoreUndefined` should be true or false it doesn't appear there would be any other way to implement this functionality

**Comment by blakeembrey** [comment] 2017-11-15 07:06
It mostly comes down to the fact I’d prefer not to deviate far from strict node.js with a TypeScript transpiler semantics. Everything added means slightly more deviation. I’d search or submit the proposal to node.ja first and then we could follow suit.

**Closed** 2017-11-18 19:13 UTC
Labels: needs more info

**Comment by benelan** [comment] 2023-03-29 00:59
Sorry for digging up this old issue, but I'm a bit confused by the outcome. The [`ignoreUndefined` flag does exist in Node's API](https://nodejs.org/api/repl.html#repl_repl_start_options). I confirmed on the command line (Node `v16.19`):

```sh
node -e 'require("repl").start({ignoreUndefined: true})'
```

Can someone elaborate on what functionality needs to be added to Node before `ts-node` supports the `ignoreUndefined` flag? I'd be happy to submit a proposal once clarified, thanks!

**Comment by lordmilko** [comment] 2023-03-30 06:49
If I recall correctly, my interpretation from when I asked this issue was that the aim of this project is essentially to replicate the functionality of the `node` executable, but for TypeScript. As such, the command line parameters that `ts-node` has are limited by the *command line parameters* `node` has. Random functionality that you can achieve using node's internal API, I believe, would be out of the scope of this project (at least, that was my interpretation in 2017), which is fair enough.

I believe as a workaround I hacked the source code in the vscode extension I was using; not ideal, but it got me going.

**Comment by benelan** [comment] 2023-03-31 04:08
Thanks for the reply. Yeah I wasn't clear on if they were asking if Node has a CLI flag or an API flag, so I thought it might have been a misunderstanding. Maintaining open source is hard and some things slip through the cracks.

Unforunately, I doubt a proposal to to add an `--ignore-undefined` CLI flag to Node would make it far, since they'd point to the existing example in my previous comment.

My use case sounds similar to yours - I'm trying to use a [Vim plugin that turns the editor into a REPL](https://github.com/metakirby5/codi.vim). But when I wire it up with `ts-node` it just says `undefined` because that's the last thing logged to the console.
