### ISSUE TITLE
v8.5.3 hangs indefinitely

### ISSUE THREAD

**Issue by Dids** [TypeStrong/ts-node#918] opened 2019-11-28 08:04 UTC
The latest version (v8.5.3) hangs indefinitely when running directly, or when running through `--register ts-node/register`.

Node.js version is v10.17.0, and downgrading ts-node to v8.5.2 (or older) works fine.

**Comment by Arcath** [comment] 2019-11-28 09:45
I'm getting the same,node v10.15.3, Typescript 3.7.2. Downgrading to 8.5.2 fixed the problem for me

**Comment by proutek** [comment] 2019-11-28 10:44
Same here. Went back to 8.5.2

**Comment by Mann-o** [comment] 2019-11-28 13:38
As per https://github.com/nuxt/typescript/issues/214

Same, or similar, issue with Nuxt.js builds when using their Typescript module. Builds either fail to complete, take an extremely long time, or error with out-of-memory errors.

Fixing `ts-node` version to `8.5.2` resolves the issue.

**Comment by c100k** [comment] 2019-11-28 15:11
I tried to dig a little bit in the issue. There might be an issue with the `bin` because even though it shows that we are on `8.5.3` we don't see the new `emit` flag in the help section. Hope it can help in some way.

```shell
➜  git:(master) ✗ ./node_modules/.bin/ts-node --version
v8.5.3
➜  git:(master) ✗ ./node_modules/.bin/ts-node --help

  Usage: ts-node [options] [ -e script | script.ts ] [arguments]

  Options:

    -e, --eval [code]              Evaluate code
    -p, --print                    Print result of `--eval`
    -r, --require [path]           Require a node module before execution
    -i, --interactive              Opens the REPL even if stdin does not appear to be a terminal

    -h, --help                     Print CLI usage
    -v, --version                  Print module version information
    -s, --script-mode              Use cwd from <script.ts> instead of current directory

    -T, --transpile-only           Use TypeScript's faster `transpileModule`
    -I, --ignore [pattern]         Override the path patterns to skip compilation
    -P, --project [path]           Path to TypeScript JSON project file
    -C, --compiler [name]          Specify a custom TypeScript compiler
    -D, --ignore-diagnostics [code] Ignore TypeScript warnings by diagnostic code
    -O, --compiler-options [opts]   JSON object to merge with compiler options

    --dir                          Specify working directory for config resolution
    --scope                        Scope compiler to files within `cwd` only
    --files                        Load files from `tsconfig.json` on startup
    --pretty                       Use pretty diagnostic formatter (usually enabled by default)
    --skip-project                 Skip reading `tsconfig.json`
    --skip-ignore                  Skip `--ignore` checks
    --prefer-ts-exts               Prefer importing TypeScript files over JavaScript files
    --log-error                    Logs TypeScript errors to stderr instead of throwing exceptions
```

**Comment by blakeembrey** [comment] 2019-11-28 17:01
It might be fixed with https://github.com/TypeStrong/ts-node/releases/tag/v8.5.4, but unsure since there's no reproduction in this thread.

**Comment by proutek** [comment] 2019-11-28 17:59
I can confirm 8.5.4 works again. Thank You.

**Closed** 2019-11-29 05:32 UTC
