### ISSUE TITLE
Registering two ts-node instances causing double-compilation, confusing errors

### ISSUE THREAD

**Issue by d3lm** [TypeStrong/ts-node#1690] opened 2022-03-14 11:51 UTC
### Expected Behavior

Consider the following entry point (`main.ts`):

```js
require('ts-node/register');
require('./index.ts');
```

When running `ts-node` on this entry point, I expect it to work just fine.

### Actual Behavior

It crashes with an error:

```
index.ts:6:15 - error TS2695: Left side of comma operator is unused and has no side effects.

6     foo_bar: (0, utils_1.foo)(),
```

### Steps to reproduce the problem

Here's a reproduction: https://stackblitz.com/edit/node-pjxvzt?file=main.ts

Open the link (in Chrome), and run `ts-node main.ts` from the terminal. Alternatively, you can download the project and run it locally. Gives the exact same error.

The problem seems to be that it overrides `Module._compile` with a custom function and it tries to compile an already compiled version of a module.

![CleanShot 2022-03-14 at 12 50 31@2x](https://user-images.githubusercontent.com/12571019/158166380-97d85d12-19eb-4889-ac6b-6b256d412260.png)

At some point `_compile` will refer to the custom function and no longer to the original function.

It does work if you run it via `node -r ts-node/register main.ts`. However, at work, I was running into the exact same issue using `-r ts-node/register` but it's quite a complex setup and I wasn't able to minimally reproduce it yet. A bit strange.

### Specifications

```
ts-node v10.7.0
node v14.19.0
compiler v4.6.2
```

**Comment by cspotcode** [comment] 2022-03-14 18:16
It sounds like you've installed two copies of ts-node.

Running the `ts-node` CLI will install ts-node's compiler hooks.  Calling `require('ts-node/register');` will also install ts-node's compiler hooks.  This means ts-node will attempt to compile your TS, then compile that compiled output *again*.

The solution is to avoid installing ts-node's hooks twice.

**Comment by d3lm** [comment] 2022-03-15 07:59
This is not a solution I have control over, because some loaders, e.g. [this](https://github.com/EndemolShineGroup/cosmiconfig-typescript-loader/blob/develop/src/index.ts#L8) one will install the compiler hooks and if I run some `.ts` file myself which uses that loader programatically I need to use `ts-node`.

**Comment by cspotcode** [comment] 2022-03-15 15:59
Ok, this sounds like a duplicate of #409.  I've renamed this issue to more accurately describe the problem.  It looks like some meaningful conversation has already happened in #409, so let's move the discussion there.  I bet we can devise a good solution for these kinds of situations.

**Closed as completed by cspotcode** 2022-03-15 15:59 UTC
