### ISSUE TITLE
ts-node doesn't do anything 4.0.0 and 4.0.1 on Windows

### ISSUE THREAD

**Issue by dammitcoetzee** [TypeStrong/ts-node#481] opened 2017-12-11 19:03 UTC
I'm running windows 10. It's a brand new and updated windows install. 

When I npm install -g ts-node and then try to run tsnode nothing happens. None of the commands do anything. 

I tried 4.0.0 and the same happens.

I installed 3.3.0 and now the REPL shows up and all commands run as normal.

Thanks,
Gerrit

**Comment by ibqn** [comment] 2017-12-12 10:31
I have the same issue, good to know that I am not alone!
There is no output at all, I do not know even how to debug in this case.....

**Comment by Xceno** [comment] 2017-12-12 11:34
Tried to run it through `PM2`. Same result here

**Comment by unlight** [comment] 2017-12-12 17:53
+1. Same result when using `npx`

**Comment by Hugheym** [comment] 2017-12-13 18:24
Same here. After debugging, I see that the child process _bin.js is exiting with exit code 7 "[Internal Exception Handler Run-Time Failure](https://github.com/nodejs/node-v0.x-archive/blob/master/doc/api/process.markdown#exit-codes)"

**Comment by Hugheym** [comment] 2017-12-14 01:25
After some work debugging the child process, I found that the issue for me was that it was not resolving typescript because it was not installed globally. Maybe the issue is that no error message is printing when node cannot resolve typescript.

**Comment by lednhatkhanh** [comment] 2017-12-14 13:32
Any updates on this?

**Comment by blakeembrey** [comment] 2017-12-14 17:08
Closing in favour of https://github.com/TypeStrong/ts-node/issues/480, if that's ok. The current fix should be to use `node -r ts-node/register` instead of `ts-node` directly.

**Closed by blakeembrey** 2017-12-14 17:08 UTC
