### ISSUE TITLE
Cannot install ts-node 4 on Windows with Cygwin

### ISSUE THREAD

**Issue by wartab** [TypeStrong/ts-node#486] opened 2017-12-14 13:49 UTC
Attempting to install ts-node 4 on Windows with Cygwin generates an invalid path when using git.

```
5285 verbose stack Error: Command failed: C:\cygwin64\bin\git.EXE clone --depth=1 -q -b master git://github.com/types/npm-yn.git C:\Users\Vincent Lycoops\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-f2f1b38b --config core.longpaths=true
5285 verbose stack fatal: Invalid path '/cygdrive/c/Users/Vincent Lycoops/AppData/Roaming/npm-cache/_cacache/tmp/git-clone-f2f1b38b/C:\Users\Vincent Lycoops\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-f2f1b38b': No such file or directory
5285 verbose stack
5285 verbose stack     at ChildProcess.exithandler (child_process.js:275:12)
5285 verbose stack     at emitTwo (events.js:126:13)
5285 verbose stack     at ChildProcess.emit (events.js:214:7)
5285 verbose stack     at maybeClose (internal/child_process.js:925:16)
5285 verbose stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
5285 verbose stack     at emitOne (events.js:116:13)
5285 verbose stack     at Socket.emit (events.js:211:7)
5285 verbose stack     at Pipe._handle.close [as _onclose] (net.js:554:12)
```

**Comment by wartab** [comment] 2017-12-14 13:50
Temporary workaround is to use the non Cygwin version of git, by the way.

**Comment by blakeembrey** [comment] 2017-12-14 17:02
Going to close as a duplicate of https://github.com/TypeStrong/ts-node/issues/475, since the fix should be the same.

**Closed by blakeembrey** 2017-12-14 17:02 UTC

**Comment by wartab** [comment] 2017-12-15 12:43
Thank you, that fix has worked!
