### ISSUE TITLE
--require can not be configured in tsconfig.json 

### ISSUE THREAD

**Issue by jjangga0214** [TypeStrong/ts-node#1334] opened 2021-05-23 12:08 UTC
`ts-node` does not read `--require` from tsconfig.json

### Steps to reproduce the problem

```jsonc
{
  // other configurations are omitted for brevity. 
  "ts-node": {
    "require": [ "tsconfig-paths/register" ] // <= This does not work. 
  }
}
```

### Specifications

* ts-node version: 9.1.1
* node version: 16
* TypeScript version: 4.2.4

* Operating system and version: ubuntu 20.04

**Comment by cspotcode** [comment] 2021-05-23 16:55
This repro is working on the versions you specified.
https://github.com/TypeStrong/ts-node-repros/tree/tsconfig-require-config
https://github.com/TypeStrong/ts-node-repros/runs/2650695046?check_suite_focus=true

Is there something else that needs to be added to this issue to reproduce it?

**Comment by cspotcode** [comment] 2021-06-06 00:30
Closing under the assumption the reporter has figured out how to make this work and it is not a bug.  If I am wrong, we can re-open.

**Closed by cspotcode** 2021-06-06 00:30 UTC
Labels: needs more info
