### ISSUE TITLE
ts-node/esm - cannot use path from tsconfig.json

### ISSUE THREAD

**Issue by testgitdl** [TypeStrong/ts-node#1728] opened 2022-04-21 18:07 UTC
### Expected Behavior
I have a playwright + cucumber project where I'm importing PO's and I want to use tsconfig-paths defined in my tsconfig.json but these do not seem to work.
Here is the project: https://github.com/testgitdl/cucumber-playwright-ang13

### Actual Behavior
In login.page.ts: works -> import { page } from '../support/hooks.js';
                          doesn't work -> import { page } from '@support';

### Steps to reproduce the problem
Here is the project: https://github.com/testgitdl/cucumber-playwright-ang13

My login.page.ts looks like this:
import { expect } from "chai";
// import { page } from '@support';
import { page } from '../support/hooks.js';

export class LoginPage {

  async navigate() {
    await page.goto('https://playwright.dev/');
  }

  async test() {
    console.log('okkkk');
  }
}

My tsconfig.json looks like this:
{
  "compileOnSave": false,
  "compilerOptions": {
    "downlevelIteration": true,
    "importHelpers": true,
    "module": "es2020",
    "outDir": "./dist/out-tsc",
    "baseUrl": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noImplicitAny": false,
    "target": "es2020",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2020",
      "dom"
    ],
    "paths": {
      "@support": [
        "./e2e/support/*"
      ],
      "@support/*": [
        "./e2e/support/*"
      ]
    }
  }
}

To run the tests: npm run test

### Specifications

* ts-node version:
* node version:
* TypeScript version:
* tsconfig.json, if you're using one:
```
{}
```
* Operating system and version:
* If Windows, are you using WSL or WSL2?:

**Comment by cspotcode** [comment] 2022-04-21 19:10
Looks like a duplicate of #1375?

See also: https://github.com/TypeStrong/ts-node/issues/1596#issuecomment-1013770399

**Closed by cspotcode** 2022-04-21 19:10 UTC

**Comment by testgitdl** [comment] 2022-04-22 06:22
Indeed, it is a duplicate
