### ISSUE TITLE
How to use with WebWorkers

### ISSUE THREAD

**Issue by kutomer** [TypeStrong/ts-node#711] opened 2018-10-23 17:58 UTC
Hello,

Is there any way to use ts-node with WebWorkers __but__ without using webpack?

When I do:

`const worker = new Worker('path-to/workerFile.ts', { // ... });`

I get:

```
TypeError [ERR_WORKER_UNSUPPORTED_EXTENSION]: The worker script extension must be ".js" or ".mjs". Received ".ts"
    at new Worker (internal/worker.js:272:15)
    // ....
```

Any ideas?

Tomer

**Comment by blakeembrey** [comment] 2018-10-24 15:28
This is a node.js error, it doesn’t look like it based on the error message.

**Comment by kutomer** [comment] 2018-10-24 18:06
@blakeembrey thanks for your quick reply :)
Not sure I fully understand what you mean by "it doesn’t look like it based on the error message".
I know it's a node.js error, but still, I think it's a ts-node related topic, cause correct me if I'm wrong but after stating a ts-node app, it compiles the ts and executing the js.
But with WebWorkers, it gets a bit more complicated cause web worker require a file path, so if I want to use a `.ts` as the worker input that's the exception node throws.
So, I can write all the worker code in js or compile ts file on my own.
Maybe it will be a good idea to somehow detect the worker's path and switch it with the compiled path?

**Comment by blakeembrey** [comment] 2018-10-25 15:49
There’s a couple of issues with that:

1. This module doesn’t produce any real files (it’s all in memory)
2. It wouldn’t have compiled any file it hasn’t seen via an import yet, so it won’t know about the web worker file 

What we could do is expose the internal compiler/config at runtime and you could generate/write the file yourself. Perhaps with a little `TsWorker` wrapper? Would this be a good starting point?

**Comment by vedmant** [comment] 2019-07-05 19:16
I have the same issue, is there any good solution for this?

**Comment by cspotcode** [comment] 2020-08-25 04:48
The problem is the worker has a separate require() cache and `require.extensions`.  `ts-node` is not installed in the worker, and node does not expose an API that would let us auto-install ourselves into all workers.  Also, I'm not sure that would be a good idea.  Third-party libraries using `worker_threads` shouldn't pay a performance hit just so we can install duplicate copies of ourselves into every worker.

Fortunately, I think the solution is simple: when you want to spawn a worker with `ts-node`, use our `ts-node/register` endpoint to install us.

```
new Worker(`
  require('ts-node/register');
  require(require('worker_threads').workerData.runThisFileInTheWorker);
`, {
  eval: true,
  workerData: {
    runThisFileInTheWorker: '/path/to/worker-script.ts'
  }
});
```

**Comment by jprochazk** [comment] 2021-02-24 12:17
To add to the above, if you want non-relative paths to be resolved according to your tsconfig `baseUrl` and `paths`, you should install the [`tsconfig-paths`](https://www.npmjs.com/package/tsconfig-paths) module, and spawn the worker like so:

```ts
new Worker(`
  require('tsconfig-paths/register');
  require('ts-node/register');
  require(require('worker_threads').workerData.runThisFileInTheWorker);
`, {
  eval: true,
  workerData: {
    runThisFileInTheWorker: '/path/to/worker-script.ts'
  }
});
```

**Comment by JounQin** [comment] 2021-04-27 09:11
@cspotcode You saved my whole day!

**Comment by cspotcode** [comment] 2021-06-14 04:19
Closing as solved and documented:

https://typestrong.org/ts-node/docs/recipes/other mentions a generic way to enable `ts-node` in web workers.
https://github.com/TypeStrong/ts-node/issues/711#issuecomment-679621830 describes a more worker-specific approach

**Closed by cspotcode** 2021-06-14 04:19 UTC
Labels: enhancement, external

**Comment by JounQin** [comment] 2021-08-29 00:35
@cspotcode 

This will stop working when using native esm due to `.ts` extension.

```
new Worker(`
  require('tsconfig-paths/register');
  require('ts-node/register');
  import(require('worker_threads').workerData.runThisFileInTheWorker);
`, {
  eval: true,
  workerData: {
    runThisFileInTheWorker: '/path/to/worker-script.ts'
  }
});
```

Any possible workaround?

**Comment by scottccoates** [comment] 2022-02-15 07:13
For anyone still experiencing this, make sure you are on node v16.9 or above. See https://nodejs.org/api/errors.html#err_worker_unsupported_extension.

**Comment by manjari09** [comment] 2022-09-13 10:45
> new Worker(`
>   require('ts-node/register');
>   require(require('worker_threads').workerData.runThisFileInTheWorker);
> `, {
>   eval: true,
>   workerData: {
>     runThisFileInTheWorker: '/path/to/worker-script.ts'
>   }
> });

@cspotcode - I am doing exactly this in my code, but I still get below error. Any idea on this?

```
Error: Cannot find module './worker.ts'
Require stack:
- /<path to project>/[worker eval]
```

**Comment by wjagodfrey** [comment] 2022-11-26 22:10
The eval solution doesn't work with `.ts` files, if you are running tsconfig `"esm": true` and package.json `"type": "module"`.

I've also attempted setting
```
NODE_OPTIONS="--loader ts-node/esm"
TS_NODE_PROJECT="[absolute tsconfig path]"
```
With not luck

Is the worker loader really affected by loader hooks? It doesn't seem that it is.

At this point it may just be easier to compile the worker target before running `ts-node`.
