### ISSUE TITLE
worker processes in cluster mode does not use the specified project file

### ISSUE THREAD

**Issue by gfx** [TypeStrong/ts-node#367] opened 2017-06-21 13:56 UTC
demo: https://github.com/gfx/ts-node-with-cluster-bugs

I found that the worker processes spawned by `cluster` module are not compiled in our environments, where `tsconfig.json` specifies `"module": "es2015"` and `tsconfig.universal.json` specifies `"modules": "commonjs"`.

This is because the worker processes always refer `tsconfig.json` which compiles *.ts for webpack, not nodejs.

FYI: I have avoided this issue by creating `tsconfig.json` for nodejs and `tsconfig.webpack.json` for webpack.

**Comment by blakeembrey** [comment] 2017-09-12 17:27
Any thoughts on how you think we could solve this correctly? It'll always be an issue when forking another process to do work, so I'd love to hear your thoughts.

**Comment by xipheCom** [comment] 2018-01-05 00:21
```typescript
//some imports
const PATH_TO_NODE = __dirname + '/../node_modules/.bin/ts-node'; 
cluster.setupMaster({
    execArgv: [PATH_TO_NODE, '-r', 'tsconfig-paths/register'], //install tsconfig-paths before
} as cluster.ClusterSettings)
//rest of cluster.ts
```
works except port sharing, what is the main reason for a cluster...... So it is useless. There is a EADDRINUSE error with this. Nevertheless the cluster starts and works well.

I have no idea why. execArgv works, because it should give some arguments to forked node. Seems it starts  ts-node.  Looks like without that the forks are not compiled, so node is complaining about invalid "import" syntax? Just walking into dark....

**Comment by xipheCom** [comment] 2018-01-05 02:35
ok, after doing some research if found out that you have to do this:
```typescript
//some import
cluster.setupMaster({
    execArgv: ['-r', 'tsconfig-paths/register', '-r', 'ts-node/register']
} as cluster.ClusterSettings)
cluster.fork()
```
I will create a gist tomorrow.

**Comment by xipheCom** [comment] 2018-01-14 10:48
To close this issue I suggest to document the need of the parameters in execArgv for clusters . It works like a charme in one of my production apps

**Comment by cspotcode** [comment] 2022-03-07 05:39
I tested this reproduction on the latest ts-node.  We set `execArgv` correctly thanks to #1657, so this is fixed and works out-of-the-box.  Users do not need to set `execArgv` manually.

**Closed by cspotcode** 2022-03-07 05:39 UTC
Labels: research
