### ISSUE TITLE
TS2322 when using async/await

### ISSUE THREAD

**Issue by kalutheo** [TypeStrong/ts-node#774] opened 2019-02-01 13:48 UTC
## What is the current behaviour

When i am using an async function in my codebase like that : 
```
export const testing = async () => {
  return "Hello world";
};
```
Then in my code : 
```
testing();
```

After running : 

`ts-node index.ts`

i get the following error : 

`error TS2322: Type '0' is not assignable to type '{ label: number; sent: () => any; trys: any[]; ops: any[]; }'.`

## Informations

```json
// tsconfig.json 

{
  "compilerOptions": {
    /* Basic Options */
    "target": "es5",                  
    "module": "commonjs",
    "lib": [
      "es2015",
      "es2017",
      "scripthost",
      "es2015.promise",
      "es2015.generator",
      "es2015.iterable",
      "dom",
      "dom.iterable"
    ],
    "resolveJsonModule": true,
    "plugins": [
      {
        "name": "typescript-tslint-plugin"
      }
    ],

    /* Strict Type-Checking Options */
    "strict": false,                          
    "noImplicitAny": false,                 
     "noImplicitThis": false,                
    "typeRoots": ["./typings"],                       
    "types": ["node", "jest"],                          
    "esModuleInterop": true                 
  }
}
```

```json
// package.json 
{
  "devDependencies": {
    "@types/bunyan": "^1.8.5",
    "@types/jest": "^23.3.13",
    "@types/node": "^10.12.19",
    "@types/ramda": "^0.25.47",
    "ts-jest": "^23.10.5",
    "ts-node": "^8.0.2",
    "tslint": "^5.12.1",
    "tslint-config-prettier": "^1.17.0",
    "tslint-config-standard": "^8.0.1",
    "typescript": "^3.3.1"
  }
}
```

``` 
// index.ts
require("ts-node").register();
require("./src/index").start(process.env);

```

## What is the expected behaviour

When i run `ts-node index.ts`  and i am using async await notation in my codebase, the compiler should not throw errors.

**Comment by blakeembrey** [comment] 2019-02-01 17:33
It seems unlikely those two lines have caused this error. It appears there's more to this project that is causing that error. That sort of error looks like tuple assignment issues. I also can't see where that type comes from in your example or anything around `0`. Can you share more for someone to be able to help you? Finally, does this compile with `tsc`?

**Comment by rodsfreitas** [comment] 2019-06-03 15:48
We're having the same error here in Windows 10. It doesn't occur in macs or linux. So strange. Any update on this? The error is happening with async. When we removed the async functions, it ran.

**Comment by blakeembrey** [comment] 2019-06-04 06:11
Can you share any repro? I can test it and see if I can narrow down the issue. Also accepting any PRs to fix it, if it’s only affecting Windows it may be a path issue somewhere in the code base.

**Comment by rodsfreitas** [comment] 2019-06-04 23:20
@blakeembrey we found here that the problem is when we used ts-node/register.
in package.json we were using nodemon -r ts-node/register. 

to solve this problem with async/await, we used nodemon --exec ts-node and it worked. it follows the working scripts in package.json:

```
"dev": "TS_NODE_COMPILER_OPTIONS='{\"module\":\"commonjs\"}' NODE_ENV=development nodemon --watch 'server/**/*.ts' --exec ts-node server/index.ts",
"win-dev": "SET TS_NODE_COMPILER_OPTIONS={\"module\":\"commonjs\"} && SET NODE_ENV=development&& nodemon --watch 'server/**/*.ts' -exec ts-node server/index.ts"
```

**Comment by cspotcode** [comment] 2020-03-27 15:44
This error happens when you are compiling your .ts *twice* because you double-registered ts-node.

When an async function is compiled, it gets converted to use `__awaiter` and `__generator` helpers.
[Playground example](https://www.typescriptlang.org/play/index.html?noImplicitAny=false&strictNullChecks=false&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&noImplicitReturns=false&alwaysStrict=false&esModuleInterop=false&declaration=false&target=1#code/IYZwngdgxgBAZgV2gFwJYHsL3egFAShgG8YBfIA)

Then, if you try to compile that output *again* as if it were TypeScript input, you get type errors inside the `__generator` helper function, because that function is raw JS and does not have the proper type annotations.  It is not meant to be compiled as TypeScript.
On line 25, you get the OPs error: `Type '0' is not assignable to type '{ label: number; sent: () => any; trys: any[]; ops: any[]; }'.`
[Playground example](https://www.typescriptlang.org/play/index.html?noImplicitAny=false&strictNullChecks=false&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&noImplicitReturns=false&alwaysStrict=false&esModuleInterop=false&declaration=false&target=1&ssl=1&ssc=1&pln=1&pc=25#code/G4QwTgBA+lIO4gJYBcCmkC8EAUyAWiAzhAGQkT5EB0M8SaYAlBAD4sQBmArgHYDGyRAHseOSoQCCYAOYAaaOGlcAtqh7JC8gArzpa9CGRCmEAN4BYAFAQbnXgOGiQAEyEAHZNlAAbLqmamEGCoyFxgoj5+EIg8hMgg-KhCHBBaEAD8EJGoEABcEDyocKnY3PyCIjjBhELewP5mQag1daheIL7+ANwQAL6MPb1Wtk2h4QVFOGlsUxBYWmBCykT+jKX2FaLY1bX18sEAVqgCAcMjtmUOldzeHIje3qjO7Z0BFGAAno1xqG7YeoUwIZjFRCgAPTzZRgDPoQPiGPh4HANQKHY6ebqwobWc42S6bJpHARPF5+N7IT7fNB-AEGIxgADaACJ8Is4EyALqk1aDOEIpHYFGE9GCmG9PpnXH4xwQH5-apcbzIN4KpVUVyFDJNFr1bbNRXIKhQvIQFzuTyqw1Qqj4NTrW73R7OfaoIloZxiyXnOXYf76IH0uYQWkBkEgNxubwfXAESQyeSwGQqNQaVjsBkc6Gg1AQ7DQrpe-oFyy9YugSAwEPAzBiWOkcjiGhQKv05gzaWVGNEKRyCAAIyEzg+pxxNnL0CDgW8ID7qG8+QADPJCCn8h2eHnGogUrgGQuOaQIABGZisoTFZAMo8cnrBMaiS-XwbyCkfQj5DPydzviAZvryDh5A+F9dGLEY7zCURpEnCYIXyeowD7bAF0YeQWTwNkmXg9AkJPNCIPCLCshw7AACZmF6F8PjcJIUgAZQ+ZQB28OYMCwJl1yZescGkBkGKY2oqBQOljAPLB103VEQkgihY0GVDgzAi4NhlBCkJ4FVpPGdccGATT71lalsAZHh5GATNBkGL0dJ9dwR1xGxtxwDhTww88JmKAAVajUAAUTARYwGwJkAHF-WraJiA6YIXC+HNji4QQeGkKgmQGL0RjgAhHhwKBT0pCxRwcxydxSLAjyA7jcCDdw9wPchSK1D5mQInhORNWr9ya5kz3ZA8Zl9ZAg2aplWs5ZgyAoKh4QebBh3kFCTQ+bMIQm8gAEJqqwQ0Zu8OavzcK9M0YdURAaVqKCU4qSpwL4sCXChmHcIMGU6+qIFIl8jQ6PwbwyhzCDgFBERwN77Ou3F4RXCAF3yKGciPfIhqwdwej7GKAGsroh2x4YgAAWfIoCoadZ28ABqcnby00RAmyfJauveQNVQNcOmh0t-ohvGAFYiZJmc50pno7ogRmbzFtwXv3Ho+BEJK-GxnG+WhgB2BmpawYnvyoNx3DzHpidfQhdf1mE5fUGJFa567nFQDgQANXIbeVpzsE25HoBtT5NAoINDUeZL8AgAA+GHuMvAO1GkYOAFpj0zKq3tYrAADY00luqU4+6FGigIMF1l+WrdQKyiuVkY3eTtisAAZiq9ahoG8XQ4oLPJpbgAeNva+Ot5idJucasOp9+0xsuK4cqvDq6muIHTyaB8Flju8fRPAiXsn-aOnpPdRsfUBALGJXLyfoh3IbF4FrfV4ZUj169weWO2u+Je1twTbcLhCDwbA7LR8eJ8z7nDdpee+zB36fzNkrM+Rsfamz+ObYuPBran1xNiZWz0sADiHNNDoe1xA9gTOlNBsJ4TIBBqKRoWDfyp3kKgCWotC6wjuDwfBXxAhlT9vdCeU8dzJ3IDzVybJM6jwunTH6rNM5dUyC3eCQhEDOBhszM6SMwBRE5kVbEmidIcCEEISSXoLq0AQMJIK4gzIKKUQ9YAVjlF2HKDKSSowZKVnCvSLsvsdLYFgODXEF074QAAPQACpWohKCX9LRYoSHYiAA)

Closing this as answered and not a ts-node bug.  There are other issues that talk about improving reporting around accidental double-registration of ts-node if you're interested.

**Closed by cspotcode** 2020-03-27 15:44 UTC
Labels: needs more info
