### ISSUE TITLE
Cannot use ts-node to run custom script in Expo project

### ISSUE THREAD

**Issue by Lpaydat** [TypeStrong/ts-node#929] opened 2019-12-25 09:42 UTC
Hello, noob here.

I have some ReactJs project which is run perfectly on every aspect.
But recently I want to make it monorepo and I chose Expo for this job.

I can make most of code works except some custom scripts.
It say `SyntaxError: Cannot use import statement outside a module` and the line of code that lead to this error was `node_modules/expo/AppEntry.js` which is in the `main` parameter in `package.json`.

This is the full log:
```
$ ts-node -r tsconfig-paths/register --project scripts/helpers/tsconfig.json scripts/customScript.ts
/home/username/Workspace/project/node_modules/expo/AppEntry.js:1
import 'expo/build/Expo.fx';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1050:16)
    at Module._compile (internal/modules/cjs/loader.js:1098:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Object.require.extensions.<computed> [as .js] (/home/username/Workspace/project/node_modules/ts-node/src/index.ts:529:44)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/username/Workspace/project/scripts/helpers/customScript.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
error Command failed with exit code 1.
```

and this is the content of `scripts/helpers/tsconfig.json`:

```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "jsx": "preserve",
    "lib": ["dom", "esnext"],
    "moduleResolution": "node",
    "noEmit": true,
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "target": "es5",
    "allowJs": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "esModuleInterop": true,
    "module": "commonjs",
    "isolatedModules": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "noImplicitThis": false
  },
  "exclude": ["node_modules"],
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"]
}
```

This error not occur on every scripts, just some custom script commands and all error disappear if I remove `main` field from `package.json`.

I tried to search for solution for hours and tried a bunch of methods with no results. T__T

**Comment by blakeembrey** [comment] 2019-12-25 20:53
Do you have a reproduction I can try?

**Comment by Lpaydat** [comment] 2019-12-27 02:44
@blakeembrey Sorry for late reply.

 I have created an example to reproduce this error, you can see it here [ts-node-next-expo](https://github.com/Lpaydat/ts-node-next-expo).

It's the `customScript` command.

**Comment by trusktr** [comment] 2020-01-02 06:36
@Lpaydat Are you on Node.js 13?

**Comment by trusktr** [comment] 2020-01-02 06:44
As I thought, `/Users/trusktr/Desktop/ts-node-next-expo/node_modules/expo/AppEntry.js` is an ES Module. The issue is https://github.com/TypeStrong/ts-node/issues/935

**Comment by Lpaydat** [comment] 2020-05-25 22:27
@trusktr Really sorry for very very late reply.

I can't remember Node.js version on that day (today I use 14, so maybe that day is 13+).

My simple solution now is just writing a script to remove `AppEntry.js` line from `package.json` before running any script and then add it back after the command is completed (this is also the reason of my absent, sorry again).

Thank you for #935, I will check it today :)

**Comment by cspotcode** [comment] 2020-11-22 06:13
Assuming the most recent comment is accurate, we can close this.

**Closed by cspotcode** 2020-11-22 06:13 UTC
