### ISSUE TITLE
child process stdout redirect

### ISSUE THREAD

**Issue by PatrikTrefil** [TypeStrong/ts-node#1751] opened 2022-05-16 15:57 UTC
### Search Terms

- child_process
- stdout redirect
- fork

### Expected Behavior

When creating a child process using `child_process.fork("file.js", { silent: true })`, it is expected that the stdout of the child process is redirected to the parent process.

### Actual Behavior

stdout is not redirected.

### Steps to reproduce the problem

```javascript
// parent.ts
const fork = require("child_process").fork;
const proc = fork("./child.js", { silent: true });
proc.stdout.on("data", (data: any) => {
    console.log(data.toString());
});
console.log("parent");
```

```javascript
// child.js
console.log("child");
```

```bash
$ npx ts-node ./parent.ts
parent
```

If we rewrite parent.ts in vanilla JS we get:

```javascript
// parent.js
const fork = require("child_process").fork;
const proc = fork("./child.js", { silent: true });
proc.stdout.on("data", (data) => {
    console.log(data.toString());
});
console.log("parent");
```

```bash
$ node ./parent.js
parent
child
```

### Specifications

* ts-node version: v10.7.0
* node version: v17.8.0
* TypeScript version: Version 4.6.4
* tsconfig.json, if you're using one: Not using tsconfig.json

* Operating system and version: Windows 11
* If Windows, are you using WSL or WSL2?: No

**Comment by cspotcode** [comment] 2022-05-16 16:15
Something I noticed:

```
$ npx ts-node ./parent.js
```

Check if it should be `parent.ts` (note the file extension)

**Comment by PatrikTrefil** [comment] 2022-05-16 16:22
> Something I noticed:
> 
> 
> 
> ```
> 
> $ npx ts-node ./parent.js
> 
> ```
> 
> 
> 
> Check if it should be `parent.ts` (note the file extension)

I made a mistake in the issue description. Should be fixed now.

**Comment by cspotcode** [comment] 2022-05-16 16:27
It's working for me.  Here's what I get:
https://github.com/TypeStrong/ts-node-repros/tree/ts-node-issue-1751

Please take a look at that branch and see if anything needs to be changed to reproduce.

**Comment by cspotcode** [comment] 2022-05-18 03:58
Closing because, as far as I can tell, this works as intended.  If OP or anyone else is able to create a working reproduction, we can always re-open and investigate.

**Closed by cspotcode** 2022-05-18 03:58 UTC
Labels: needs more info
