### ISSUE TITLE
Inspect is broken in 5.0.1, but ok in at least 3.3.0

### ISSUE THREAD

**Issue by govorov** [TypeStrong/ts-node#549] opened 2018-03-04 00:24 UTC
Hi,

I'm experiencing issues with latest `ts-node`  and `inspect` flag:
`yarn run ts-node --inspect=localhost:9229 -r tsconfig-paths/register ./src/server.ts`
I see no connection with my launched chrome inspector.

Whereas version 3.3.0 is fine with exactly the same command:
```
Debugger listening on ws://localhost:9229/1e4dda24-b443-46a0-90a8-0d505d62b145
```

Related StackOverflow discussion with the same problem:
https://stackoverflow.com/questions/49042830/why-does-the-node-inspector-not-start-when-i-am-using-nodemon-and-ts-node/49090594#49090594

Thank you!

**Comment by blakeembrey** [comment] 2018-03-04 03:37
Duplicate of https://github.com/TypeStrong/ts-node/issues/543. Please check the README and search past issues in the future.

**Closed by blakeembrey** 2018-03-04 03:37 UTC
