### ISSUE TITLE
worker process in cluster mode can't enable type-check

### ISSUE THREAD

**Issue by lp6moon** [TypeStrong/ts-node#496] opened 2017-12-18 07:51 UTC
https://github.com/TypeStrong/ts-node/blob/129153f810a7e2306a89ecafff9ae698dc871fff/src/index.ts#L173

here `options.typeCheck` is `null` not `undefined`, so it didn't load env settings

**Comment by Diluka** [comment] 2017-12-18 08:15
https://github.com/TypeStrong/ts-node/blob/129153f810a7e2306a89ecafff9ae698dc871fff/src/_bin.ts#L97-L105

The default cmd args is set with `null`. And `null` is not equal to `undefined`.

**Comment by blakeembrey** [comment] 2017-12-23 02:53
Looks like a duplicate of https://github.com/TypeStrong/ts-node/issues/483.

**Closed by blakeembrey** 2017-12-23 02:53 UTC
Labels: bug
