### ISSUE TITLE
Can't pass --experimental-specifier-resolution flag to node

### ISSUE THREAD

**Issue by kshetline** [TypeStrong/ts-node#1180] opened 2020-12-20 23:33 UTC
### Expected Behavior

Should be able to pass flag.

### Actual Behavior

Getting the error message: "Unknown or unexpected option: --experimental-specifier-resolution"

### Steps to reproduce the problem

Assume 'ts-node' is installed in the local npm package:
`npx ts-node --experimental-specifier-resolution=node example.ts`

### Minimal reproduction

Same as above.

### Specifications

* ts-node v9.1.1
* node v14.15.3
* compiler v4.1.3
* tsconfig.json:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "outDir": "./dist",
    "sourceMap": true,
    "declaration": true,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "target": "ES2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  },
  "include": ["./src/**/*"],
  "exclude": [
    "**/*.spec.ts",
    "dist",
    "node_modules"
  ]
}

```
* Operating system and version: MacOS 11.0.1

**Comment by cspotcode** [comment] 2020-12-20 23:38
This comes up a lot.  It's working as intended.  See explanation here:
https://github.com/TypeStrong/ts-node/issues/1073#issuecomment-656225803

See also, a few others I found in the issue tracker:
https://github.com/TypeStrong/ts-node/issues/574
https://github.com/TypeStrong/ts-node/issues/522

This issue explains one of the problems that would happen if we spawned subprocesses.
https://github.com/TypeStrong/ts-node/issues/471

**Comment by cspotcode** [comment] 2020-12-20 23:39
Closing as answered.  If you have more questions, feel free to [open a Discussion thread](https://github.com/TypeStrong/ts-node/discussions) or ask on the [TypeScript Community Discord](https://discord.com/invite/typescript)

**Closed by cspotcode** 2020-12-20 23:39 UTC

**Comment by cspotcode** [comment] 2020-12-20 23:58
I've started a discussion post to explain this in more detail.

#1182  Feel free to ask follow-up questions and I'll do my best to update the post with all relevant information.
