### ISSUE TITLE
Add documentation how to add syntax highlighting for ts-node

### ISSUE THREAD

**Issue by sinapis** [TypeStrong/ts-node#1144] opened 2020-11-03 11:23 UTC
### Desired Behavior
Please document how it's possible to achieve syntax highlighting with ts-node, like is shown in the readme of this project:
![image](https://user-images.githubusercontent.com/15230040/97979355-a9dded80-1dd7-11eb-96c7-e8dfeaf769a8.png)

**Comment by cspotcode** [comment] 2020-11-03 15:16
@sinapis Looks like that screenshot comes from #710 which predates my involvement in this project.

Have you looked at that pull request, specifically the comments about a terminal theme?  If so, did it enable you to setup similar syntax highlighting?  As far as I know, this coloring comes from the terminal theme.  ts-node does not emit ANSI escape codes for color.

**Comment by cspotcode** [comment] 2020-11-03 15:17
@blakeembrey do you know how that screenshot was generated?

**Comment by sinapis** [comment] 2020-11-03 16:13
@cspotcode the link in the PR mentions carbon.now.sh which does not help with real console highlighting, only generating static images.

**Comment by cspotcode** [comment] 2020-11-03 17:01
@sinapis Is it possible that you simply can't do console highlighting like this?

**Comment by sinapis** [comment] 2020-11-03 17:39
@cspotcode you're probably right and ts-needs to use some highlighting library. I'm not a Linux guru, just saw that image and thought it is possible.

**Comment by blakeembrey** [comment] 2020-11-08 05:13
Ah yeah, I think this would be possible to do but probably not trivial. To clarify, the request is for syntax highlighting support in the console and not just to figure out how to take the screenshot?

**Comment by sinapis** [comment] 2020-11-08 09:01
@blakeembrey Yes, I want syntax highlighting in the console for ts-node. Is it possible to configure my console to support that?

**Comment by cspotcode** [comment] 2020-11-08 21:04
The problem is the console likely does not know the difference between the first 2x lines in this example:

```
> console.log('this is not code and should not be syntax highlighted')
this is not code and should not be syntax highlighted
> 
```

Highlighting would have to be built-in to `ts-node`.  Unfortunately, we use [`node`'s own REPL implementation](https://nodejs.org/dist/latest-v15.x/docs/api/repl.html). As far as I know, it does not let us colorize the user's input as they type.  Even if it did, we would need a library to perform this colorization.

Only speaking for myself, I suspect this will never happen due to the high level of complexity and effort and the relatively low benefit.

Are there any other REPLs that perform syntax-highlighting in the console?  I'm curious if there are any examples out there.

**Comment by sinapis** [comment] 2020-11-08 22:06
I've seen some kind of colorizing of output, i think even ts-node does it. There is [API for it in node.js](https://nodejs.org/api/repl.html#repl_customizing_repl_output)

There is [ptpython](https://github.com/prompt-toolkit/ptpython) that performs nice syntax highlighting for python. 
Also the next REPL of nodejs - [node-prototype-repl](https://github.com/nodejs/repl) - is doing exactly that. maybe ts-node can use that?

![image](https://user-images.githubusercontent.com/15230040/98485445-106f6b00-221f-11eb-900d-46262108805b.png)

**Comment by cspotcode** [comment] 2020-11-09 14:13
That node API you linked talks about customizing REPL output, not the input code, correct?

Will node's built-in syntax highlighting support TypeScript syntax?

Finally, the million-dollar question: do you know someone who will implement this for us?  Speaking for myself, I will not, at least not in the short-term, because the benefits do not seem worth the complexity.  There are other features I need to prioritize.  But if you or someone you know is going to dedicate the time, then I'll certainly review a PR.

**Comment by sinapis** [comment] 2020-11-09 18:09
Yes, only output.

Yes. It uses [emphasize](https://www.npmjs.com/package/emphasize) which support typescript. basically you need to change one letter here: https://github.com/nodejs/repl/blob/master/src/highlight.js instead of js need to provide ts

As you probably understood, I was looking at the nice screenshot and figured this neat feature is already implemented.

Unfortunately I cannot do it right now, though I may find time for this in the near future.

**Comment by cspotcode** [comment] 2020-11-10 01:21
Ok, sounds good.  I'm going to close this issue only because the issue's title, asking for documentation, has been answered: we can't provide documentation because this is not possible.

Please don't hesitate to create a new issue linked to this one that asks for syntax highlighting of REPL input.  We can mark it as "help wanted" to indicate that we'll review a PR adding it.  I've been trying to keep the issue tracker clean so that the title and body of the issue clearly explains the feature/bug/question.

**Closed by cspotcode** 2020-11-10 01:21 UTC
