### ISSUE TITLE
Heap Snapshot Slow

### ISSUE THREAD

**Issue by timoxley** [TypeStrong/ts-node#1398] opened 2021-07-14 14:20 UTC
Taking heap snapshots while using `ts-node` seems to take an unusually long time.

```js
import { writeHeapSnapshot } from 'v8'
console.log(writeHeapSnapshot())
```

```
node: 200ms
ts-node: 15s
```

This test is not fair of course, since ts-node had to load all the ts toolchain and do the transpiling, but IMO 15 seconds seems far too long for a 10MB snapshot.

This seems likely to be more of an an issue with v8 or even typescript, but reporting here as you may find this interesting or have some ideas.

### Minimal reproduction

See https://github.com/timoxley/test-ts-snapshot

### Specifications

* ts-node v9.1.1
* node v16.5.0
* compiler v4.3.5
* tsconfig.json: https://github.com/timoxley/test-ts-snapshot/blob/main/tsconfig.json
* macOS 11.4

**Comment by cspotcode** [comment] 2021-07-14 17:29
Are you running the typechecker?  That'll load a ton of @types and other .d.ts and build a lot of type info.

I'd be curious to see the speed of generating a heap snapshot from `tsc` when it's finished typechecking a project, or from ts-node in transpile-only mode where it has skipped any typechecking and thus has also parsed far fewer source files.

**Comment by timoxley** [comment] 2021-07-15 14:49
I think what surprised me was that the slowdown occurred with such a minimal input file, literally just this: https://github.com/timoxley/test-ts-snapshot/blob/main/index.mjs

When that's built with tsc (after changing extension to .ts), it doesn't change much:

```
"use strict";
exports.__esModule = true;
var v8_1 = require("v8");
var path_1 = require("path");
var name = process.env.npm_lifecycle_event || path_1.basename(process.argv[0]);
console.log(name, '>>');
console.time(name);
console.log(v8_1.writeHeapSnapshot());
console.timeEnd(name);
console.log(name, '<<');
```

The dump when running this with `node index.js` takes 164.57ms.

> Are you running the typechecker?

Yes.

> ts-node in transpile-only mode where it has skipped any typechecking and thus has also parsed far fewer source files.

Doesn't seem to make any difference:

normal: 14.685s
transpile-only: 14.532s

Added a script for this:
https://github.com/timoxley/test-ts-snapshot/blob/d17caeae73fafc9c4b098081fdf1f1769046df81/package.json#L16

**Comment by cspotcode** [comment] 2021-07-15 15:24
Someone would have to send us a pull request with those changes, and before we merged it, we would need some clearer proof that ts-node is causing the slowdown.  (as opposed to typescript, source-map-support, or any other third-party dependency)

**Comment by cspotcode** [comment] 2021-07-15 15:25
If the changes used a sandbox environment, they would also need to compare performance against our current in-thread implementation.

**Comment by dyst5422** [comment] 2021-07-27 22:35
This recently became high priority for my team. Compiling to js to run it just so we can get heap snapshots is rough.

**Comment by cspotcode** [comment] 2021-07-27 22:37
Have you been able to narrow down the cause, and do you have a proposed
solution?

**Comment by cspotcode** [comment] 2021-09-05 14:16
@dyst5422 @timoxley is there anything we need to do here?

**Comment by timoxley** [comment] 2021-09-05 14:40
It would be good if you could try reproducing the problem to try see where the problem exists or if there's anything that can be done to alleviate it in ts-node. It's a bit beyond me.

**Comment by cspotcode** [comment] 2021-09-05 14:56
What is the performance for something like this?

```
node -e 'require("typescript"); console.time(); require("v8").writeHeapSnapshot(); console.timeEnd()'
```

**Comment by cspotcode** [comment] 2021-09-07 14:37
@timoxley are you able to confirm timing for the benchmark test above?

**Comment by timoxley** [comment] 2021-09-07 17:56
@cspotcode 😢 amazing, yeah ok that just seems to get stuck in a loop forever. Never ends, process at 100% CPU.
I guess the issue is `typescript` itself not `ts-node`.

**Comment by cspotcode** [comment] 2021-09-07 18:02
Interesting.  For me it takes about 13 seconds.  My guess: try different versions of typescript and of node.  Maybe you're hitting a node or a typescript bug.

I'll go ahead and close this issue, but discussion is not locked, in case there is more to talk about.

**Closed by cspotcode** 2021-09-07 18:02 UTC
Labels: needs more info

**Comment by timoxley** [comment] 2021-09-07 18:09
@cspotcode That was done using `node v14.17.5` on `typescript@4.4.2`, similar results with `typescript@4.5.0-dev.20210907`.

Just tried again on `node v16.5.0` and `typescript@4.5.0-dev.20210907`: 28.804s.

So I think you're right, it's some v8/node weirdness.

**Comment by hansl2** [comment] 2022-01-06 06:22
Facing the same problem as @dyst5422, it just hangs(Ran for 20+ minute before i killed the process) when i run ts-node. When i ran `node -e 'require("typescript"); console.time(); require("v8").writeHeapSnapshot(); console.timeEnd()'`. It takes 15 second but it does not hang. 

To reproduce:
1. `ts-node` in terminal(zsh). It is install globally
2. `import { writeHeapSnapshot } from "v8"`
3. `console.log(writeHeapSnapshot())`

| Key | Value |
| --- | ----------- |
| Ts-node version | 10.4.0 |
| Typescript version  | 4.5.0 |
| Node version | 16.7.0 |
| OS | mac OS Big Sur M1 |

**Result:** It hangs

**Comment by theanarkh** [comment] 2023-01-29 16:29
I had the same problem recently. I try to debugger into V8 and found it consumes much time in `V8HeapExplorer::IterateAndExtractReferences`, then i print some infos in this function and recompile Node.js.

<img width="1337" alt="image" src="https://user-images.githubusercontent.com/21155906/215337935-5b60e0af-5920-4e98-b21f-3b5c8ab67d25.png">

My test is as follows(test.js).
```js
console.time('heapsnapshot');
console.log(require('v8').writeHeapSnapshot('11.heapsnapshot'));
console.timeEnd('heapsnapshot');
```
When i run the test by `node test.js`, the result is as follows.
```
the final output of i: 30681
time: 2.812s
size of file: 2864297
```
and when i run the test by `node bin/ts-node test.js`, the result is as follows.
```
the final output of i: 111805
time: 5:40.787 (m:ss.mmm)
size of file: 11020805
```
The follow picture is the heapsnapshot diff.
<img width="1789" alt="image" src="https://user-images.githubusercontent.com/21155906/215339903-0cef42d7-c225-488f-bc0a-bfecb830f09f.png">


My test environment is as follows.
```
tsc v4.9.4
ts-node v10.4.0
node v15.14.0
OS MacOS Darwin Kernel Version 20.6.0
```
