### ISSUE TITLE
`--` arg disappears

### ISSUE THREAD

**Issue by joeskeen** [TypeStrong/ts-node#47] opened 2015-12-20 03:41 UTC
First off, thanks for creating and maintaining `ts-node`.  It is awesome!

Consider the following Node script `args.js`:
```js
console.log(process.argv)
```
Calling this with `node`, we get the following result:
```bash
>node args hi -- test -a
[ 'C:\\Program Files\\nodejs\\node.exe',
  'C:\\temp\\args',
  'hi',
  '--',
  'test',
  '-a' ]
```
But if you call it using `ts-node`, you lose the `--` argument:
```bash
>ts-node args hi -- test -a
[ 'node', 'C:\\temp\\args', 'hi', 'test', '-a' ]
```
I came across this when trying to use `yargs` to parse command line arguments.  `yargs` considers the `--` argument as a signal to stop parsing arguments and take the rest of the arguments as string literals rather than switches.  When running it through ts-node, the `--` disappears, so arguments that should be taken literally are being parsed as switches.  I can overcome this by passing `-- --`, but I think it would be better to have a consistent behavior between `node` and `ts-node` for interoperability.

**Comment by blakeembrey** [comment] 2015-12-20 17:48
This is definitely a bug, let me confirm and patch it now. Thanks for the report!

**Comment by blakeembrey** [comment] 2015-12-20 18:10
Related issue: https://github.com/substack/minimist/issues/71

**Comment by blakeembrey** [comment] 2015-12-20 18:26
Opened https://github.com/substack/minimist/pull/77. Not sure if or when it'll be merged since the project is quiet.

**Closed** 2016-06-11 03:08 UTC
Labels: bug, dependency

**Comment by zbigg** [comment] 2019-01-15 10:38
Looks like, there is regression. `--` disappears in newest `ts-node@7.0.1`.

Should we reopen this one or create new issue ?

--
Here's the script:

```
$ cat ./foo.js 
console.log('raw args', process.argv);
```

Actual behavior - script doesn't see the `--` :
```
$ npx ts-node ./foo.js -- foo bar
raw args [ 'node',
  '/home/user/foo/foo.js',
  'foo',
  'bar' ]
```
Same without npx, to prove that's not npx
```
$ ./node_modules/.bin/ts-node ./foo.js -- foo bar
raw args [ 'node',
  '/home/user/foo/foo.js',
  'foo',
  'bar' ]
```

Expected behavior (node is ok) - script sees `--` and can interpret it:
```
$ node ./foo.js -- foo bar
raw args [ '/home/user/.nvm/versions/node/v10.11.0/bin/node',
  '/home/user/foo/foo.js',
  '--',
  'foo',
  'bar' ]
```

Env:
```
$ ./node_modules/.bin/ts-node --version
ts-node v7.0.1
node v10.11.0
typescript v3.2.2
cache "/tmp/ts-node-732b3ea8158c1ce0f45c23f0d6d0dc7df99bcd697d222f18f9ad1bd2f273e528/76e10fcb695febc00ffc6bc37e357d102d336c414698899e54c4837fad976a1b"
```
OS: Ubuntu 18

**Comment by blakeembrey** [comment] 2019-01-15 17:11
@zbigg Feel free to close, I'll look into it soon and start moving to https://github.com/zeit/arg now that it supports TypeScript and the functionality is a lot clearer.

**Comment by lonix1** [comment] 2019-02-23 19:51
@zbigg Have the same problem here...
Did you find a workaround?

**Comment by blakeembrey** [comment] 2019-02-23 23:05
@lonix1 This shouldn't be a problem using the latest release.
