### ISSUE TITLE
npm ts-node is broken in version 10.2.0

### ISSUE THREAD

**Issue by wandyezj** [TypeStrong/ts-node#1428] opened 2021-08-09 23:00 UTC
### Expected Behavior

> npx ts-node@10.1.0
```text
v10.1.0
```

> npx ts-node@10.2.0

```text
v10.2.0
```

### Actual Behavior

> npx ts-node@10.2.0

```text
Cannot find module 'typescript'
```

### Steps to reproduce the problem

> npx ts-node@10.2.0

### Minimal reproduction

> npx ts-node@10.2.0

### Specifications

* ts-node version:
* node version:
* TypeScript version:
* tsconfig.json, if you're using one:
```
{}
```
* Operating system and version:
* If Windows, are you using WSL or WSL2?:

**Comment by cspotcode** [comment] 2021-08-09 23:12
Closing as duplicate of #1426

**Closed by cspotcode** 2021-08-09 23:12 UTC

**Comment by wandyezj** [comment] 2021-08-10 19:18
@cspotcode The duplicate was also closed with the explanation that this was something related to npx? However the above example seems to indicate that this change is related to a change in ts-node.
