### ISSUE TITLE
ts-node does not load typings installed with npm

### ISSUE THREAD

**Issue by rainyday** [TypeStrong/ts-node#271] opened 2017-02-15 23:30 UTC
ts-node won't recognize typings installed via npm, such as `npm install @types/node`

to reproduce create a typescript file that imports or uses node modules or globals such as:

```javascript
import * as path from 'path';
console.log(__dirname);
```

and run `npm -D install @types/node` and then `ts-node test.ts` This will result in these compile errors:

```
TSError: ⨯ Unable to compile TypeScript
test.ts (1,23): Cannot find module 'path'. (2307)
test.ts (2,13): Cannot find name '__dirname'. (2304)
```

**Comment by blakeembrey** [comment] 2017-02-15 23:35
Seems like a duplicate of https://github.com/TypeStrong/ts-node/issues/216.

**Closed by blakeembrey** 2017-02-15 23:35 UTC
