### ISSUE TITLE
Support for node's --unhandled-rejections=strict

### ISSUE THREAD

**Issue by alextes** [TypeStrong/ts-node#1076] opened 2020-07-16 07:56 UTC
### Desired Behavior
When an unhandled promise rejection occurs I'd like the process to exit. Node even explains in a warning that this is their intended future behavior, if you want that behavior now, you can pass the `--unhandled-rejections=strict` flag. ts-node does not appear to support it. Or maybe I misunderstand how to pass it, in which case this issue can be read as a suggestion to change the docs.

### Alternatives you've considered
Compiling with tsc and running with node. Sadly stack-traces get worse and it's a bit cumbersome in development when running with docker-compose for example.

**Comment by cspotcode** [comment] 2020-07-16 15:02
Duplicate of multiple other issues, for example, #1073

See also: #1074, where we are awaiting a pull request that improves documentation.

**Closed by cspotcode** 2020-07-16 15:02 UTC

**Comment by cirosantilli** [comment] 2021-05-25 21:58
To answer other Googlers more directly this seems to do it:

```
node --unhandled-rejections=strict -r ts-node/register main.ts
```

test `main.ts` program:

```
(async () => { throw 'asdf' })()
```

Related: https://stackoverflow.com/questions/54041199/how-to-pass-parameters-to-a-script-processed-by-ts-node

**Comment by cspotcode** [comment] 2021-05-25 22:03
This is also mentioned in the docs: https://typestrong.org/ts-node/docs/configuration#node-flags
And there is a discussion thread which goes into even more detail: https://github.com/TypeStrong/ts-node/discussions/1182

**Comment by rattrayalex** [comment] 2021-07-17 01:02
Per the docs, an alternative syntax for the lazy:

```
NODE_OPTIONS='--unhandled-rejections=strict' ts-node main.ts
```
