### ISSUE TITLE
alias namespace imports not working in ESM

### ISSUE THREAD

**Issue by joacub** [TypeStrong/ts-node#1442] opened 2021-08-28 20:13 UTC
When enable modules the alias and base paths does not work.

this is the code and this the second fix the problem:

```js
if (shouldBeTreatedAsRelativeOrAbsolutePath(specifier)) {
    resolved = new URL(specifier, base);
  } else if (specifier[0] === '#') {
    ({ resolved } = packageImportsResolve(specifier, base, conditions));
  } else {
    try {
      resolved = new URL(specifier);
    } catch {
-----------
      resolved = packageResolve(specifier, base, conditions);
-----------
    }
  }```

FIXED:
```js
if (shouldBeTreatedAsRelativeOrAbsolutePath(specifier)) {
    resolved = new URL(specifier, base);
  } else if (specifier[0] === '#') {
    ({ resolved } = packageImportsResolve(specifier, base, conditions));
  } else {
    try {
      resolved = new URL(specifier);
    } catch {
-----------
      try {
      resolved = packageResolve(specifier, base, conditions);
      } catch {
        resolved = new URL(specifier, base);
      }
    }
-----------
  }```

**Comment by cspotcode** [comment] 2021-08-28 21:07
Is this a bug report, a feature request, or a discussion thread?  As-is it's unclear; I may need to close it.

**Comment by joacub** [comment] 2021-08-28 21:52
> Is this a bug report, a feature request, or a discussion thread? As-is it's unclear; I may need to close it.

Is a bug, the typescript loser is not loading imports in src or base path folders

**Comment by joacub** [comment] 2021-08-28 21:54
For example:

import ‘webpack’  —— works
Import ‘myfolderinsidebasepath/my file’ —— does not work any more

**Comment by cspotcode** [comment] 2021-08-28 21:54
The proposed changes are in a file that's been copied directly from node's source code.  Has this been fixed in upstream nodejs?

**Comment by joacub** [comment] 2021-08-28 23:44
I have no idea, this still so unstable ?

many many libraries are migrating to esm only so we are force to use esm with typescript.

so that code comes from nodejs source ???

**Comment by cspotcode** [comment] 2021-08-29 00:25
I've been explaining node's ESM instability to people for months, so I don't want to repeat myself here.  I hope you understand, it's exhausting.

Relevant links and context:
#1007 
https://github.com/TypeStrong/ts-node/blob/main/dist-raw/README.md
https://nodejs.org/dist/latest-v16.x/docs/api/esm.html#esm_loaders
https://nodejs.org/dist/latest-v16.x/docs/api/documentation.html#documentation_stability_index
https://github.com/nodejs/node/pull/37468 
https://github.com/nodejs/loaders

Remember that suggested changes to `ts-node` should be submitted in the form of a pull request.

Good luck!

**Comment by joacub** [comment] 2021-08-29 00:27
I understand you 100%, I do not understand why people is migrating libraries just for esm, but yeah, my solution for now is to fix this manually in the source code and that's it

thanks

**Comment by joacub** [comment] 2021-08-29 02:21
just one question, I don't know if you already mention this, but why ts-node is not longer looking at the tsconfig.json compilerOptions.paths ?

**Comment by joacub** [comment] 2021-08-29 06:41
by the way, I created this in some minutes that fix all the issues about loading files extension etc. if you want to include, I already tested and is perfect.


```js
/* eslint-disable no-cond-assign */
import { fileURLToPath } from 'url';
import { createRequire } from 'module';
import { Stats, statSync } from 'fs';
import { join, dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const require = createRequire(fileURLToPath(import.meta.url));

const { ERR_MODULE_NOT_FOUND } = require('./node_modules/ts-node/dist-raw/node-errors').codes;

/** @type {import('ts-node/dist/esm')} */
const esm = require('./node_modules/ts-node/dist/esm');

const {
  resolve: _resolve,
  getFormat,
  transformSource,
} = esm.registerAndCreateEsmHooks({
  transpileOnly: true,
});

function tryStatSync(path) {
  try {
    return statSync(path);
  } catch {
    return new Stats();
  }
}

/*
 * Legacy CommonJS main resolution:
 * 1. let M = pkg_url + (json main field)
 * 2. TRY(M, M.js, M.json, M.node)
 * 3. TRY(M/index.js, M/index.json, M/index.node)
 * 4. TRY(pkg_url/index.js, pkg_url/index.json, pkg_url/index.node)
 * 5. NOT_FOUND
 */
function fileExists(url) {
  return tryStatSync(fileURLToPath(url)).isFile();
}

function legacyMainResolve(fileToFound, base) {
  let guess;
  // Note: fs check redundances will be handled by Descriptor cache here.
  if (fileExists((guess = new URL(`./${fileToFound}`, base)))) {
    return guess;
  }
  if (fileExists((guess = new URL(`./${fileToFound}.ts`, base)))) {
    return guess;
  }
  if (fileExists((guess = new URL(`./${fileToFound}.tsx`, base)))) {
    return guess;
  }
  if (fileExists((guess = new URL(`./${fileToFound}.js`, base)))) {
    return guess;
  }
  if (fileExists((guess = new URL(`./${fileToFound}.json`, base)))) {
    return guess;
  }
  if (fileExists((guess = new URL(`./${fileToFound}.node`, base)))) {
    return guess;
  }
  if (fileExists((guess = new URL(`./${fileToFound}/index.ts`, base)))) {
    return guess;
  }
  if (fileExists((guess = new URL(`./${fileToFound}/index.tsx`, base)))) {
    return guess;
  }
  if (fileExists((guess = new URL(`./${fileToFound}/index.js`, base)))) {
    return guess;
  }
  if (fileExists((guess = new URL(`./${fileToFound}/index.json`, base)))) {
    return guess;
  }
  if (fileExists((guess = new URL(`./${fileToFound}/index.node`, base)))) {
    return guess;
  }
  // Not found.
  // Not found.
  throw new ERR_MODULE_NOT_FOUND(fileToFound, base);
}

const resolve = async (specifier, context, defaultResolve) => {
  const resolveResponse = await _resolve(specifier, context, defaultResolve).catch((error) => {
    let fileFound = null;
    ['api', 'src'].some((path) => {
      const fileToFind = join(__dirname, path);
      fileFound = legacyMainResolve(specifier, `file://${fileToFind}/`);
      return fileFound;
    });
    if (fileFound) {
      return { url: fileFound.href };
    }
    throw error;
  });

  return resolveResponse;
};

export { resolve, getFormat, transformSource };

```

**Comment by cspotcode** [comment] 2021-08-29 20:20
That code change probably breaks requirements for `--experimental-specifier-resolution=[mode]` https://nodejs.org/dist/latest-v16.x/docs/api/esm.html#esm_customizing_esm_specifier_resolution_algorithm

Can't know without running it against our tests.

**Comment by joacub** [comment] 2021-08-29 20:22
if you see the code, you will notice that this is a fallback in case that node resolution didn't found anything.

Si this is not gonna break anything since this is a fallback when node loader crash.

**Comment by cspotcode** [comment] 2021-08-29 20:36
Saying that it works for one person for a single day is very different from saying it meets the requirements of `ts-node` and that it passes the necessary automated tests.  Adding fallback behavior that was not there before is a breaking change.

**Comment by joacub** [comment] 2021-08-29 20:44
o, yeah of course, I was not trying to said is stable, is just an idea that is working perfect in this context, but you probably will have an idea how to fix node resolutions before everything becomes stable, 

btw, I don't think there is any instability in node resolution, is just they don't see anymore in paths, there is just 3 ways to make the resolutions which is packages, absolute and relative that's it.

**Comment by cspotcode** [comment] 2021-09-05 14:14
Is there anything actionable here?  Or is everything working as intended?  Coming back to https://github.com/TypeStrong/ts-node/issues/1442#issuecomment-907694469, is our behavior differing from node, or is are we correctly matching upstream node's behavior?

**Comment by cspotcode** [comment] 2021-09-19 17:51
Closing as everything is working correctly; no bugs; no action required.

**Closed by cspotcode** 2021-09-19 17:51 UTC
