### ISSUE TITLE
VSCode Debugging

### ISSUE THREAD

**Issue by amcdnl** [TypeStrong/ts-node#46] opened 2015-12-15 02:28 UTC
VSCode will not recognize any breakpoints hit.

**Comment by blakeembrey** [comment] 2015-12-20 18:27
You're going to have to provide a lot more information for anyone to replicate. I personally don't even use VSCode, so have no idea what this issue even means or where to start. How do I reproduce it? It's unlikely it's an issue with `ts-node`, but I don't know where to start.

**Comment by amcdnl** [comment] 2015-12-21 15:39
@blakeembrey absolute; so its rather simple.  do `require('ts-node/register')` and set a breakpoint in any file from there. I'm positive its related to source maps not getting mapped correctly when using register. If you need more details, let me know if you can't reproduce and i'll create a demo repo.

What IDE you use? VSCode seems like a obvious TS user IDE.

**Comment by enlight** [comment] 2015-12-23 06:24
I've hit this issue today, though I'm not using the latest revision and it seems like there have been some changes to source map generation lately. The main problem here I think is that VSCode seems to require access to a `.js` file on disk, but ts-node doesn't emit the generated code to a file. The TypeScript `inlineSources` compiler options could've perhaps provided a workaround, unfortunately according to the docs https://code.visualstudio.com/docs/editor/debugging

> VS Code supports inlined source maps but not inlined source

so that's a dead end unless someone adds support for it in VSCode.

**Comment by blakeembrey** [comment] 2015-12-23 22:32
Yeah, it sounds like this is unlikely to ever work then. That's unfortunate. VSCode would have to hook into `source-map-support` to make this happen, which someone might be able to do easily enough. Since all the generated files and source maps are in memory, if there's some way to communicate that then we can make it work, otherwise you'll have to rely on actually transpiling files for now.

**Comment by jonaskello** [comment] 2015-12-29 11:56
I am using ts-node to run mocha. I can get debugging to work in Webstorm although there are issues:

1. Webstorms own breakpoints does not work, I need to explicitly add a "debugger" statement in the source code.
2. Webstorm highlights the wrong line. It is about 20 lines off the debugger statement.

Is there some way to verify that the source maps generated in memory are correct when running mocha?

**Comment by jonaskello** [comment] 2015-12-29 12:04
Tried setting both inlineSourceMap and inlineSources to true in tsconfig.json but exact same behaviour in Webstorm.

**Comment by blakeembrey** [comment] 2015-12-29 13:25
The source maps are all correct, I believe the issue is what I mentioned above - the fact they don't have access to the source maps. If there's some way to make access possible, I'll investigate it. Perhaps the source map location could be absolute and I could write the files into a temporary directory during execution.

**Comment by arolson101** [comment] 2016-05-04 14:25
Looks like things have changed- https://code.visualstudio.com/docs/editor/debugging:
> VS Code supports both the inlined source maps and the inlined source.

I've tried turning on these options but breakpoints still don't work for me.  My config:
```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Test",
			"type": "node",
			"request": "launch",
			"program": "${workspaceRoot}/node_modules/mocha/bin/_mocha",
			"stopOnEntry": false,
			"args": ["--require", "ts-node/register", "test/table.test.ts"],
			"cwd": "${workspaceRoot}",
			"preLaunchTask": null,
			"runtimeExecutable": null,
			"runtimeArgs": [
				"--nolazy"
			],
			"env": {
				"NODE_ENV": "development"
			},
			"externalConsole": false,
			"sourceMaps": true,
			"outDir": null
		},
```

**Comment by blakeembrey** [comment] 2016-05-04 15:21
@arolson101 I believe you misunderstand. There's no difference. TypeScript still does not have access to the source maps of `ts-node` - they are in memory. I have a working debugger just fine with VS Code, but you need to emit the `.js` and source map files for VS Code to consume (and configure `outDir`) and not use `ts-node`.

**Comment by blakeembrey** [comment] 2016-06-11 03:42
Coming back to this, I use VS Code now and often use the debugging feature. However, I recommend you compile the JavaScript files with source maps and execute those directly instead. It's pretty simple with VS Code to set up a CLI task that watches and compiles using `tsc` and restarts the program while listening to the debugger.

**Comment by amcdnl** [comment] 2016-06-11 15:46
😒

**Comment by nbransby** [comment] 2016-06-24 14:12
Does this mean no translated stack traces from node when an uncaught exception is thrown whilst debugging in vscode?

**Comment by blakeembrey** [comment] 2016-06-24 15:33
No. How are you debugging in vscode?

**Comment by nbransby** [comment] 2016-06-24 16:32
Without using ts-node, obviously works fine but I switched to ts-node so I could have proper stack traces on a crash but then the debugger doesn't pick up the breakpoints. So I have both configs in my launch.json and I just comment in/out the relevant one depending if I want to debug or run

**Comment by blakeembrey** [comment] 2016-06-24 17:20
Did you even read this issue?

**Comment by blakeembrey** [comment] 2016-06-24 17:21
If you want to re-map errors according to source maps, I'd recommend checking out https://github.com/evanw/node-source-map-support.

**Comment by nbransby** [comment] 2016-06-24 18:17
I did read it, I assumed by " I recommend you compile the JavaScript files with source maps and execute those directly instead" you meant don't use ts-node.

I did look at that project before but looked like far more effort to setup compared to ts-node, i'll stick with switching configs for now

**Comment by blakeembrey** [comment] 2016-06-24 18:23
Yes, that's exactly what I recommend. I'm not sure what you're asking now, sorry. That project is only one line - you asked for source map support with stack traces?

**Comment by nbransby** [comment] 2016-06-24 18:37
yes will take another look thanks

**Comment by amcdnl** [comment] 2016-06-30 14:07
'm coming back to this after a bit, have a few comments since first started...

> TypeScript still does not have access to the source maps of ts-node - they are in memory
@blakeembrey Are you not  saving the files to disk at all? I know `babel/register` actually does that.

> The main problem here I think is that VSCode seems to require access to a .js file on disk, but ts-node doesn't emit the generated code to a file. The TypeScript inlineSources compiler options could've perhaps provided a workaround, unfortunately according to the docs...
@enlight you should check this out, looks like it has it now https://github.com/Microsoft/vscode/issues/2803

> I'd recommend checking out https://github.com/evanw/node-source-map-support.
@blakeembrey would be worth considering building this into ts-node.

> I have a working debugger just fine with VS Code, but you need to emit the .js and source map files for VS Code to consume (and configure outDir) and not use ts-node.
@blakeembrey so I have to ask if this is necessary what is the point of this project? ;)

**Comment by blakeembrey** [comment] 2016-06-30 16:25
> Are you not saving the files to disk at all?

No, that's the entire point. Babel only does that as a cache, but a cache doesn't help much with TypeScript since it's not a single file cache and requires the entire project loaded anyway for compilation errors. In `--fast` mode, it's possible we could do it. On top of this, if VS Code (or other debuggers) can use the source maps from files while executing the rest in memory, I'm happy to make that change - it seems like a great fix to me.

> would be worth considering building this into ts-node.

It has been since the first release.

> so I have to ask if this is necessary what is the point of this project?

Because some people have different use-cases to you and don't need an IDE debugger. For instance, I've never used it (for something I'd use `ts-node` for). I usually use `ts-node` for running tests without needing to compile them and restructure the entire project with fixtures.

**Comment by amcdnl** [comment] 2016-06-30 21:58
Thanks for clarifying those details! I'm just trying to understand the use cases for the project given the hurdles. 

I hate having to have tool and workflow for build/etc when this theoretically could be done on the fly 😞

**Comment by blakeembrey** [comment] 2016-06-30 22:12
Understandable - I think it'd be valuable to check if generating the source map contents into a temp file would fix this. I'll make that change when I get a chance, probably just rewriting contents into `tmp/<sha>` files for caching and lookup later. I really feel it might fix this, so thanks for the idea!

**Comment by amcdnl** [comment] 2016-07-01 12:33
@blakeembrey awesome!! Let me know and i'll give it a try on my [demo project](https://github.com/swimlane/nodejs-seed) I'm working on.

For reference, on the [Babel](https://babeljs.io/docs/usage/require/) page you can see `BABEL_CACHE_PATH` variable which sets the path `BABEL_CACHE_PATH=/foo/my-cache.json babel-node script.js`. By default I think it saves them in `node_modules` that being local or global.

**Comment by jeffijoe** [comment] 2016-07-11 09:54
Any progress on this? I'm using the CLI with nodemon and ts-node + attach in VSCode

**Comment by blakeembrey** [comment] 2016-07-20 00:50
I went ahead and built https://github.com/TypeStrong/ts-node/pull/148. Feel free to test it and let me know if it works.

I have a suspicion that it won't though. VS Code needs to be able to discover the source map file. If it could do that, it should have been doing that already with previous versions. The issue is that VS Code needs access to both `.js` and `.js.map` files to work properly with debugging.

**Comment by amcdnl** [comment] 2016-07-20 12:47
@blakeembrey couldn't you inline the sourcemaps?

**Comment by blakeembrey** [comment] 2016-07-20 16:00
@amcdnl That's how it worked in `0.x`.

**Comment by amcdnl** [comment] 2016-07-20 18:21
I'll test it out shortly and let you know! Thanks for looking into it either way!

**Comment by rjmacarthy** [comment] 2016-08-10 15:34
I'd be very interested to know if anyone finds a good solution to this problem too.

**Comment by trainerbill** [comment] 2016-09-21 20:10
Yeah this is tricky.  I wanted a way to debug my test scripts.   I started by trying to create a task.json which would run my npm test script and setting the breakpoints and they would get skipped due to sourcemaps or some error.  After hours of playing around I just add a Debug launch.json task with the program as the currently open file. 

launch.json
```js
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug",
            "type": "node",
            "request": "launch",
            "cwd": "${workspaceRoot}",
            "program": "${file}",
            "stopOnEntry": false,
            "sourceMaps": true,
            "outDir": "${workspaceRoot}/dist"
            
        }
    ]
}
```

tsconfig.json
```sh
{
    "compileOnSave": true,
    "compilerOptions": {
        "module": "commonjs",
        "target": "es2015",
        "sourceMap": true,
        "inlineSources": true,
        "isolatedModules": true,
        "outDir": "./dist"
    },
    "exclude": [
        "node_modules"
    ]
}
```
Now when I go to debugger set a breakpoint, and launch the Debug on the open file, it breaks as expected.  This is good enough for me since if I am setting breakpoints I really only want to run the one file anyway and not the entire test suite.

Most of my development is test driven so the classes are only constructed in the tests.  I can set breakpoints in the src/module.ts file as well and when the test executes them it breaks there as well.

The only drawback is that now my ./dist folder contains src and test folders, but I am going to either npm/git ignore them or write some logic into my versioning script to remove dist/test and move the files from dist/src to /dist.

So this really isn't even a ts-node issue as everything is doable in VSCode.

**Comment by arturoarevalo** [comment] 2017-02-06 12:55
I've been able to debug TypeScript code running directly with ts-node (this is without precompilation), even inside a Docker container, within VS Code, using the ["V8 Inspector Integration"](https://nodejs.org/api/debugger.html#debugger_v8_inspector_integration_for_node_js) feature in Node > 6.3.

My tsconfig.json:

```javascript
{
    ...
    "compilerOptions": {
         ...
        // "sourceMap": true,
        "inlineSources": true    // use inlineSources instead of sourceMap
    },
    ...
}
```
My launch configuration in VSCode's launch.json:

```javascript
        {
            "type": "node2",
            "request": "attach",
            "name": "Attach to Port",
            "port": 9229
        }
```

Just run your script with --inspect=PORT (9229 by default), i.e. `ts-node --inspect source/index.ts`

**Comment by vigie** [comment] 2017-02-06 23:04
@arturoarevalo could you expand a little - when you set `inlineSources` tsc forces you to also set either `sourceMap` or `inlineSourceMap` - which do you set? Also, by setting these aren't you implying that you are in fact transpiling before launching the debugger, or does ts-node somehow use these settings under the hood?

**Comment by vigie** [comment] 2017-02-06 23:58
Just to confirm, I also now have the set-up @arturoarevalo describes above working, except that setting `inlineSources` or any other mapping flag in `tsconfig.json` is not needed. I also do **not** have `sourceMaps` set within my launch.json. 

With the above set-up you are **not** explicitly generating or linking to transpiled code or maps. What happens is that ts-node generates and writes the files to a temporary location on disk as the typescript files are loaded by node, and the debugger is smart enough to locate and use those maps. You can see this happening if you launch the debugger with the `verboseDiagnosticLogging` flag set. It's a pretty nice set-up.

The thing that threw me to begin with was that I was trying to get breakpoints to stick in typescript files before the had been `require`d by the running program. This is not possible - the typescript file must be loaded first and then you can hit whatever breakpoints you like from within functions in that file.

**Comment by rjmacarthy** [comment] 2017-02-07 09:08
Pretty good solution @arturoarevalo thank you.

**Comment by Moenomi** [comment] 2017-02-08 09:45
@arturoarevalo thanks a lot! I have been looking for a solution like that for a long time..

Just one thing here: It works perfectly if I attach to my local ts-node application, but if it is running inside a Docker container, the breakpoints are shifted if the file is more complex (I still can attach and debug but the source maps seem not to work right, even empty lines shift the code). Setting the tsconfig.json to `inlineSources` doesn't change anything.

Have you experienced something like that?

**Comment by amcdnl** [comment] 2017-02-08 13:40
I still can't seem to get it to work, mind sharing your tsconfig and vscode launch config?

**Comment by Moenomi** [comment] 2017-02-09 08:06
My tsconfig:
```javascript
{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "es6",
      "dom"
    ],
    "module": "commonjs",
    "moduleResolution": "node",
    "outDir": "./bin",
    "inlineSourceMap": true,
    "inlineSources": true,
    "target": "es5",
    "typeRoots": [
      "./node_modules/@types"
    ],
    "noUnusedParameters": false,
    "noUnusedLocals": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "noImplicitAny": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "pretty": true
  },
  "exclude": [
    "node_modules",
    "**/*.spec.ts"
  ],
  "compileOnSave": false
}
```
As @vigie already mentioned, changing the source map settings doesn't change anything. My code is still shifted if I'm attaching to the Docker container.

Here my launch.json for attaching to the container (local is the same without localRoot and remoteRoot):
```javascript
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node2",
            "request": "attach",
            "name": "Attach to Docker",
            "address": "localhost",
            "port": 9229,
            "restart": true,
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "/home/doc/app"
        }
    ]
}
```
Note that the `node2` (v6.3+ - Experimental) is important, it won't work with the old one.

**Comment by henioStraszny** [comment] 2017-02-14 13:55
@arturoarevalo thanks for great solution, I now can confirm working debugging directly from VS Code, plus I could drop transpiling to js.

tsconfig:

`{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "outDir": "dist",
        "lib": [
            "es6",
            "dom"
        ],
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true
    },
    "include": [
        "src/**/*.ts"
    ],
    "exclude": [
        "node_modules"
    ]
}`

**Comment by delfinof** [comment] 2017-02-22 19:23
The "shift" problem outlined by @Moenomi when debugging with visual studio a ts-node project inside a docker container seems to be related to the fact that vscode expects to have source maps available locally; ts-node instead creates them in the temp cache directory.

I guess this can only be fixed by the vscode team.

**Comment by giggio** [comment] 2017-03-16 17:52
This works with `launch` as well. I just got it to run with the latest VSCode (1.10.2).

This is the config in launch.json:

````js
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}\\server\\bin\\www.js",
            "protocol": "inspector"
        }
````

And I did not have to set `inlineSources` to true or any of the source maps configs on ts.config.

**Comment by xs9627** [comment] 2017-03-18 02:02
Thanks, @giggio. "protocol": "inspector" works for me.
Here is the launch.json to debug mocha with ts-node:
`{
      "name": "Run mocha",
      "type": "node",
      "request": "launch",
      "program": "${workspaceRoot}/node_modules/mocha/bin/_mocha",
      "stopOnEntry": false,
      "args": ["--no-timeouts", "--compilers", "ts:ts-node/register", "${workspaceRoot}/test/**/*.test.ts"],
      "cwd": "${workspaceRoot}",
      "protocol": "inspector"
}`

VSCode (1.10.2).

**Comment by blakeembrey** [comment] 2017-03-21 01:38
I'm going to close this issue for now, but feel free to continue the discussion. If someone does find a way for this to work reliably with source maps in IDEs, let me know - I'm happy to add it to the README.

**Closed by blakeembrey** 2017-03-21 01:38 UTC
Labels: dependency, help wanted, research, wontfix

**Comment by amcdnl** [comment] 2017-03-21 12:35
@blakeembrey I think it would be good idea to add @giggio to the readme.

**Comment by leoparis89** [comment] 2017-03-30 10:03
Vs code breakpoints don't work for me.
I have to use debugger statements.

this is my lauch.json

```
{
    "version": "0.2.0",
    "configurations": [
        
        {
            "type": "node",
            "request": "launch",
            "name": "Launch via NPM",
            "runtimeExecutable": "npm",
            "windows": {
                "runtimeExecutable": "npm.cmd"
            },
            "runtimeArgs": [
                "run-script",
                "debug"
            ],
            "port": 5858
        }
    ],
    "compounds": []
}
```

and my debug script in package.json is: 
`    "debug": "ts-node  --nolazy --debug-brk app.ts"`


How can I get the vscode breakpoints working ?
it says 'non verified breakpoiint' when I hover over one.

**Comment by dupski** [comment] 2017-04-25 04:06
Hey all, I've just done a load of work on this. I have a test project working will full debugging of both .ts code and mocha tests. Here's my config (requires Node 6.3 or above and I am using VS Code 1.11):

tsconfig.json:  (just need to make sure sourceMap is true)
```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "noImplicitAny": true,
        "outDir": "./dist",
        "sourceMap": true
    },
    "include": [
        "src/**/*"
    ],
}
```

launch.json:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Current TS Tests File",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/node_modules/.bin/_mocha",
            "args": ["-r", "ts-node/register", "${relativeFile}"],
            "cwd": "${workspaceRoot}",
            "protocol": "inspector"
        },
        {
            "name": "Current TS File",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/node_modules/ts-node/dist/_bin.js",
            "args": ["${relativeFile}"],
            "cwd": "${workspaceRoot}",
            "protocol": "inspector"
        }
    ]
}
```

The key is to make sure you don't run a script that does a `process.spawn()` as I believe this interferes with node's ability to debug properly, hence running `ts-node/dist/_bin.js` above.

If the above works for others, maybe the `_bin.js` script could be exposed in a slightly nicer way @blakeembrey ?

Sample github project:
https://github.com/EnterpriseJSTutorial/vscode-ts-node-debugging

**Comment by blakeembrey** [comment] 2017-04-25 15:44
> If the above works for others, maybe the _bin.js script could be exposed in a slightly nicer way @blakeembrey ?

Sure. We could follow the Mocha pattern and expose an `_ts-node` script globally.

**Comment by sinedied** [comment] 2017-05-03 09:23
Does anyone successfully made it work with WebStorm? I've read through this post, and I'm still stuck trying to debug properly my app with ts-node :/

**Comment by mccool** [comment] 2017-05-31 00:56
@sinedied I have gotten it to work with webstorm 2017.2 EAP using nodemon. I have nodemon and ts-node installed in `devDependencies`.  In my `tsconfig.json` I have `"sourceMap":true` and in my `nodemon.json` file i have included
```json
{
  "exec": "./node_modules/.bin/ts-node --debug-brk src/server",
  "ext": "ts"
}
```

With webstorm you have to use --debug-brk so that it's debugger can attach to it as mentioned in [this comment](https://intellij-support.jetbrains.com/hc/en-us/community/posts/208374225-How-to-debug-a-nodejs-application-in-Webstorm-served-using-nodemon-via-a-Gulp-task).

My configuration settings is shown below as well
<img width="659" alt="screen shot 2017-05-30 at 6 50 16 pm" src="https://cloud.githubusercontent.com/assets/648237/26611120/36a5dca0-4569-11e7-97f9-5bcc02772a88.png">

The issue I'm seeing with this is that the breakpoints aren't really set until the server restarts. If you remove a breakpoint it won't really be gone until the server restarts again. I think this is just how it works with nodemon though. It's not that big of a deal with nodemon though. I hope this makes sense.

**Comment by mccool** [comment] 2017-08-01 18:53
I just got an even easier option for debugging ts-node with webstorm. Just add a script in your `package.json` file like
`"start": "./node_modules/.bin/ts-node $NODE_DEBUG_OPTION --project src ./src/index.ts`

The project flag is described in the readme for ts-node and the last argument is the path to your script to run, in this case it's my express app.

With this you can use control + option + d to start the npm script with webstorm's debugger.

**Comment by k8w** [comment] 2017-09-01 06:58
@dupski @blakeembrey 

It seems this only works when ts-node is installed in the workspaceRoot, but not work when refer to a global `ts-node`.
While `mocha` with `ts-node` works both global and local.

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Current TS File",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/node_modules/ts-node/dist/_bin.js",
            "args": ["${relativeFile}"],
            "cwd": "${workspaceRoot}",
            "protocol": "inspector"
        },
        {
            "name": "Current TS Tests File",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/node_modules/.bin/_mocha",
            "args": ["-r", "ts-node/register", "${relativeFile}"],
            "cwd": "${workspaceRoot}",
            "protocol": "inspector"
        }
    ]
}
```

**Comment by IAMtheIAM** [comment] 2017-09-05 23:10
@mccool I could not get any of the 3 examples you explained working for IntelliJ / WebStorm. When I do your 3rd option `    "debug": "./node_modules/.bin/ts-node --debug-brk --project tsconfig.json ./app/server.ts",`

then start the debugger, it says `Debugger listening on [::]:5858` but then my main app is not running on port 5000, so when I load the page, nothing happens. If I start the app server separately then run this debug command, no breakpoints are hit.

Any ideas?

**Comment by cspotcode** [comment] 2017-10-26 19:23
Debugging in VSCode is now very simple and works well.

```
{ // launch.json
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Program",
            "type": "node",
            "request": "launch",
            "protocol": "inspector",
            // Use ts-node as drop-in replacement for node
            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/ts-node",
            // Manually specify the args to pass
            "runtimeArgs": [
                "${workspaceRoot}/src/foo.ts"
            ]
        }
    ]
}
```

If you try to specify `"program"` config, VSCode will see that it's a `.ts` file and try to locate the corresponding compiled `.js` file.  We don't want that; we're using ts-node so we want to run the `.ts` directly.  `"runtimeArgs"` does what we want, and VSCode doesn't interfere or complain.

Anway, breakpoints "just work!"  Sweet!

**Comment by cgatian** [comment] 2017-11-09 13:08
@cspotcode I was unable to get the breakpoints to hit unless I supplied a `debugger` statement.

**Comment by evgenyt1** [comment] 2018-01-31 17:39
@cspotcode I had to replace "runtimeArgs" with "args" to make it work.
Otherwise `--inspect=12400 --debug-brk` args are passed after `foo.ts` and are ignored by ts-node

node: 8.9.4
ts-node: 4.1.0
vs-code: 1.9.3

**Comment by Xotabu4** [comment] 2018-02-19 17:09
For debugging protractorJS tests this works:

```json
        {
            "type": "node",
            "request": "launch",
            "name": "Working thru node",
            "program": "${workspaceFolder}/node_modules/.bin/protractor",
            "args": [
                "./jasminejs/protractor.conf.js",
                "--directConnect=true"
            ],
            "protocol": "inspector",
            "sourceMaps": true,
            "console": "internalConsole",
            "outputCapture": "std"
        }
```

The only JS file - is `protractor.conf.js`, and first line - `require('ts-node').register();`

tsconfig.json:
```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "sourceMap": true,
    "inlineSourceMap": true,
    "outDir": "./built"
  },
  "exclude": [
    "node_modules/"
  ]
}
```

**Comment by peternann** [comment] 2018-03-17 13:26
Can I very, very strongly suggest that the 'current, best' way to setup VSCode debugging with ts-node is described in the main README?

VSCode is very widely used for Typescript dev. ts-node is awesome during dev.
Both working together is SWEET, but it's BLACK MAGIC to get it going!
There is a TON of partial/old/incorrect information floating around...

An official 'Hello World' debugging setup would give ts-node much more traction with devs I expect... If they can't get it working straight away with step-through debugging - You've lost 80% of folks right there...

**Comment by blakeembrey** [comment] 2018-03-17 17:54
I can check but I'm not sure it should be very complicated to get started. Just add `['-r', 'ts-node/register']` to the default node.js configuration? I don't really use this myself but would accept a PR that adds the example to the README.

**Comment by blakeembrey** [comment] 2018-03-17 18:02
Just verified it working locally by creating a new project. All I did is below. Can someone confirm this?

```json
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "runtimeArgs": [
                "-r",
                "ts-node/register"
            ],
            "args": [
                "${workspaceFolder}/index.ts"
            ]
        }
```

**Comment by peternann** [comment] 2018-03-22 12:35
I'm still getting patchy breakpoint behaviour. It seems to work in the primary file (index.ts), but not in other imported files.

Interestingly, it works somewhat more reliably after a restart of VSCode.
I'm testing a very short-lived script - It feels a bit like a race condition during startup perhaps.
Strangely, WHETHER OR NOT the breakpoint happens to work in any one run, hovering over the breakpoints list in VSCode, after running, always says "Breakpoint ignored because generate code not found (source map problem?)". Yes, it even says that when IT WORKS.

Breakpoint debugging is simply not working for me I'm afraid.
Bummer.

**Comment by s-KaiNet** [comment] 2018-03-24 07:28
> Just verified it working locally by creating a new project. All I did is below. Can someone confirm this? 

Works well for me on node `8.10`, however on node `6.x` breakpoints never hit. Maybe that's the case for other folks.

**Comment by s-KaiNet** [comment] 2018-03-24 08:25
> Works well for me on node 8.10, however on node 6.x breakpoints never hit. Maybe that's the case for other folks.  

**UPDATE:** well, breaks work in an initial file (`index.ts` for example), however, don't work in all imported files :( (`Breakpoint ignored because generate code not found (source map problem`)

**Comment by s-KaiNet** [comment] 2018-03-24 08:39
Created reproduction repository - [here](https://github.com/s-KaiNet/ts-node-46):
1. Clone, `npm i`  
2. Add breaks in `index.ts` and `parser.ts`, F5 -> doesn't work in `parser.ts`

node `8.10` npm `5.7.1`

**Comment by s-KaiNet** [comment] 2018-03-24 09:42
So it looks like vscode [bug](https://github.com/Microsoft/vscode/issues/45657)... superannoying!

**Comment by s-KaiNet** [comment] 2018-03-24 09:49
Installed `1.20` from [here](https://vscode-update.azurewebsites.net/1.20.1/win32-x64/stable) - everything works! ts-node, node, breaks, everything!

**Comment by rjmacarthy** [comment] 2018-03-27 11:21
I've managed to get debugging in ts working. The solution was to compile the ts to js in a dist folder with source maps then attach to the debugger after running the solution. Typescript -w is used to watch the files and  `nodemon` is used to restart the server on js file changes.

You need to be on a Node version which supports the `--inspect` parameter.

Then add a new npm script in package.json

```
    "debug": "concurrently --kill-others \"tsc -w -p src\" \"nodemon --inspect dist/index.js "",

```

Add a new configuration to` .vscode/launch.json`

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "attach",
            "name": "Attach to Port",
            "port": 9229,
            "protocol": "inspector"
        }
    ]
}
```

tsconfig.json

```

{
    "compileOnSave": false,
    "compilerOptions": {
        "sourceMap": true,
        "declaration": false,
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "target": "es5",
        "typeRoots": [
            "node_modules/@types"
        ],
        "lib": [
            "es2016",
            "dom"
        ]
    }
}

```

**Comment by Kamilius** [comment] 2018-03-29 07:48
@s-KaiNet nope, it still doesn't work for me though. Tests are launching, but breakpoints are greyed-out with a message `"Breakpoint ignored because generated code not found (source map problem?)"`.

**Comment by s-KaiNet** [comment] 2018-03-29 07:55
@Kamilius hmmm strange...
Did it work before? 
Do you have 1.20 installed?    

If the answer is yes to both questions, then I don't know the reason why it's still doesn't work for you. For me, 1.20 automagically fixed all issues.

**Comment by Kamilius** [comment] 2018-03-30 05:35
@s-KaiNet @davidwesst thanks, I am already using `insiders` version, which is currently `Version 1.22.0-insider (1.22.0-insider)`, also I'm using `ts-node` inside protractor's `onPrepare()`. My project is generated using `angular-cli` and this configuration comes by default:

```js
  onPrepare() {
    require('ts-node').register({
      project: './e2e/tsconfig.e2e.json'
    });
    jasmine.getEnv().addReporter(new SpecReporter({ spec: { displayStacktrace: true } }));
  }
```

@davidwesst workaround you've suggested, for `ts-node` users, proposes to `reapply all breakpoints`, but it doesn't work for me. Breakpoints stay greyed out after reapplying operation.

**Comment by davidwesst** [comment] 2018-04-11 19:20
@Kamilius -- My apologies as I didn't see this until just now!

Well, 1.22.1 is already out, so hopefully that resolves the issue in the long-term. The answer I found for the breakpoint thing was you needed to follow the following to "reapply all breakpoints":

* Start your debugger
* Break on first line
* _Now disable and re-enable all breakpoints
* You should hopefully hit the next breakpoint
* Repeat every time you debug

Again, hopefully this is fixed in the new version of Code that is out, but that was my little workaround.

**Comment by peternann** [comment] 2018-05-01 05:33
I am still having no luck with this. I gave up on my old project. Figured it had something weird.
But I'm now on a new project, on a different computer, and a different OS, and having the same troubles.

As requested by @blakeembrey, here is my launch config:
```
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "runtimeArgs": [
                "-r",
                "ts-node/register"
            ],
            "args": [
                "${workspaceFolder}/index.ts"
            ]
        }
```
Yes, that is byte-for-byte what was suggested.
I am using vscode 1.22.2, on Windows 7.
Using versions: Node=8.10, ts-node=6.0.2, typescript=2.8.3
(Latest at time of writing)

Breakpoints in the top file (index.ts) work fine, (Even though they report **"Breakpoint ignored because generated code not found (source map problem?)."**

The other breakpoints show the same text on hover, but are grayed out and the breakpoint circle is empty. They go gray as soon as I launch, by the time they hit my test breakpoint in the top file.

The disable/reenable/Reapply All tricks do not work for me.

This is driving me bananas.

Does the contents of tsconfig.json matter? Here's mine right now after minimizing it:
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es6"
    },
    "exclude": [
        "node_modules",
        "**/*.spec.ts"
    ]
}
```

**Any new ideas out there?**

**Comment by iammelvin** [comment] 2018-07-01 08:41
@blakeembrey Thanks for the solution it works !

**Comment by phil294** [comment] 2018-08-19 05:10
For attaching, the process is pretty much the same. package.json:

    "scripts": {
        "dev": "node --inspect $(npm bin)/ts-node index.ts"

and in launch.json the typical

    "type": "node",
    "request": "attach",
    "protocol": "inspector",
     "port": 9229

**Comment by tomitrescak** [comment] 2018-11-12 05:10
I just paste here couple solutions that work nicely:

# Launch

```
{
      "name": "TS Node",
      "type": "node",
      "request": "launch",
      "env": {
        ... whatever
      },
      "args": ["./src/server/index.ts"],
      "runtimeArgs": ["--nolazy", "-r", "ts-node/register"],
      "sourceMaps": true,
      "cwd": "${workspaceRoot}",
      "protocol": "inspector"
    }
```

# Attach With forever

```
{
      "name": "Forever",
      "type": "node",
      "request": "attach",
      "sourceMaps": true,
      "port": 9229,
      "cwd": "${workspaceRoot}",
      "protocol": "inspector"
    }
```

And the command 

`forever -a --watch --watchDirectory ./src/server --uid youruid -c \"node --nolazy -r ts-node/register --inspect=9229\" src/server/index.ts`

**Comment by zwhitchcox** [comment] 2019-06-13 20:12
```json
{
      "name": "TS Node",
      "type": "node",
      "request": "launch",
      "env": {
        ... whatever
      },
      "args": ["./src/server/index.ts"],
      "runtimeArgs": ["--nolazy", "-r", "ts-node/register"],
      "sourceMaps": true,
      "cwd": "${workspaceRoot}",
      "protocol": "inspector"
    }
```

This did not work for me...the only think that has worked is manually compiling the typescript files and then manually running the debugger

**Comment by JingLMalan** [comment] 2019-08-10 02:58
> Just verified it working locally by creating a new project. All I did is below. Can someone confirm this?
> 
> ```json
>         {
>             "type": "node",
>             "request": "launch",
>             "name": "Launch Program",
>             "runtimeArgs": [
>                 "-r",
>                 "ts-node/register"
>             ],
>             "args": [
>                 "${workspaceFolder}/index.ts"
>             ]
>         }
> ```

thank you very much

**Comment by pirix-gh** [comment] 2019-09-06 19:06
Hey @blakeembrey, do you know if this is still working correctly?
Because I am able to debug using breakpoints, but in some cases, the breakpoint is just ignored.
This seems to happen when a breakpoint is placed in a file that is not directly run. I also tried to add `--nolazy` but without success. Should I just transpile?

```json
{
	"launch": {
		"configurations": [
			{
				"name": "Debug Current",
				"type": "node",
				"request": "launch",
				"args": [
					"${fileBasename}"
				],
				"runtimeArgs": [
					"-r",
					"ts-node/register"
				],
				// "sourceMaps": true,
				"cwd": "${fileDirname}",
				"protocol": "inspector",
				"outputCapture": "std",
			},
		],
		"compounds": []
	}
}
```

**Comment by pirix-gh** [comment] 2019-10-14 15:07
nevermind, it seems to be related to https://github.com/microsoft/vscode-chrome-debug-core/issues/533

**Comment by GuillaumeDesforges** [comment] 2021-01-29 18:30
If anybody lands here, I'd advise using ts-node-dev

example: https://gist.github.com/GuillaumeDesforges/bf7383f8403e1683b2b9467db3964185

**Comment by rdotg** [comment] 2021-06-01 23:55
Thank you @GuillaumeDesforges I tried like a 1000 different ways and this was the only one that worked for my use case 😓 

```
{
            "name": "runit",
            "type": "node-terminal",
            "request": "launch",
            "command": "ts-node-dev --inspect -T -O '{\"esModuleInterop\": true}' --skip-project my-scripts/migrate.ts my-scripts/a",
            "cwd": "${workspaceFolder}"
},

```
