### ISSUE TITLE
Date type changed to Object type, when run from src, while run from build works.

### ISSUE THREAD

**Issue by An1mus** [TypeStrong/ts-node#567] opened 2018-04-12 17:12 UTC
Hello. 
I've created a decorator for DateTime field, which type is Date. 
TS(src) example:
```
@DateTimeField()
someField: Date;
```
JS(build) example:
```
__decorate([
      date_time_field_1.DateTimeField(),
      __metadata("design:type", Date)
]
```

When running test from `.ts` file, Reflect.type of this field is `Object` , and `.js` gives back `Date`. 
While build folder contains:
` __metadata("design:type", Date)`

Decorator function:
```
export function DateTimeField(options: DateTimeFieldDecoratorOptions) {
    return (target: any, name: string, descr?: any) => {
        validatePropertyDecorator(target, name, descr);

        const reflectType = Reflect.getMetadata("design:type", target, name);
        checkReflectType(reflectType, Date, name);

        const field = getOrCreateField(target, name);
        Object.assign(field, options, {type: ResourceFieldType.DateTime});
    }
}
```

Tell me please if I need to provide you with some more info?

**Comment by blakeembrey** [comment] 2018-04-14 00:57
Duplicate of https://github.com/TypeStrong/ts-node/issues/511. See also https://github.com/TypeStrong/ts-node#features. This will likely be reverted in the future.

**Closed by blakeembrey** 2018-04-14 00:57 UTC
