### ISSUE TITLE
TypeChecking is still not working properly in 7.0.0

### ISSUE THREAD

**Issue by JonWallsten** [TypeStrong/ts-node#659] opened 2018-08-07 06:31 UTC
So I just changed "target" from es5 to es6 in tsconfig. And suddenly ts-node starts to complain about stuff in my tools (see error + source code below). 
VS Code does not indicate any errors in the file.  
Running "tsc" produces no errors what so ever.
transpileOnly flag does nothing unfortunately.

Any idea whats going in here? Downgrading to 5.0.1 works fine. Setting target back to es5 works fine.

Node: 8.9.4
Webpack: 4.16.3
Typescript: 3.0.1
TS-node: 7.0.0

```
"scripts": {
    "build:dev": "npm run webpack -- --config config/webpack.dev.ts --progress --colors --hide-modules --display-error-details --profile --display-entrypoints",
    "webpack": "ts-node --transpileOnly --max_old_space_size=8192 node_modules/webpack/bin/webpack.js"
  }
```

```
C:\Users\me\repo\web-lib-angular1\node_modules\ts-node\src\index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: Ô¿» Unable to compile TypeScript:
config/plugins/dts-bundle.ts(9,14): error TS2339: Property 'name' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(10,14): error TS2339: Property 'options' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(13,14): error TS2339: Property 'options' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(13,41): error TS2339: Property 'options' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(14,14): error TS2339: Property 'options' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(14,37): error TS2339: Property 'options' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(15,14): error TS2339: Property 'options' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(15,38): error TS2339: Property 'options' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(16,14): error TS2339: Property 'options' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(16,40): error TS2339: Property 'options' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(17,14): error TS2339: Property 'options' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(17,41): error TS2339: Property 'options' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(17,69): error TS2339: Property 'options' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(18,14): error TS2339: Property 'options' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(18,34): error TS2339: Property 'options' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(18,55): error TS2339: Property 'options' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(19,14): error TS2339: Property 'options' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(19,37): error TS2339: Property 'options' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(19,61): error TS2339: Property 'options' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(19,85): error TS2339: Property 'options' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(20,14): error TS2339: Property 'options' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(20,42): error TS2339: Property 'options' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(21,14): error TS2339: Property 'options' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(21,35): error TS2339: Property 'options' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(22,14): error TS2339: Property 'options' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(22,36): error TS2339: Property 'options' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(25,48): error TS2339: Property 'name' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(26,37): error TS2339: Property 'options' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(27,38): error TS2339: Property 'options' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(31,29): error TS2339: Property 'options' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(41,38): error TS2339: Property 'name' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(42,39): error TS2339: Property 'options' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(47,28): error TS2339: Property 'options' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(48,28): error TS2339: Property 'options' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(49,27): error TS2339: Property 'options' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(50,36): error TS2339: Property 'options' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(53,31): error TS2339: Property 'options' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(56,22): error TS2339: Property 'options' does not exist on type 'DtsBundlePlugin'.
config/plugins/dts-bundle.ts(57,29): error TS2339: Property 'options' does not exist on type 'DtsBundlePlugin'.

    at createTSError (C:\Users\me\repo\web-lib-angular1\node_modules\ts-node\src\index.ts:261:12)
    at getOutput (C:\Users\me\repo\web-lib-angular1\node_modules\ts-node\src\index.ts:367:40)
    at Object.compile (C:\Users\me\repo\web-lib-angular1\node_modules\ts-node\src\index.ts:557:11)
    at Module.m._compile (C:\Users\me\repo\web-lib-angular1\node_modules\ts-node\src\index.ts:439:43)
    at Module.m._compile (C:\Users\me\repo\web-lib-angular1\node_modules\ts-node\src\index.ts:439:23)
    at Module._extensions..js (module.js:654:10)
    at require.extensions.(anonymous function) (C:\Users\me\repo\web-lib-angular1\node_modules\ts-node\src\index.ts:442:12)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\Users\me\repo\web-lib-angular1\node_modules\ts-node\src\index.ts:442:12)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (C:\Users\me\repo\web-lib-angular1\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\Users\me\repo\web-lib-angular1\config\webpack.base.ts:9:22)
    at Module._compile (C:\Users\me\repo\web-lib-angular1\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Module.m._compile (C:\Users\me\repo\web-lib-angular1\node_modules\ts-node\src\index.ts:439:23)
    at Module.m._compile (C:\Users\me\repo\web-lib-angular1\node_modules\ts-node\src\index.ts:439:23)
    at Module._extensions..js (module.js:654:10)
    at require.extensions.(anonymous function) (C:\Users\me\repo\web-lib-angular1\node_modules\ts-node\src\index.ts:442:12)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\Users\me\repo\web-lib-angular1\node_modules\ts-node\src\index.ts:442:12)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (C:\Users\me\repo\web-lib-angular1\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\Users\me\repo\web-lib-angular1\config\webpack.dev.ts:6:24)
    at Module._compile (C:\Users\me\repo\web-lib-angular1\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Module.m._compile (C:\Users\me\repo\web-lib-angular1\node_modules\ts-node\src\index.ts:439:23)
    at Module.m._compile (C:\Users\me\repo\web-lib-angular1\node_modules\ts-node\src\index.ts:439:23)
    at Module._extensions..js (module.js:654:10)
    at require.extensions.(anonymous function) (C:\Users\me\repo\web-lib-angular1\node_modules\ts-node\src\index.ts:442:12)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\Users\me\repo\web-lib-angular1\node_modules\ts-node\src\index.ts:442:12)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
```

Source code: 
```
import * as dts from 'dts-bundle';
import { existsSync } from 'fs';
import * as rc from 'recursive-copy';
import * as rimraf from 'rimraf';

export type pluginOptions = {
    libraryName: string
    srcPath: string
    distPath: string
    dtsCopySrc: string
    dtsCopyDest: string
    main: string
    outFile: string
    removeSrcDts: boolean;
    debug: boolean;
    filter: string[];
};

export class DtsBundlePlugin {
    private options: pluginOptions;
    private name: string = 'dts-bundle';

    constructor (options: pluginOptions) {
        this.options = options;
        // Set src and dest paths unless provided
        const root = process.cwd() + '/';
        this.options.libraryName = this.options.libraryName || 'index';
        this.options.srcPath = this.options.srcPath || root + 'src/';
        this.options.distPath = this.options.distPath || root + 'dist/';
        this.options.dtsCopySrc = this.options.dtsCopySrc || root;
        this.options.dtsCopyDest = this.options.dtsCopyDest || this.options.distPath + 'declaration/';
        this.options.main = this.options.main || this.options.dtsCopyDest + 'src/index.d.ts';
        this.options.outFile = this.options.outFile || this.options.distPath + this.options.libraryName + '.d.ts';
        this.options.removeSrcDts = this.options.removeSrcDts || false;
        this.options.debug = this.options.debug || false;
        this.options.filter = this.options.filter || ['src/**/*.d.ts'];
    }

    apply (compiler) {
        compiler.hooks.afterEmit.tapAsync(this.name, (_compilation, callback) => {

            const dtsCopySrc = this.options.dtsCopySrc;
            const dtsCopyDest = this.options.dtsCopyDest;
            const rcOptions = {
                overwrite: true,
                filter: [
                    ...this.options.filter
                ]
            };
            rc(dtsCopySrc, dtsCopyDest, rcOptions, function (error, _results) {
                if (error) {
                    console.error('[webpack: plugin/dts-bundle]', error); // tslint:disable-line no-console
                }
                callback();
            });
        });

        compiler.hooks.done.tap(this.name, () => {
            if (!existsSync(this.options.main)) {
                console.error('[webpack: plugin/dts-bundle] main does not exist.'); // tslint:disable-line no-console
                return;
            }

            dts.bundle({
                name: this.options.libraryName,
                main: this.options.main,
                out: this.options.outFile,
                removeSource: this.options.removeSrcDts,
                outputAsModuleFolder: true,
                emitOnIncludedFileNotFound: true,
                verbose: this.options.debug
            });

            // DTS Bundle does not remove the folder, just the files.
            if (this.options.removeSrcDts) {
                rimraf(this.options.dtsCopyDest, (error) => {
                    if (error) {
                        console.error('[webpack: plugin/dts-bundle] ', error); // tslint:disable-line no-console
                    }
                });
            }
        });
    }
}
```

**Comment by blakeembrey** [comment] 2018-08-07 15:42
Can you please create a standalone repo or zip or something that can be used to demonstrate the problem? I suspect there’s more to your problem than what you’re saying. For instance, webpack adds `ts-node` for you so you’re double loading it and that would cause issues.

**Comment by blakeembrey** [comment] 2018-08-07 16:45
Closing this issue actually, I'm 99% sure it's caused by you double loading `ts-node`. Don't do `ts-node --transpileOnly` and it should be fixed. The reason it changes based on ES6 vs ES5 is because ES5 would not be emitting a class anymore and TypeScript is probably only trying to follow and type check the `class`.

**Closed by blakeembrey** 2018-08-07 16:45 UTC

**Comment by blakeembrey** [comment] 2018-08-07 23:18
5.0 only works because it’s in transpile only. It’s not more robust, it’s just transpiling TS to JS and JS to JS without error. If you avoid double registering you should be fine on any version.
