### ISSUE TITLE
Cannot use imported module

### ISSUE THREAD

**Issue by servermeta** [TypeStrong/ts-node#243] opened 2016-11-27 18:02 UTC
In a newly created project:

index.ts
```

export class SheetApi {

    hello = () => 'hello world';

}
```

On the ts-node repl:

```
> import {SheetApi} from './src/index'
'use strict'
> SheetApi
⨯ Unable to compile TypeScript
[eval 1].ts (1,1): Cannot find name 'SheetApi'. (2304)
```

why is that? It gives me problems only with ts-node repl, not if I use it in a file.

What does that 'use strict' mean?

**Comment by blakeembrey** [comment] 2016-11-28 03:02
Ah, this is a real pain point, thanks for picking up on it. The issue is TypeScript actually elides imports that aren't used which hinders the ability to write a decent REPL. Previous iterations went with the approach of using one giant file and using `diff` to exec the changes between new lines, but that failed in other unexpected ways (released in https://github.com/TypeStrong/ts-node/releases/tag/v1.5.0, see https://github.com/TypeStrong/ts-node/issues/189). 

Unfortunately using `import` or `export` also puts things into module mode (not global), so I suspect that also fails even if we managed to get `import` to work. Pinging @mhegazy for ideas, because I'm out now - both solutions have their pitfalls as a way to build the REPL.

**Comment by blakeembrey** [comment] 2016-11-28 03:04
Perhaps the best solution will be reverting to the previous single document approach, and if a newline begins with `(` or `[`, automatically inserting a semicolon onto the previous line before diffing.

**Closed** 2016-12-09 22:45 UTC
Labels: bug
