### ISSUE TITLE
Error when running in Travis and AppVeyor

### ISSUE THREAD

**Issue by budiadiono** [TypeStrong/ts-node#227] opened 2016-10-29 13:00 UTC
I got error when running test on Travis-CI and AppVeyor-CI. My tests working fine in my local computer (Windows 10).

Here's the log from Travis that also similar to log from AppVeyor:

```bash
> mocha --require ts-node/register test/common/specs/**/*.ts

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Module.m._compile (/home/travis/build/vue-typed/vue-typed/node_modules/ts-node/src/index.ts:406:23)
    at Module._extensions..js (module.js:422:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/travis/build/vue-typed/vue-typed/node_modules/ts-node/src/index.ts:409:12)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at /home/travis/build/vue-typed/vue-typed/node_modules/mocha/lib/mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/travis/build/vue-typed/vue-typed/node_modules/mocha/lib/mocha.js:219:14)
    at Mocha.run (/home/travis/build/vue-typed/vue-typed/node_modules/mocha/lib/mocha.js:487:10)
    at Object.<anonymous> (/home/travis/build/vue-typed/vue-typed/node_modules/mocha/bin/_mocha:458:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
```

**Comment by blakeembrey** [comment] 2016-10-29 18:58
Please post the code you use, the version you use, the node version you're using and configuration. I can't help without any information.

**Comment by blakeembrey** [comment] 2016-10-29 19:00
I'm going to close this as it's clearly not a `ts-node` issue. The issue is that you're emitting features that aren't supported in your node version.

**Closed by blakeembrey** 2016-10-29 19:00 UTC

**Comment by blakeembrey** [comment] 2016-10-29 19:02
I also see in your linked commits you couldn't run it with `ts-loader` (https://github.com/vue-typed/vue-typed/commit/a6dbcdd5b69bde811b1d0ad7804dab371eb73519). You needed to add Babel. Maybe you should try emitting ES5 instead of ES6?

**Comment by budiadiono** [comment] 2016-10-29 19:52
Ah, that was good catch! Yes the node on CI is different from my local machine. CI uses v5.12.0 and my local machine is v6.9.1. I'll try to invesitage it again later. Thank you @blakeembrey !

**Comment by blakeembrey** [comment] 2016-10-29 19:54
No worries. The ES6 support between v5 and v6 is a lot different, so that makes sense. On node 6, I get away with ES6 output but definitely couldn't before v6 was released (I had a TypeScript -> Babel workflow because I wanted to use `async`/`await` but node v5 can't handle basics like deconstruction, default parameters, etc).

**Comment by budiadiono** [comment] 2016-10-29 20:13
Oh I just realize that, thanks for sharing @blakeembrey. It's very useful, cause I think I have similar problems with my other apps.

**Comment by budiadiono** [comment] 2016-10-30 02:36
I confirm that this issue is truly false alarm. @blakeembrey  is right, upgrading node version on CI machines to v6 solving the problem.
