### ISSUE TITLE
Sending multiple lines to ts-node

### ISSUE THREAD

**Issue by RenWenshan** [TypeStrong/ts-node#558] opened 2018-03-22 23:47 UTC
### Bug

```
function minimizeXml(xml: string): string {
  return xml.replace(/^\s+|\s+$|$\s+/gm, '');
}
```

Pasting the above code to ts-node gives:

```
> function minimizeXml(xml: string): string {
Thrown: ⨯ Unable to compile TypeScript
[eval].ts (2,1): '}' expected. (1005)
[eval].ts (1,36): A function whose declared type is neither 'void' nor 'any' must return a value. (2355)
>   return xml.replace(/^\s+|\s+$|$\s+/gm, '');
Thrown: ⨯ Unable to compile TypeScript
[eval].ts (1,3): A 'return' statement can only be used within a function body. (1108)
```

whereas, sending the definition of `minimizeXml` in one line (minimized) is successful.

### Expected

Pasting multiple line code segments to ts-node works.

**Comment by blakeembrey** [comment] 2018-03-23 06:05
It worked fine for me:

![image](https://user-images.githubusercontent.com/1088987/37814099-67cf5c2a-2e25-11e8-932f-75276c0ea3ac.png)

Can you provide some more information about your environment (e.g. `ts-node` version, node.js version, `tsconfig.json` file) that might impact this or something standalone I can use to reproduce?

**Comment by blakeembrey** [comment] 2018-04-07 23:41
Closing since I couldn't reproduce. Feel free to comment again in the future if it becomes an issue.

**Closed by blakeembrey** 2018-04-07 23:41 UTC
Labels: needs more info
