### ISSUE TITLE
Tsconfig.json with extends pointing to tsconfig.json in parent gives typeerror.

### ISSUE THREAD

**Issue by wvhulle** [TypeStrong/ts-node#1953] opened 2023-02-09 19:36 UTC
### Search Terms
Creating an extends entry in the tsconfig.json file that points to a tsconfig.json in a parent directory gives a type error "value.replace is not a function". It seems to be related to the file paths.

### Expected Behavior

Run main without type error.

### Actual Behavior
```
/home/..../node_modules/.pnpm/ts-node@10.9.1_phnrzqkcivvh6u4szhymjletvi/node_modules/ts-node/dist/util.js:62
    return value.replace(backslashRegExp, directorySeparator);
                 ^

TypeError: value.replace is not a function
    at normalizeSlashes (/home/..../node_modules/.pnpm/ts-node@10.9.1_phnrzqkcivvh6u4szhymjletvi/node_modules/ts-node/dist/util.js:62:18)
    at Object.getExtendsConfigPath (/home/..../node_modules/.pnpm/ts-node@10.9.1_phnrzqkcivvh6u4szhymjletvi/node_modules/ts-node/dist/ts-internals.js:24:54)
    at readConfig (/home/..../node_modules/.pnpm/ts-node@10.9.1_phnrzqkcivvh6u4szhymjletvi/node_modules/ts-node/dist/configuration.js:127:64)
    at findAndReadConfig (/home/..../node_modules/.pnpm/ts-node@10.9.1_phnrzqkcivvh6u4szhymjletvi/node_modules/ts-node/dist/configuration.js:50:84)
    at phase3 (/home/..../node_modules/.pnpm/ts-node@10.9.1_phnrzqkcivvh6u4szhymjletvi/node_modules/ts-node/dist/bin.js:254:67)
    at bootstrap (/home/..../node_modules/.pnpm/ts-node@10.9.1_phnrzqkcivvh6u4szhymjletvi/node_modules/ts-node/dist/bin.js:47:30)
    at main (/home/..../node_modules/.pnpm/ts-node@10.9.1_phnrzqkcivvh6u4szhymjletvi/node_modules/ts-node/dist/bin.js:33:12)
    at Object.<anonymous> (/home/..../node_modules/.pnpm/ts-node@10.9.1_phnrzqkcivvh6u4szhymjletvi/node_modules/ts-node/dist/bin.js:579:5)
    at Module._compile (node:internal/modules/cjs/loader:1239:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)

Node.js v19.4.0
```

### Steps to reproduce the problem
Make a typescript project with a child tsconfig.json extending a parent.

```
cd lib
chmod a+x ./main.ts
./main.ts
```

### Minimal reproduction

https://github.com/wvhulle/ts-node-bug-extends-parent-directory

### Specifications

* ts-node version: 10.9.1
* node version: Node.js v19.4.0
* TypeScript version: 5.0.0-dev.20230209
* tsconfig.json, if you're using one:
```
{
	"ts-node": {
		"experimentalSpecifierResolution": "node",
		"esm": true,
        "files": true
	},
	"compilerOptions": {
		"forceConsistentCasingInFileNames": true,
		"target": "ESNext",
		"useDefineForClassFields": true,
		"module": "ESNext",
		"lib": [
			"ESNext",
			"DOM"
		],
		"moduleResolution": "Node",
		"strict": true,
		"resolveJsonModule": true,
		"isolatedModules": true,
		"esModuleInterop": true,
		"noEmit": true,
		"noImplicitReturns": true,
		"baseUrl": "."
    },
	"exclude": [
		"./node_modules/**",
		"./.vscode/**"
	]
}
```
* package.json:
```
{
  "name": "typescript",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "type": "module",
  "devDependencies": {
    "@types/node": "^18.13.0",
    "ts-node": "^10.9.1",
    "typescript": "5.0.0-dev.20230209"
  }
}

```
* Operating system and version:
* If Windows, are you using WSL or WSL2?:
Linux Mint 21.1

**Comment by cspotcode** [comment] 2023-02-09 19:52
This is actually caused by #1954, it is not related to a parent directory.

I'm going to go ahead and close this issue to keep things tidy, and because #1954 can be used to track the implementation of this feature.

**Closed by cspotcode** 2023-02-09 19:52 UTC
