### ISSUE TITLE
Breaking change between 10.1.0 and 10.2.0 with regards to loading typescript

### ISSUE THREAD

**Issue by devshorts** [TypeStrong/ts-node#1427] opened 2021-08-09 22:58 UTC
### Expected Behavior
That minor version bumps would be back compat and not cause hidden errors

### Actual Behavior
```
circleci@49a06e581692:~/project/service$ npx ts-node
npx: installed 14 in 1.066s
Cannot find module 'typescript'
Require stack:
- /home/circleci/.npm/_npx/3711/lib/node_modules/ts-node/dist/index.js
- /home/circleci/.npm/_npx/3711/lib/node_modules/ts-node/dist/repl.js
- /home/circleci/.npm/_npx/3711/lib/node_modules/ts-node/dist/bin.js
circleci@49a06e581692:~/project/service$ npx ts-node@10.1.0
npx: installed 13 in 1.05s
```

Note how pulling in the latest ts-node fails with a cannot find module 'typescript' (even though its there) but 10.1.0 works fine.

**Comment by cspotcode** [comment] 2021-08-09 23:11
Closing as duplicate of #1426

**Closed by cspotcode** 2021-08-09 23:11 UTC
