### ISSUE TITLE
Interpreter error: Property 'exports' does not exist on type '{ id: string; }'

### ISSUE THREAD

**Issue by dinvlad** [TypeStrong/ts-node#369] opened 2017-06-22 16:49 UTC
Hi team,

I'm trying to use ts-node interpreter from a command line (for quick tests of ideas), but no matter what I do I get this error message: `[eval].ts (0,18): Property 'exports' does not exist on type '{ id: string; }'. (2339)`

I'm using ts-node v3.1.0 with node v7.10.0, installed as a global package for a regular user on Ubuntu 14.04. I simply type `ts-node` from the command line, and then for example `const x = 10;`, which returns the above error.

Is there any way to troubleshoot what might be causing that?

Thanks

**Comment by blakeembrey** [comment] 2017-06-22 18:00
It does seem like a duplicate of https://github.com/TypeStrong/ts-node/issues/351. Unfortunately I don't have a solution - this used to work before TypeScript changed the emit in 2.2 and I was forced to require `@types/node` to be installed going forward. The other issue remains open to try and resolve sometime soon.

**Closed by blakeembrey** 2017-06-22 18:00 UTC

**Comment by dinvlad** [comment] 2017-06-22 22:35
Hmm, actually `@types/node` is already installed (locally). Not sure what else to do. Thanks
