### ISSUE TITLE
typescript 3.9.5 support/usage 

### ISSUE THREAD

**Issue by high-malloy** [TypeStrong/ts-node#1071] opened 2020-07-01 07:13 UTC
when I use the typescript version 3.9.5 (Angular 10) then I get an error message:

TypeError: express_1.default is not a function

the support of typescript version 2.1 is required.

**Comment by cspotcode** [comment] 2020-07-01 14:05
@high-malloy without a reproducible example, this looks like something wrong with your code, not with ts-node.

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by cspotcode** [comment] 2020-07-09 16:28
@high-malloy I assume this was a problem with your code and you've been able to fix it.  I'm going to close this issue.  We can re-open if needed, but we will of course need a reproduction if a bugfix is required.

**Closed by cspotcode** 2020-07-09 16:28 UTC
