### ISSUE TITLE
Error: Cannot find module 'arg'

### ISSUE THREAD

**Issue by DPS34** [TypeStrong/ts-node#1552] opened 2021-11-23 10:55 UTC
I just installed ts-node, to ubuntu, and can't use it, when i try to use it i get this error: 

-------------------------------------
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'arg'
Require stack:
- /usr/share/nodejs/ts-node/dist/bin.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/share/nodejs/ts-node/dist/bin.js:8:13)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/share/nodejs/ts-node/dist/bin.js' ]
}
-------------------------------------

I saw this was fixed in 8.0.1, but i use 9.1.1. How can i fix it?

Ubuntu 20.04
Node.js v17.1.0

**Comment by cspotcode** [comment] 2021-12-10 18:22
If this doesn't reproduce with the newest version of ts-node then there's nothing we can do, because any bugfixes would be made in the next version of ts-node (the newest version)

**Comment by cspotcode** [comment] 2021-12-13 03:52
Closing for the reasons outlined in my previous comment.  If there is additional information, particularly if this reproduces on the most recent version of ts-node, then let us know and we can reopen this issue.

**Closed by cspotcode** 2021-12-13 03:52 UTC

**Comment by klequis** [comment] 2021-12-16 21:44
If it is helpful to anyone I had the same problem with the latest version of ts-node v10.4.0. 

- node 14.18.2
- Ubuntu 21.10

I now have resolved this. I suspect the problem could be one of two things I did.

1. tried to do `npm i -g ts-node` without `sudo` and got an error. Then ran with sudo.
2. installed ts-node before typescript.

Maybe neither of those were the problem but ... I deleted ts-node* from /usr/bin, installed typescript and then ts-node. Things I working now.

**Comment by cspotcode** [comment] 2021-12-16 23:14
Thanks, this appears to be a problem with the package manager not doing the right thing or failing to do the right thing due to permissions issues.  This confirms that it is not a ts-node bug and no action is required from us.

**Comment by hussamsindhu** [comment] 2021-12-23 08:50
> were the pro

with which command you delete ts-node ?

**Comment by sciffany** [comment] 2022-12-11 23:30
If it helps anyone, I forgot to `npm install`

**Comment by moezbenrebah** [comment] 2023-07-27 15:08
I have the same issue, with the same error message. I tried to run .ts files using "ts-node", I tried to install it inside a project folder, and globally, but every time I got the same error, even to check the "version" it returns the same error:

```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'arg'
Require stack:
- /usr/share/nodejs/ts-node/dist/bin.js
...
```

I use NodeJs 16 and Ubuntu 22.04
First I need to understand what's the error exactly, and how fix it please

**Comment by standardimagery** [comment] 2023-11-30 18:16
nvm use <node-version>

that fixes my issue

**Comment by standardimagery** [comment] 2023-11-30 18:17
nvm use ....

that fix my issue

**Comment by phamthainb** [comment] 2024-03-31 16:43
you can try using with `npx ts-node`

**Comment by hristinson** [comment] 2024-08-23 12:59
**npx ts-node** working! my environment 
Linux nb2302008 6.8.0-40-generic #40~22.04.3-Ubuntu SMP PREEMPT_DYNAMIC Tue Jul 30 17:30:19 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
