### ISSUE TITLE
Presence of .babelrc in cwd changes compiling behavior

### ISSUE THREAD

**Issue by brandones** [TypeStrong/ts-node#991] opened 2020-03-27 02:32 UTC
I've created [a repo](https://github.com/brandones/require-override-problem) to demonstrate the issue. I'm not sure that it's necessarily a problem with ts-node, but ts-node does play an important role.

Let's say, as demonstrated in the repo, that I have two packages, `foo/` and `bar/`.
```
cli/
  bin/
    cli.js
lib/
  index.tsx
  .babelrc
```

`cli/bin/cli.js` takes an argument `target_file`. It essentially just does a `require("ts-node").register(opts)` and then `require(target_file)`.

Let's say that `index.tsx` just looks like this:
```
import { blue } from "chalk";
console.log(blue("some very nice blue content"));
```

When I run `cli.js` from anywhere outside `lib/`, as in
- `node cli/bin/cli.js lib/index.tsx` or
- `cd cli; node bin/cli.js ../lib/index.tsx`,
`lib/index.tsx` is parsed and loaded as expected.

When run from `lib/` as `node ../cli/bin/cli.js index.tsx`,  I get

```
import { blue } from "chalk";
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Module.m._compile (/home/brandon/Code/require-override-problem/cli/node_modules/ts-node/src/index.ts:837:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

If I delete `lib/.babelrc`, then `lib/index.tsx` can be successfully loaded, even with `lib/` as the cwd.

### Expected Behavior

I expect ts-node to handle compilation of `require`d files, regardless of the presence or absence of a `.babelrc` file.

### Actual Behavior

The presence of a `.babelrc` file causes compilation to fail. It appears to cause `Module._compile` to refer to the default NodeJS `cjs/loader`.

### Steps to reproduce the problem

See [the repo](https://github.com/brandones/require-override-problem)

### Specifications

* ts-node version: 8.6.2
* TypeScript version: 3.8.3
* tsconfig.json, if you're using one: [also in the repo](https://github.com/brandones/require-override-problem/blob/master/cli/tsconfig.json)
* node version: 10.16.3
* Operating system and version: Ubuntu 19.10

**Comment by brandones** [comment] 2020-03-27 02:47
I mitigated the problem by adding `dir: __dirname` to the tsconfig I'm passing to `require("ts-node").register`.

**Comment by cspotcode** [comment] 2020-03-27 04:27
Your reproduction looks like it has some complexity that you didn't describe in your issue.  There's an `autodoc` thing being loaded, and it's patching node's require mechanism.  If that's not causing any problems, then it can be removed from the reproduction, right?  Or is it causing the problem?

You're also using `commander` which doesn't seem necessary to reproduce the problem.  I would remove it from the equation to make sure it's not causing issues.

I also see in your repo that you have `lib/index.tsx` but in your description, you refer to `bar/thing.js`  The different file extension suggests there might be some confusion, or perhaps your setup is actually a bit different than the reproduction.

ts-node behaves differently depending on the `dir` option, which defaults to your cwd.  It's different in your 2 scenarios.  I suspect that's the root of the problem, not the presence or absence of a `.babelrc` file.

**Comment by brandones** [comment] 2020-03-27 05:30
Sure, very fair about the reproduction being overcomplicated. Please [have another look](https://github.com/brandones/require-override-problem) now that the excess has been stripped away.

I'll fix the names in the narrative description above so that they match my reproduction, sorry about the confusion.

I'm not sure we're understanding each other about the `dir` option. Here are the two scenarios:
- the command is `node cli/bin/cli.js lib/index.tsx`, which succeeds
- the command is `cd cli; node bin/cli.js ../lib/index.tsx`, which fails

The code is identical, and does not include the `dir` option, in either scenario.

I would encourage you to check out the repository, now that it's properly minimal, and run the following experiments:
- run the commands above
- add `dir: __dirname` to the tsconfig and run the same commands again
- remove `dir: __dirname` from the tsconfig and `rm lib/.babelrc` and run the same commands again

Hopefully that clarifies things!

**Comment by cspotcode** [comment] 2020-03-27 13:39
Much appreciated.  It looks like your first bullet point, which you say succeeds for you, is actually failing for me.

Here's what I did:
```
git clone https://github.com/brandones/require-override-problem/
cd require-override-problem
cd cli
npm install
cd ../lib
npm install
cd ..
node cli/bin/cli.js lib/index.tsx
```
I get this error:
```
Error: Cannot find module 'lib/index.tsx'
Require stack:
- /d/Personal-dev/@TypeStrong/ts-node-repros/issue-991/require-override-problem/cli/bin/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/d/Personal-dev/@TypeStrong/ts-node-repros/issue-991/require-override-problem/cli/bin/cli.js:12:1)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
```

![image](https://user-images.githubusercontent.com/376504/77761433-6c79dc00-700e-11ea-9eda-a0c11931f667.png)

**Comment by brandones** [comment] 2020-03-27 23:21
Fascinating! I will see if I can repro in a docker container this weekend.

**Comment by cspotcode** [comment] 2020-04-02 17:48
@brandones any update on this?

**Comment by brandones** [comment] 2020-04-02 20:04
Sorry, I've been caught up in COVID response. Thanks for the ping. I'm going to try to get to it this weekend.

**Comment by cspotcode** [comment] 2020-04-02 20:06
No rush at all, do what you gotta do.  Thanks for the reply.

**Comment by cspotcode** [comment] 2020-04-22 16:23
@brandones have you been able to take another look at this?

**Comment by brandones** [comment] 2020-04-22 16:55
I haven't, and probably won't. Sorry about that.

**Comment by cspotcode** [comment] 2020-04-22 17:00
@brandones ok, I'm going to close this because it sounds like it was a problem on your end, not a ts-node bug.  We can always reopen in the future.

**Closed by cspotcode** 2020-04-22 17:00 UTC
Labels: needs more info
