### ISSUE TITLE
scope CLI option doesn't work as expected

### ISSUE THREAD

**Issue by ofagbemi** [TypeStrong/ts-node#1493] opened 2021-10-08 20:22 UTC
### Search Terms

"scope", "Emit skipped"

### Expected Behavior

Was reading through #693 and saw that a `--scope` flag fix in #1346 was merged. However, it doesn't appear to work on ts-node@10.2.1. I wrote a small script that imports from a module in the same yarn workspace. It runs successfully if I set `TS_NODE_SCOPE=true`, but crashes with an "Emit skipped" error when I use the `--scope` flag.

### Actual Behavior

The script exits successfully when I use `TS_NODE_SCOPE=true` while it crashes with an "Emit skipped" error when I use the `--scope` flag

### Steps to reproduce the problem

See `run.sh` here: https://github.com/TypeStrong/ts-node-repros/pull/19

`TS_NODE_SCOPE=true yarn ts-node b/index.ts --project b/tsconfig.json` works.

`yarn ts-node b/index.ts --project b/tsconfig.json --scope` fails.

### Minimal reproduction

https://github.com/TypeStrong/ts-node-repros/pull/19

### Specifications

* ts-node version: **10.2.1**
* node version: **v12.21.0**
* TypeScript version: latest
* tsconfig.json, if you're using one:
```
{
  "compilerOptions": {
    "allowJs": true
  },
  "include": ["index.ts"]
}
```
* Operating system and version: **macOS Big Sur**

**Comment by cspotcode** [comment] 2021-10-10 23:11
Looks like an issue with passing command-line arguments in the wrong order.  https://typestrong.org/ts-node/docs/configuration#cli-flags

Closing as not a bug.  If you believe it is a bug or I've misunderstood, we can always reopen this ticket.

**Closed by cspotcode** 2021-10-10 23:11 UTC
