### ISSUE TITLE
ReferenceError: exports is not defined (OSX)

### ISSUE THREAD

**Issue by ethanresnick** [TypeStrong/ts-node#437] opened 2017-09-29 21:11 UTC
The issue originally reported in #309 (or one very related to it) is back, possibly caused by the changes in #404.

Specifically:

```
$ ts-node
> export default 4;

[eval].ts:2
Object.defineProperty(exports, "__esModule", { value: true });
                      ^

ReferenceError: exports is not defined
    at [eval].ts:2:23
    at ContextifyScript.Script.runInContext (vm.js:53:29)
    at ContextifyScript.Script.runInNewContext (vm.js:59:15)
    at _eval (/usr/local/lib/node_modules/ts-node/dist/_bin.js:181:29)
    at REPLServer.replEval (/usr/local/lib/node_modules/ts-node/dist/_bin.js:220:18)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:433:10)
    at emitOne (events.js:115:13)
    at REPLServer.emit (events.js:210:7)
```

**Comment by blakeembrey** [comment] 2017-09-30 07:38
As the issue and PR states, it was fixed in #404. This is a duplicate. It hasn’t been released yet, you can check the commit log.

**Comment by blakeembrey** [comment] 2017-09-30 07:38
Duplicate of https://github.com/TypeStrong/ts-node/issues/351.

**Closed by blakeembrey** 2017-09-30 07:38 UTC

**Comment by ethanresnick** [comment] 2017-09-30 09:03
Got it; I didn't realize these changes hadn't been released. My apologies.
