### ISSUE TITLE
Invalid typescript is build successfully

### ISSUE THREAD

**Issue by k-stasevich** [TypeStrong/ts-node#952] opened 2020-01-31 12:26 UTC
I'm using `ts-node-dev` package which use `ts-node` inside. I noticed that there are no errors in build when TS is invalid.

When I'm running ts-node-dev build I don't see errors!
`ts-node-dev --respawn --no-notify ./src/server.ts`

Using ts-node version 8.6.0, typescript version 3.7.2 - no errors, but ts is invalid
Using ts-node version 8.6.2, typescript version 3.7.2 - no errors, but ts is invalid
Using ts-node version 8.5.2, typescript version 3.7.2 - there're errors if TS is invalid!

I understand that `ts-node-dev` is another package but it is based on `ts-node` and seems like problem is here!

**Comment by cspotcode** [comment] 2020-01-31 16:24
Please share a minimal, reproducible example of the incorrect behavior that
we can look at.  Without this, we cannot identify the problem.  You can
post it as a new GitHub repository or as a pull request on
https://github.com/cspotcode/ts-node-repros

Either way, be sure to post a link to it in this issue.

**Comment by cspotcode** [comment] 2020-02-03 20:05
@k-stasevich any update on this?

**Comment by k-stasevich** [comment] 2020-02-06 06:52
Yes sorry, please test it
test.ts
`
function foo(n: string) {
  return n;
}

console.log(foo(5));

`

package.json
`
{
  "name": "ts-issue",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "ts-node-dev test.ts",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "ts-node": "8.6.2",
    "ts-node-dev": "^1.0.0-pre.44",
    "typescript": "^3.7.5"
  }
}

`

**Comment by k-stasevich** [comment] 2020-02-06 06:53
and then downgrade `ts-node` to 8.5.2, and build will be failed (which is expected because it is invalid TS)

**Comment by k-stasevich** [comment] 2020-02-06 06:57
Hm, I just tested not `ts-node-dev` but just `ts-node` and it is failed in both cases (which is expected behavior), and it looks like problem is somewhere in `ts-node-dev` package

**Comment by cspotcode** [comment] 2020-02-06 14:51
@k-stasevich ok, sounds good, I'll close this since it's not a ts-node issue.  If that changes, we can definitely re-open.

**Closed by cspotcode** 2020-02-06 14:51 UTC
Labels: needs more info
