### ISSUE TITLE
--inspect isn't working for me

### ISSUE THREAD

**Issue by ndthanhdev** [TypeStrong/ts-node#542] opened 2018-02-27 18:33 UTC

**Comment by pherret** [comment] 2018-02-27 20:25
@ndthanhdev It seems adding port helped me `ts-node --inspect=9229 ./src/index.ts`

**Comment by blakeembrey** [comment] 2018-03-01 04:27
Duplicate of https://github.com/TypeStrong/ts-node/issues/537.

**Closed by blakeembrey** 2018-03-01 04:27 UTC
