### ISSUE TITLE
cannot resolve types with esm format and transpile only when using dynamic import

### ISSUE THREAD

**Issue by hesxenon** [TypeStrong/ts-node#1549] opened 2021-11-21 21:55 UTC
### Search Terms

"transpile only type export"

### Expected Behavior

ts-node should not care about re-exported or imported types when ordered to only transpile typescript - even with esm modules and dynamic imports

### Actual Behavior

ts-node complains that the module does not provide an export named `<whatever-your-type-is-called>`

### Steps to reproduce the problem

1. create ts project with esm module format
2. create a module `A` that exports a type
3. create a module `B` that re-exports the type from module `A`
4. dynamically require module `B`

### Minimal reproduction

https://github.com/hesxenon/ts-node-esm-problem

### Specifications

```
$ npx ts-node -vv
ts-node v10.4.0
node v16.11.1
compiler v4.5.2
```
* tsconfig.json, if you're using one:
part of the linked repo
* Operating system and version:
Linux 5.14.16-arch1-1

**Comment by cspotcode** [comment] 2021-12-10 18:30
Is `ts-node` complaining, or is `node` complaining?  I ask because if you disable any typechecking, then the code emitter has no idea if your `export {} from` statement in `dynamic.ts` is attempting to import/export a type or a value.

**Comment by cspotcode** [comment] 2021-12-22 16:35
Closing as not a bug, likely needs the `type` keyword added to some imports or exports to be compatible with non-typechecking compilation modes.

**Closed by cspotcode** 2021-12-22 16:35 UTC

**Comment by hesxenon** [comment] 2021-12-22 20:23
sorry for the late reply, for some reason github stopped sending me notifications :/

no, it was `ts-node` complaining. The thing with the missing `type` keyword (to which I've found plenty of threads) is that it's not always possible to add this keyword. The behaviour - iirc - also occurs when you're exporting everything from another file as a namespace. Afaik it's not possible to split the exports between types and values and have those merged into the same namespace.

For my case it's not relevant anymore, I've moved away from ts-node, but imho you should look into this.

**Comment by cspotcode** [comment] 2021-12-22 21:44
@hesxenon 

I'm betting the error you saw was a node runtime error, not from ts-node.  ts-node delegates to the typescript compiler and runs on top of the node runtime, so you can get errors coming from the node runtime when it tries to execute code from the typescript compiler, due to incorrectly-configured compiler options.

This flag allows the typescript compiler to flag this mistake *when it is running the typechecker.*  So it will *not* flag this mistake in transpileOnly mode.  The idea is you typecheck as a separate step, perhaps in your lint step.
https://www.typescriptlang.org/tsconfig#importsNotUsedAsValues

See also: this new feature of TypeScript which allows annotating individual imports as type-only, allowing non-typechecking compilers to elide them.
https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/#type-on-import-names

**Comment by hesxenon** [comment] 2021-12-22 23:21
```
$ npm run no-workee

> tmp@1.0.0 no-workee
> TS_NODE_TRANSPILE_ONLY=true npm run workee


> tmp@1.0.0 workee
> node --loader=ts-node/esm --experimental-specifier-resolution node index.ts

(node:106710) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
file:///home/hesxenon/projects/ts-node-esm-problem/dynamic.ts:1
export { t } from "./test";
         ^
SyntaxError: The requested module './test' does not provide an export named 't'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:127:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:191:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
```

so, it looks like `node` is complaining afterall, sorry for the mistake. As I've said, I've moved on already so it's not exactly fresh. Still, I've cloned the repro-repo above and just ran the two npm scripts.

The `no-workee` script should run in transpileOnly mode, with the default ts setting of removing type only imports, yet it still fails because it's not about importing but exporting.

After running a few tests on that repro-repo the following seems to hold true with typescript@>=4.5

* `export * as X from "./test"` works as expected
* `export { type t } from "./test"` works in transpileOnly mode but requires typescript@>=4.5
* `export { t } from "./test"` does not work in transpileOnly mode

So what you're saying is that import and export statements that don't explicitly mark which tokens are types won't get removed in transpileOnly mode and thus node throws an error?

**Comment by cspotcode** [comment] 2021-12-23 03:27
Yeah, from your reproduction, `test.ts` compiles from:
```
export type t = number;
```
into
```
// empty file
```
because any transpiler -- typechecking or not -- is going to omit the `type` statement.

`dynamic.ts` compiles from:
```
export { t } from "./test";
```
into
```
export { t } from "./test";
```
Without type-checking, the transpiler does not know whether or not `t` is a type import.  Note that typescript *with typechecking* will omit the `export { t } from "./test";` because it has the necessary type info to understand `t` will not exist at runtime.

Looking at the two *output* files, it's clear why node raises that error.

TypeScript has dedicated flags to support avoiding these issues: [`isolatedModules`](https://www.typescriptlang.org/tsconfig#isolatedModules) and [`importsNotUsedAsValues`](https://www.typescriptlang.org/tsconfig#importsNotUsedAsValues)
