### ISSUE TITLE
Cannot install with yarn on Node 8 or 9

### ISSUE THREAD

**Issue by Darep** [TypeStrong/ts-node#941] opened 2020-01-12 11:37 UTC
The `yn` package was updated to v4.0.0 in ts-node@8.6.0. It seems that [yn@4.0.0 now requires node >= 10](https://github.com/sindresorhus/yn/blob/028ca5df4818a6fc519bd349686619218f5c3312/package.json#L13) so ts-node v8.6.0 and newer might error when installing/starting on Node.js 8 or 9. At least when using yarn.

For example, on a fresh Node.js v8.12 Docker container:

```
$ docker run --rm -it node:8.12-alpine yarn add ts-node@latest
yarn add v1.9.4
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
error yn@4.0.0: The engine "node" is incompatible with this module. Expected version ">=10".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

Same in the Node.js 9 image:

```
$ docker run --rm -it node:9 yarn add ts-node@latest
yarn add v1.5.1
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
error yn@4.0.0: The engine "node" is incompatible with this module. Expected version ">=10".
error An unexpected error occurred: "Found incompatible module".
info If you think this is a bug, please open a bug report with the information provided in "/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

Contrary to yarn, npm doesn't seem to fail atleast on the CLI. npm just outputs a warning:

```
npm WARN notsup Unsupported engine for yn@4.0.0: wanted: {"node":">=10"} (current: {"node":"8.12.0","npm":"6.13.6"})
npm WARN notsup Not compatible with your version of node/npm: yn@4.0.0
```

Though e.g. `pm2 install typescript` uses npm and on Node 8 or 9 it will actually fail 😄

**Comment by cspotcode** [comment] 2020-01-12 21:21
Closing as a duplicate of #940.

**Closed by cspotcode** 2020-01-12 21:21 UTC
