### ISSUE TITLE
Abridged stack traces

### ISSUE THREAD

**Issue by hath995** [TypeStrong/ts-node#575] opened 2018-04-22 23:07 UTC
After switching to using ts-node, I seem to be getting abridged stack traces. 
```
TypeError: Cannot read property 'get' of null
  File "/var/app/current/src/helpers/profile.ts", line 21, col 25, in Object.exports.getAddressSummary.lgAddr [as getAddressSummary]
    return {
  File "/var/app/current/src/routes/profile.ts", line 56, col 28, in router.get
    * @api { GET }             /profile
  ?, in null.<anonymous>
```
Is this a bug or do I need to configure something or this just the state of things?

**Comment by blakeembrey** [comment] 2018-04-24 14:16
I haven't seen this before, can you specify your set up and versions? Especially versions for `ts-node`, node.js and TypeScript.

**Comment by hath995** [comment] 2018-04-25 23:29
Node v8.8.1
TypeScript 2.8.3
ts-node 4.1.0

**Comment by blakeembrey** [comment] 2018-04-26 00:33
It seems like it'd most likely be related to https://github.com/evanw/node-source-map-support if it's error related. Are you possibly activating it more than once? (e.g. https://github.com/evanw/node-source-map-support/issues/200). How are you using `ts-node`?

**Comment by hath995** [comment] 2018-04-26 01:25
We are running the code on AWS using the command `npx ts-node bin/server.ts`. no other options.

**Comment by hath995** [comment] 2018-04-26 01:31
I'm not aware of doubling up on node-source-map but all of this is the context of a Koa2 server route and we are using Sentry.io error reporting library. I'll look into those and see if they might be loading it twice.

**Comment by cspotcode** [comment] 2021-06-14 03:33
Closing as likely not a bug, or at least not a bug anymore.

**Closed by cspotcode** 2021-06-14 03:33 UTC
