### ISSUE TITLE
"Cannot find module 'http'. (2307)" with "@types/node" under typescript@2.0.3

### ISSUE THREAD

**Issue by zixia** [TypeStrong/ts-node#216] opened 2016-10-11 03:25 UTC
**TypeScript Version:**  

2.0.3

**Code**

``` ts
// A *self-contained* demonstration of the problem follows...
// t.ts
import * as http from 'http'
console.log(typeof http)
```

``` shell
$ ./node_modules/.bin/ts-node -v
ts-node v1.4.1
node v6.0.0

$ ./node_modules/.bin/tsc -v     
Version 2.0.3

$ npm install @types/node
wechaty@0.4.0 /Users/zixia/git/wechaty
└── @types/node@6.0.45

$ ./node_modules/.bin/ts-node --no-cache t.ts

D:\cygwin64\home\zixia\git\wechaty\node_modules\ts-node\dist\index.js:166
                    throw new TSError(diagnosticList);
                          ^
TSError: ⨯ Unable to compile TypeScript
t.ts (1,23): Cannot find module 'http'. (2307)
```

**Expected behavior:**

should import http as well

**Actual behavior:** 

TS2307 error

**Another STRANGE behavior**

if I add another @types into t.ts, it will work without any problem.

``` shell
$ cat t.ts
import * as http from 'http'
console.log(typeof http)

import * as express from 'express'
console.log(typeof express)

zixia@zixia-desktop ~/git/wechaty
$ ./node_modules/.bin/ts-node --no-cache t.ts
object
function
```

very interesting, what's wrong with me?

**Comment by ljani** [comment] 2016-10-14 19:36
I have the same problem. It seems I can workaround it using the following directive at the top of my file (which is located in `./src/`):
```
///<reference path="../node_modules/@types/node/index.d.ts"/>
```

Running `tsc` works fine. `ts-node` seems to be missing the global references `tsc` has.

**Comment by paulsouche** [comment] 2016-12-09 17:00
Hi,

I had the same issue with mocha on #246

The problem is that module http is ambient declared by node declaration file. What ts-node do is
 - find http directory in @types folder
 - no directory - Error

My first solution was to import module mocha

```typescript
import * as mocha from 'mocha';
```

To have all mocha declarations available but I did not know that we could declare an ambient module via

```typescript
/// <reference types="mocha" />
```

Declaring mocha as ambient in tsconfig.json did not work for me

```json
{
  "compilerOptions": {
    "types": ["mocha"]
  }
}
```

I don't know why exactly because it should be equivalent...

Again I faced a new issue not declaring these references outside of my tests in a separated file with only one spec file.

It works with two spec files ??? I think this is most a mocha --compilers issue.

I've created a repo [here](https://github.com/paulsouche/tsnode-216) explaining the solution.

**Comment by MrCrimp** [comment] 2016-12-12 15:50
My fix for windows, after trying most suggestions, was to remove `types` and instead use

```
"typeRoots": [
      "node_modules/@types"
    ],
```

in combination with adding this to my src/typings.d.ts

```
/// <reference types="@types/mocha" />
```
Tsnode 1.7.0
TypeScript 2.1.1 and 2.1.4

**Comment by cloutiertyler** [comment] 2017-01-30 00:21
I seem to be getting this exact error on Linux, and unfortunately the work arounds here do not appear to work.

**Comment by samvloeberghs** [comment] 2017-02-08 13:04
@MrCrimp although that also solved it for me, the bug remains. 

As per the documentation of TypeScript:
https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types

> By default all visible “@types” packages are included in your compilation. Packages in node_modules/@types of any enclosing folder are considered visible; specifically, that means packages within ./node_modules/@types/, ../node_modules/@types/, ../../node_modules/@types/, and so on.

Be aware that using this solutions, you may introduce some side effects / unexpected behavior:

> If typesRoots is specified, only packages under typeRoots will be included.

**Comment by renehamburger** [comment] 2017-02-28 18:16
A combination of 'typeRoots' and `types` worked for me on Windows (TypeScript@2.2.1, ts-node@2.1.0):
```json
"compilerOptions": {
  "typeRoots": [
    "node_modules/@types"
  ],
  "types": [
    "mocha"
  ]
}
```
(On OS X, neither of these was needed, and I'm sure the same is true for Linux.)

**Comment by massimocode** [comment] 2017-03-06 07:42
We are facing what seems to be a related issue. In our scenario, we have multiple `typeRoots` and packages are not being found in those `typeRoots`. The code can be seen here:
https://github.com/SMH110/Pizza-website/pull/198

And the error can be seen here:
https://app.shippable.com/runs/58bd1167ba295305001507e7/1/console

However, what we're seeing is that it works fine on Windows, and we only get this error on Linux.

**Comment by blakeembrey** [comment] 2017-03-21 01:08
This should be resolved with `v2.1.1` now, let me know how that goes!

**Closed by blakeembrey** 2017-03-21 01:08 UTC
Labels: bug, windows

**Comment by kalahari** [comment] 2017-06-29 06:00
I am getting this with `ts-node` 2.1.2 and `typescript` 2.4.1. If I take `typescript` back to 2.3.4 it works.

**Comment by collinforrester** [comment] 2017-07-04 19:27
I am also getting this on `ts-node` 3.0.4 and `typescript` 2.4.1 (node 6.10.0 on mac).  If I downgrade `typescript` to 2.3.4 it also starts working for me again.

**Comment by jochenseeber** [comment] 2017-07-04 22:38
I also have this problem on MacOS. I created a minimal test project. Running

```bash
yarn install
gulp
```
results in the following output:

```
[node-test.zip](https://github.com/TypeStrong/ts-node/files/1123143/node-test.zip)

[00:37:40] Requiring external module ts-node/register

/Users/jochen/Projects/Scratch/node-test/node_modules/ts-node/src/index.ts:296
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
gulpfile.ts (3,29): Cannot find module 'gulp-typescript'. (2307)
    at getOutput (/Users/jochen/Projects/Scratch/node-test/node_modules/ts-node/src/index.ts:296:15)
    at /Users/jochen/Projects/Scratch/node-test/node_modules/ts-node/src/index.ts:325:16
    at Object.compile (/Users/jochen/Projects/Scratch/node-test/node_modules/ts-node/src/index.ts:479:11)
    at Module.m._compile (/Users/jochen/Projects/Scratch/node-test/node_modules/ts-node/src/index.ts:379:43)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/jochen/Projects/Scratch/node-test/node_modules/ts-node/src/index.ts:382:12)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
```

**Comment by blakeembrey** [comment] 2017-07-05 02:50
@jochenseeber Your issue is caused by a lack of `moduleResolution` in your `tsconfig.json` file and having it set to `module: es6`. If you were emitting `commonjs`, it would default to node module resolution. I'm not sure that's a regression since non-CommonJS code would never run on node.js anyway, but if someone wants to create a demo of something that has regressed please share.

**Comment by nevir** [comment] 2017-07-08 22:18
I'm also seeing this on OS X with ts-node@3.2.0, typescript@2.4.1 and the config below.

`tsc` compiles, but `ts-node` fails to find any types declared via `@types/*` packages

```json
{
  "compilerOptions": {
    "charset": "utf-8",
    "declaration": true,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "importHelpers": true,
    "jsx": "react",
    "lib": [
      "dom",
      "es2016",
      "es2017.object"
    ],
    "module": "commonjs",
    "newLine": "LF",
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "outDir": "./dist/",
    "pretty": true,
    "rootDir": ".",
    "sourceMap": true,
    "strictNullChecks": true,
    "target": "es5"
  }
}
```

**Comment by danielpa9708** [comment] 2018-01-29 19:00
I have the same problem in linux, 

```
$ tsc --version
Version 2.6.2
$ node --version
v6.12.3
$ cat tsconfig.json 
{
    "compilerOptions": {
        "rootDir": ".",
        "module": "commonjs",
        "target": "es6",
        "strict": true,
        "noImplicitAny": false,
        "noImplicitThis": true,
        "moduleResolution": "node",
        "outDir": "./dist/",
        "baseUrl": ".",
        "paths": {
            "*": [
                "node_modules/*"
            ]
        }
    },
    "include": [
        "./index.ts"
    ]
}
$ cat index.ts 
import * as http from "http";
$ tsc -p .
index.ts(1,23): error TS2307: Cannot find module 'http'.
```

**Comment by paulsouche** [comment] 2018-01-30 14:20
@danielpa9708 add

```json
{
  "typeRoots": [
    "./node_modules/@types"
  ],
  "types": ["node"]
}```

In your `compilerOptions` and be sure to have ``@types/node` installed

**Comment by scott-lin** [comment] 2018-07-18 22:49
I'm seeing this on Windows 10 using `"ts-node": "^7.0.0"`. I tried Paul's suggestion, but it did not help.

```
> tsc --version
Version 2.6.2
> npm --version
6.2.0
> cat .\tsconfig.json
{ 
  "compilerOptions": {
     "target": "es6",
     "module": "commonjs"
  }
}
> cat index.ts 
import * as http from "http";
> tsc -p .
index.ts(1,23): error TS2307: Cannot find module 'http'.
```

**Comment by NoelSkenshee** [comment] 2022-06-09 06:11
The solution to this problem is  than you think :
1     npm i -D typscript
2     npm tsc init
💯 🥇
