### ISSUE TITLE
windows: cannot find type definition file for node/jasmine

### ISSUE THREAD

**Issue by tycho01** [TypeStrong/ts-node#284] opened 2017-03-06 21:59 UTC
I ran into a Windows issue on `2.0.0`, matching @sweetim's report [here](https://github.com/TypeStrong/ts-node/issues/266#issuecomment-275106688):
> when I am using ts-node on Windows, it will complain `cannot find type definition file for node` which is related to issue #216 , this doesnt happen at Linux.

Bash on Windows does indeed seem to relieve this issue...

**Comment by blakeembrey** [comment] 2017-03-06 22:43
Seems like an exact duplicate of https://github.com/TypeStrong/ts-node/issues/283 too? If someone using Windows can submit a PR here or correct the bug in TypeScript, that'd be really helpful to me. If I had to guess, it's _probably_ a TypeScript `normalizeSlashes` issue with the base path of the `tsconfig.json` content parser (TypeScript has a funky external API where it sometimes supports real paths and sometimes only supports paths where backslashes are replaced with forward slashes).

**Closed by blakeembrey** 2017-03-06 22:43 UTC

**Comment by tycho01** [comment] 2017-03-06 22:46
Whoops, looks like my search failed me there...

**Comment by maiasmith** [comment] 2017-06-28 18:30
I had this error while trying to run npm run e2e on a mac, and fixed it with the following:

I received this error as well, and I fixed it by changing my package.json "scripts" variable from:
```

    "scripts": {
        ...
        "pree2e": "webdriver-manager update --standalone false --gecko false",
        "e2e": "protractor"
      }

```
to 
```

    "scripts": {
        ...
        // REMOVE "pree2e"
        "e2e": "ng e2e"
      }
```
