### ISSUE TITLE
TypeError: Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by DOrlov77** [TypeStrong/ts-node#94] opened 2016-04-07 17:44 UTC
Hi, I get that error when use the lib with protractor tests.
The exception occurs when "ts" file imports "d.ts". 
The problem is in a bug in return line of **getOutput** method :
```
function getOutput(fileName) {
        var output = service.getEmitOutput(fileName);
        var diagnostics = getDiagnostics(service, fileName, options, ts);
        if (output.emitSkipped) {
            diagnostics.push(path_1.relative(cwd, fileName) + ": Emit skipped");
        }
        if (diagnostics.length) {
            throw new TSError(diagnostics);
        }
        return output.outputFiles[0].text;
    }
```
The typescript usually converts d.ts file to nothing, so you need to check such case.
```
...
        return output.outputFiles.length ? output.outputFiles[0].text : '';
...
```

**Comment by blakeembrey** [comment] 2016-04-07 18:04
If what you're saying is an issue, this won't fix it - it'll make it worse.

**Comment by DOrlov77** [comment] 2016-04-07 21:06
May be, I didn't research the code in deep, but the workaround did a trick right now for my configuration.
I'm sure you will find the best solution.

**Comment by blakeembrey** [comment] 2016-04-07 21:09
I'll try to investigate, it sounds easy to reproduce. If you're returning an empty string, the resolved JS is theoretically an empty string. Which means nothing executes on that `require`.

**Comment by DOrlov77** [comment] 2016-04-10 07:41
That is Ok because interface been compiled to nothing (to empty JS).  :)

**Comment by blakeembrey** [comment] 2016-04-10 23:34
@DOrlov77 Right, I need to test it. My concern was that you didn't want the empty string and the `.d.ts` was taking precedence somehow over the `.js` file you had - which would create some issues here that I'd need to properly investigate. Instead, you're saying that you're just importing from a `.d.ts` file - there's no implementation?

**Comment by DOrlov77** [comment] 2016-04-11 13:03
The main idea of d.ts files is to move out ```declaration``` code, so you could use it without having the source implementation (at compile time of course). In my case I have a 3rd party libs written in pure JS but with d.ts declaration files with interfaces only.

**Comment by blakeembrey** [comment] 2016-04-12 23:16
Do you have a way to replicate it? Using `.d.ts` and `.js` is common and, as far as I believe, works fine.

**Comment by DOrlov77** [comment] 2016-04-13 11:40
For example:
in protractor.conf.js:
```
...
var tsNode = require('ts-node').register();
...
var suites = {"01": "01.spec.ts"}
```
in the spec file ("01.spec.ts"):
```
...
import '../../../build-utils/typings/node/node.d.ts';
...
describe() {...}
```
for debug purpose in ts-node.js:
```
function getOutput(fileName) {
...
        // return output.outputFiles.length ? output.outputFiles[0].text : '';
        console.warn('~~~~~~~ fileName', fileName);
        return output.outputFiles[0].text;
    }
``` 

Ready? Run protractor test and get:
```
~~~~~~~ fileName d:\workspace\nolio\rp-main\ui\main\e2e\releases\01releasesPage.spec.ts
~~~~~~~ fileName d:\workspace\nolio\rp-main\ui\build-utils\typings\node\node.d.ts
[launcher] Error: TypeError: Cannot read property 'text' of undefined
    at getOutput (d:\workspace\nolio\rp-main\ui\node_modules\ts-node\src\ts-node.ts:215:37)
    at Object.loader (d:\workspace\nolio\rp-main\ui\node_modules\ts-node\src\ts-node.ts:227:25)
    at Module.load (d:\workspace\nolio\rp-main\ui\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (d:\workspace\nolio\rp-main\ui\main\e2e\releases\01releasesPage.spec.ts:5:1)
    at Module._compile (module.js:413:34)
    at Object.loader (d:\workspace\nolio\rp-main\ui\node_modules\ts-node\src\ts-node.ts:227:3)
    at Module.load (d:\workspace\nolio\rp-main\ui\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at d:\workspace\nolio\rp-main\ui\node_modules\jasmine\lib\jasmine.js:71:5
    at Array.forEach (native)

```

I use protractor v3.2.2, node v5.6.0

All paths in the log are correct.
If you uncomment my fix (before console output) - all works like a charm! :)

**Comment by blakeembrey** [comment] 2016-04-13 16:26
@DOrlov77 You're using imports wrong. That should be a reference.

**Comment by DOrlov77** [comment] 2016-04-14 11:34
Not so - that is the way to import ambient modules with global content defined.
Just try to work with [node.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/node/node.d.ts)

In my case using ```reference``` in 01.spec.ts:
```
/// <reference path="../../../build-utils/typings/node/node.d.ts" />
...
describe() {...}
...
```

will cause an error:
```
[launcher] Error: TSError: ⨯ Unable to compile TypeScript
01.spec.ts (10,1): Cannot find name 'describe'. (2304)
```

It is possible I do something wrong still and could you suggest other valid pattern?

**Comment by blakeembrey** [comment] 2016-04-14 16:17
@DOrlov77 Usually you'd use `tsconfig.json` to configure that. Even then, it should work fine - I'd suggest narrowing down the use-case and trying to compile with `tsc`.

**Comment by DOrlov77** [comment] 2016-04-15 11:03
Again: using ```import 'relative/path/to/ambient/module.d.ts'``` - is a valid solution from TS team and works perfect with ```tsc```. So the question is for you still - why don't you just support that case?

**Comment by blakeembrey** [comment] 2016-04-15 16:35
> valid solution from TS team

Is that documented somewhere?

> why don't you just support that case?

I haven't seen any reason to support it. You're using the definition in a value position, why wouldn't you expect a value to come out of the import?

**Comment by DOrlov77** [comment] 2016-04-15 19:27
:) Exactly - I DO expect a value that come out of the import! NULL - is a valid value. But get an exception instead of it - see my first message. :) Anyway - I got your answer.

**Comment by jeffijoe** [comment] 2016-07-07 15:21
I'm experiencing this issue as well when `import './some/type.d.ts`

**Comment by blakeembrey** [comment] 2016-07-07 15:45
Sorry, that was a typo - meant to say "would" of course.

Please read the conversation, it's not how you should be using typescript.

**Closed by blakeembrey** 2016-07-07 15:45 UTC
Labels: bug, research

**Comment by jeffijoe** [comment] 2016-07-07 15:50
I'm not sure I understand - isn't `import './some/type.d.ts'` the new way of importing type defs?

**Comment by blakeembrey** [comment] 2016-07-07 15:55
No. Never has been. You can not import types in a value position.

**Comment by blakeembrey** [comment] 2016-07-07 15:57
I don't know where people keep coming up with this, but I'd recommend reading up on typescript and the tsconfig file. That's how you should be configuring your references to definitions. You should never have to import or reference a definition.

**Comment by jeffijoe** [comment] 2016-07-07 16:04
I can't find anything on the [tsconfig,json](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html) docs that mentions anything about definitions

**Comment by blakeembrey** [comment] 2016-07-07 17:28
If you're using `files`, add it to that. If you're using references, use that. If you're using exclude, make sure it's in the project context.

**Comment by jeffijoe** [comment] 2016-07-07 17:30
I'm not using files, I'm using rootDir - adding to files is not picked up by Code.

~ Jeff Hansen

**Comment by blakeembrey** [comment] 2016-07-07 17:33
Yes, it is. I use it all the time. Please share a reproduction or example of the issue you're facing, I've mentioned everything I can think of. Perhaps you can look at other projects written in TypeScript? There's a few under my own user such as https://github.com/TypeStrong/ts-node/blob/master/tsconfig.json or https://github.com/blakeembrey/node-scrappy/blob/master/tsconfig.json (each of these uses the files or exclude approach).

**Comment by jeffijoe** [comment] 2016-07-07 17:40
In my case I have a tsconfig in the root, and one for tests (else the compiler vomits since test isnt in the rootDir)

~ Jeff Hansen
